//go:build !jsonschema

// Code generated by internal/generate. DO NOT EDIT.

package implementation

import (
	"context"
	"os"
	"os/signal"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/tylergannon/gimble"
	"github.com/tylergannon/gimble/internal/binding"
	"github.com/tylergannon/gimble/web"
	"github.com/tylergannon/gimble/workflow"
)

func init() { gimble.RegisterGraph(Graph) }

// Graph is the shape of this workflow, read from the source of Implement.
var Graph = workflow.Graph{
	Name:   "implement",
	Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 60},
	Body: []workflow.Operation{
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 61}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 61}, Case: "params.MaxTasks < 1", Exits: true, Body: []workflow.Operation{}},
		}},
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 65}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 65}, Case: "validationCommand == \"\"", Exits: true, Body: []workflow.Operation{}},
		}},
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 76}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 76}, Case: "!info.Mode().IsRegular()", Exits: true, Body: []workflow.Operation{}},
		}},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 80}, Key: "requirements file"},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 81}, Key: "repository"},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 82}, Key: "fixed validation command"},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 83}, Key: "maximum tasks"},
		workflow.Session{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 85}, Name: "sprint-planning", From: ""},
		workflow.Session{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 86}, Name: "architectural-critique", From: ""},
		workflow.PromiseLoop{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 89}, Name: "implementation", Planner: "sprint-planning", Supervisors: []workflow.Supervisor{
			{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 90}, Session: "architectural-critique", Role: "architectural-critique", Instruction: "Keep the plan inside the requirements file. Object to invented features, speculative infrastructure, polishing, or unrelated repairs. Preserve failed checks and validator findings as evidence for replanning; do not declare the overall goal complete merely because dispatch can stop."},
		}, Body: []workflow.Operation{
			workflow.Session{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 98}, Name: "coding", From: ""},
			workflow.Session{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 99}, Name: "architectural-critique", From: ""},
			workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 100}, Session: "coding", Role: "coding", Prompt: "Read the requirements file and implement only the selected task in the repository. Make the actual source changes and run useful focused checks. Do not edit the requirements, this workflow, or the fixed validation command; do not commit, push, merge, deploy, or add proof scripts and run output. Preserve unrelated work. Answer with what changed and what you personally ran or observed.", Supervisors: []workflow.Supervisor{
				{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 101}, Session: "architectural-critique", Role: "architectural-critique", Instruction: "Watch only for concrete work beyond the selected assignment or the requirements file. Object to invented features, speculative abstractions, weakened validation, edits to the requirements, and unrelated cleanup. Do not edit source or demand optional polish."},
			}},
			workflow.Set{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 106}, Key: "worker report"},
			workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 109}, Branches: []workflow.Branch{
				{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 109}, Case: "command := strings.TrimSpace(task.Validation.Command); command != \"\"", Exits: false, Body: []workflow.Operation{
					workflow.Command{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 110}, Name: "task-check"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 115}, Key: "task check"},
				}},
			}},
			workflow.Command{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 119}, Name: "fixed-validation"},
			workflow.Set{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 124}, Key: "fixed validation"},
			workflow.Session{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 126}, Name: "qa-orchestration", From: ""},
			workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 127}, Session: "qa-orchestration", Role: "qa-orchestration", Prompt: "Independently read the complete requirements file, inspect the actual repository changes and recorded command results, and run any additional focused checks needed to assess required behavior. Make no source changes and do not treat the worker report as proof. Complete is true only when every requirement is satisfied and credibly demonstrated; a passing fixed command establishes only what it actually exercises. Report concrete unmet requirements or invalid evidence, not style preferences, optional polish, or unrelated improvements."},
			workflow.Set{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 132}, Key: "independent assessment"},
			workflow.Set{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 134}, Key: "deterministic checks passed"},
			workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 135}, Branches: []workflow.Branch{
				{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 135}, Case: "checksPassed && assessment.Complete", Exits: true, Body: []workflow.Operation{}},
			}},
			workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 139}, Branches: []workflow.Branch{
				{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 139}, Case: "tasksRun >= params.MaxTasks", Exits: true, Body: []workflow.Operation{}},
			}},
		}},
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 150}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 150}, Case: "completed", Exits: true, Body: []workflow.Operation{}},
		}},
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 153}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/implementation/implementation.go", Line: 153}, Case: "exhausted", Exits: true, Body: []workflow.Operation{}},
		}},
	},
}

// Command is gimble run implement: Gimble's environment flag, a flag for each field of Params, a
// model flag for each role Implement names with defaults supplied by the caller,
// the web application's flags, and a run of Implement on the runtime.
func Command(defaults map[gimble.WorkflowRole]string) *cobra.Command {
	var params Params
	var sprintPlanningModel string
	var architecturalCritiqueModel string
	var codingModel string
	var qaOrchestrationModel string
	var workDir string
	var port int
	var uds string
	var noWeb bool
	cmd := &cobra.Command{
		Use:   "implement",
		Short: "Implement modifies a repository until its requirements are independently demonstrated.",
		Long:  "Package implementation implements a local requirements file through a\nbounded, planner-directed loop and independently validates the result.\n\nThe requirements file is the authoritative goal. On each lap, a planner\nchooses the next coherent assignment, a fresh coding agent implements it,\nand the workflow runs both the planner's optional task check and one fixed\ncaller-supplied validation command. A fresh validator then inspects the\ncomplete requirements and the actual repository. Failed deterministic\nvalidation cannot be overruled by an agent's judgment.\n\nThe workflow does not commit, push, merge, deploy, or rewrite the\nrequirements. It succeeds only when the fixed command passes and the\nindependent validator finds the complete requirements satisfied. Otherwise\nit replans until the task limit is exhausted or the planner stops honestly.\n\nExample:\n\n\tgimble run implement \\\n\t  --requirements-file ./issue.md \\\n\t  --validation-command \"just build && just test\" \\\n\t  --max-tasks 8",
		Args:  cobra.NoArgs,
	}
	cmd.Flags().StringVar(&params.RequirementsFile, "requirements-file", "", "RequirementsFile is the local file whose complete requirements the run implements. (required)")
	cmd.Flags().StringVar(&params.ValidationCommand, "validation-command", "", "ValidationCommand is the fixed shell command that must pass before the run can succeed. (required)")
	cmd.Flags().IntVar(&params.MaxTasks, "max-tasks", 0, "MaxTasks is the maximum number of planner assignments the run may execute. (required)")
	_ = cmd.MarkFlagRequired("requirements-file")
	_ = cmd.MarkFlagRequired("validation-command")
	_ = cmd.MarkFlagRequired("max-tasks")
	cmd.Flags().StringVar(&workDir, "work-dir", ".", "the working directory for this run")
	cmd.Flags().StringVar(&sprintPlanningModel, "sprint-planning", defaults[gimble.WorkflowRole("sprint-planning")], "the model for role sprint-planning, as model or model:effort")
	if defaults[gimble.WorkflowRole("sprint-planning")] == "" {
		_ = cmd.MarkFlagRequired("sprint-planning")
	}
	cmd.Flags().StringVar(&architecturalCritiqueModel, "architectural-critique", defaults[gimble.WorkflowRole("architectural-critique")], "the model for role architectural-critique, as model or model:effort")
	if defaults[gimble.WorkflowRole("architectural-critique")] == "" {
		_ = cmd.MarkFlagRequired("architectural-critique")
	}
	cmd.Flags().StringVar(&codingModel, "coding", defaults[gimble.WorkflowRole("coding")], "the model for role coding, as model or model:effort")
	if defaults[gimble.WorkflowRole("coding")] == "" {
		_ = cmd.MarkFlagRequired("coding")
	}
	cmd.Flags().StringVar(&qaOrchestrationModel, "qa-orchestration", defaults[gimble.WorkflowRole("qa-orchestration")], "the model for role qa-orchestration, as model or model:effort")
	if defaults[gimble.WorkflowRole("qa-orchestration")] == "" {
		_ = cmd.MarkFlagRequired("qa-orchestration")
	}
	cmd.Flags().IntVar(&port, "port", 8080, "loopback TCP port for the web application")
	cmd.Flags().StringVar(&uds, "uds", "", "Unix-domain socket for the web application instead of TCP")
	cmd.Flags().BoolVar(&noWeb, "no-web", false, "run without the web application")
	cmd.RunE = func(cmd *cobra.Command, _ []string) error {
		workDir, err := filepath.Abs(workDir)
		if err != nil {
			return err
		}
		models, err := binding.Roles(map[gimble.WorkflowRole]string{gimble.WorkflowRole("sprint-planning"): sprintPlanningModel, gimble.WorkflowRole("architectural-critique"): architecturalCritiqueModel, gimble.WorkflowRole("coding"): codingModel, gimble.WorkflowRole("qa-orchestration"): qaOrchestrationModel})
		if err != nil {
			return err
		}
		ctx, stop := signal.NotifyContext(cmd.Context(), os.Interrupt)
		defer stop()
		var options []web.Option
		switch {
		case noWeb:
			options = append(options, web.WithNoWeb())
		case uds != "":
			options = append(options, web.WithUDS(uds))
		default:
			options = append(options, web.WithPort(port))
		}
		runtime, err := web.NewRuntime(ctx, filepath.Join(workDir, ".gimble"), options...)
		if err != nil {
			return err
		}
		env := gimble.Env{WorkDir: workDir}
		return runtime.Run(ctx, "implement", models, func(ctx context.Context) error { return Implement(ctx, env, params) })
	}
	return cmd
}
