// Code generated by gimble graph. DO NOT EDIT.

package execute

import (
	"context"
	"encoding/json"

	"github.com/tylergannon/gimble"
	"github.com/tylergannon/gimble/workflow"
)

// The workflow registers itself when it is built: gimble lists it and runs it.
func init() {
	gimble.RegisterWorkflow(gimble.Registration{
		Name:    "execute",
		Summary: "Execute builds sprint in.Sprint.",
		Input:   (Input{}).Schema(),
		Graph:   Graph,
		Run: func(ctx context.Context, input json.RawMessage) error {
			var in Input
			if err := in.ValidateJSON(input); err != nil {
				return err
			}
			if err := json.Unmarshal(input, &in); err != nil {
				return err
			}
			return Execute(ctx, in)
		},
	})
}

// Graph is the shape of this workflow, read from the source of Execute.
var Graph = workflow.Graph{
	Name:   "execute",
	Source: workflow.Source{File: "internal/workflows/execute/execute.go", Line: 35},
	Body: []workflow.Operation{
		workflow.Set{Source: workflow.Source{File: "internal/workflows/execute/execute.go", Line: 40}, Key: "sprint document"},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/execute/execute.go", Line: 41}, Key: "blockers file"},
		workflow.Session{Source: workflow.Source{File: "internal/workflows/execute/execute.go", Line: 43}, Name: "worker", From: ""},
		workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/execute/execute.go", Line: 44}, Session: "worker", Role: "worker", Prompt: "You are executing a sprint plan. Read the sprint document named below and work through every task in its Implementation Plan, phase by phase, in order: implement the change, verify it works with the tests and checks the repository has, and move on to the next task. Follow the project's conventions in AGENTS.md, CLAUDE.md, or equivalent. Do not skip tasks, and do not reorder phases unless a dependency requires it. If you hit a blocker you cannot resolve, write what is blocked and why to the blockers file named below and continue with the next unblocked task. If the sprint is linked to a chapter, read the chapter document too and keep the work aligned with its vector and non-goals, preserving the link in the sprint document. If the sprint document has a Pyramid Index, keep it accurate. Answer with what you completed and what you did not."},
		workflow.Command{Source: workflow.Source{File: "internal/workflows/execute/execute.go", Line: 49}, Name: "tests"},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/execute/execute.go", Line: 57}, Key: "tests"},
		workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/execute/execute.go", Line: 58}, Session: "worker", Role: "worker", Prompt: "The repository's tests ran as recorded below. Read the blockers file named below if it exists. Report the tasks completed, the blockers, and the test results."},
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/execute/execute.go", Line: 63}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/execute/execute.go", Line: 63}, Case: "code != 0", Exits: true, Body: []workflow.Operation{}},
		}},
	},
}
