// Code generated by polytype. DO NOT EDIT.

/**
 * Conversation is the durable metadata and visible transcript for one chat.
 */
export type Conversation = {
  id: string;
  title: string;
  provider: string;
  model: string;
  branch: string;
  worktree: string;
  live: boolean;
  status: string;
  error: string;
  created: number;
  updated: number;
  messages: Array<Message>;
};

/**
 * Message is one visible turn in a conversation transcript.
 */
export type Message = {
  role: string;
  text: string;
  created: number;
};
