//go:build !jsonschema

// Code generated by internal/generate. DO NOT EDIT.

package piport

import (
	"github.com/tylergannon/gimbal"
	"github.com/tylergannon/gimbal/workflow"
)

func init() { gimbal.RegisterGraph(Graph) }

// Graph is the shape of this workflow, read from the source of Port.
var Graph = workflow.Graph{
	Name:     "pi-port",
	Source:   workflow.Source{File: "internal/workflows/piport/piport.go", Line: 63},
	Services: []workflow.Service{},
	Body: []workflow.Operation{
		workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 68}, Name: "initial-status"},
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 72}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 72}, Case: "exit != 0 || strings.TrimSpace(status) != \"\"", Exits: true, Body: []workflow.Operation{}},
		}},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 79}, Key: "assignments file"},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 80}, Key: "worker worktrees"},
		workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 81}, Name: "wave", Services: []workflow.Service{}, Body: []workflow.Operation{
			workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 82}, Name: "baseline"},
			workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 86}, Branches: []workflow.Branch{
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 86}, Case: "exit != 0", Exits: true, Body: []workflow.Operation{}},
			}},
			workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 91}, Name: "prepare", Services: []workflow.Service{}, Body: []workflow.Operation{
				workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 94}, Name: "worktree"},
				workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 98}, Branches: []workflow.Branch{
					{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 98}, Case: "exit != 0", Exits: true, Body: []workflow.Operation{}},
				}},
			}},
			workflow.Group{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 103}, Name: "modules", Children: []workflow.GroupChild{
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 104}, Name: "model", Services: []workflow.Service{}, Body: []workflow.Operation{
					workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 106}, Branches: []workflow.Branch{
						{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 106}, Case: "task == nil", Exits: true, Body: []workflow.Operation{}},
					}},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 109}, Key: "assignment file"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 110}, Key: "allowed paths"},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 111}, Name: "pi-port-coding", From: ""},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 112}, Name: "pi-port-scope", From: ""},
					workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 114}, Name: "attempt", Services: []workflow.Service{}, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 115}, Key: "previous check"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 116}, Session: "pi-port-coding", Role: "pi-port-coding", Prompt: "Read the local assignment file named in context. Port its TypeScript modules to the assigned Go package, using the upstream source and relevant unit tests. Run and fix ordinary package tests; preserve behavior without redesign or unrelated features. You own only the listed paths in this isolated worktree. Do not edit other packages, shared contracts, this workflow or the handoff, and do not commit or push. If a shared contract blocks you, report it instead of inventing a competing type. Report what changed and the tests you ran.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 116}, Session: "pi-port-scope", Role: "pi-port-scope", Instruction: "Steer only against expanding this assignment, redesigning the upstream, or building elaborate test machinery. Preserve the requested behavior and relevant upstream unit tests. Do not edit files."},
						}},
						workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 119}, Name: "package-test"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 124}, Key: "package test"},
						workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 125}, Branches: []workflow.Branch{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 125}, Case: "exit == 0", Exits: true, Body: []workflow.Operation{}},
						}},
					}},
				}},
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 132}, Name: "wire", Services: []workflow.Service{}, Body: []workflow.Operation{
					workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 134}, Branches: []workflow.Branch{
						{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 134}, Case: "task == nil", Exits: true, Body: []workflow.Operation{}},
					}},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 137}, Key: "assignment file"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 138}, Key: "allowed paths"},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 139}, Name: "pi-port-coding", From: ""},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 140}, Name: "pi-port-scope", From: ""},
					workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 142}, Name: "attempt", Services: []workflow.Service{}, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 143}, Key: "previous check"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 144}, Session: "pi-port-coding", Role: "pi-port-coding", Prompt: "Read the local assignment file named in context. Port its TypeScript modules to the assigned Go package, using the upstream source and relevant unit tests. Run and fix ordinary package tests; preserve behavior without redesign or unrelated features. You own only the listed paths in this isolated worktree. Do not edit other packages, shared contracts, this workflow or the handoff, and do not commit or push. If a shared contract blocks you, report it instead of inventing a competing type. Report what changed and the tests you ran.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 144}, Session: "pi-port-scope", Role: "pi-port-scope", Instruction: "Steer only against expanding this assignment, redesigning the upstream, or building elaborate test machinery. Preserve the requested behavior and relevant upstream unit tests. Do not edit files."},
						}},
						workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 147}, Name: "package-test"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 152}, Key: "package test"},
						workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 153}, Branches: []workflow.Branch{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 153}, Case: "exit == 0", Exits: true, Body: []workflow.Operation{}},
						}},
					}},
				}},
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 160}, Name: "openai", Services: []workflow.Service{}, Body: []workflow.Operation{
					workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 162}, Branches: []workflow.Branch{
						{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 162}, Case: "task == nil", Exits: true, Body: []workflow.Operation{}},
					}},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 165}, Key: "assignment file"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 166}, Key: "allowed paths"},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 167}, Name: "pi-port-coding", From: ""},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 168}, Name: "pi-port-scope", From: ""},
					workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 170}, Name: "attempt", Services: []workflow.Service{}, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 171}, Key: "previous check"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 172}, Session: "pi-port-coding", Role: "pi-port-coding", Prompt: "Read the local assignment file named in context. Port its TypeScript modules to the assigned Go package, using the upstream source and relevant unit tests. Run and fix ordinary package tests; preserve behavior without redesign or unrelated features. You own only the listed paths in this isolated worktree. Do not edit other packages, shared contracts, this workflow or the handoff, and do not commit or push. If a shared contract blocks you, report it instead of inventing a competing type. Report what changed and the tests you ran.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 172}, Session: "pi-port-scope", Role: "pi-port-scope", Instruction: "Steer only against expanding this assignment, redesigning the upstream, or building elaborate test machinery. Preserve the requested behavior and relevant upstream unit tests. Do not edit files."},
						}},
						workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 175}, Name: "package-test"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 180}, Key: "package test"},
						workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 181}, Branches: []workflow.Branch{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 181}, Case: "exit == 0", Exits: true, Body: []workflow.Operation{}},
						}},
					}},
				}},
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 188}, Name: "config", Services: []workflow.Service{}, Body: []workflow.Operation{
					workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 190}, Branches: []workflow.Branch{
						{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 190}, Case: "task == nil", Exits: true, Body: []workflow.Operation{}},
					}},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 193}, Key: "assignment file"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 194}, Key: "allowed paths"},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 195}, Name: "pi-port-coding", From: ""},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 196}, Name: "pi-port-scope", From: ""},
					workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 198}, Name: "attempt", Services: []workflow.Service{}, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 199}, Key: "previous check"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 200}, Session: "pi-port-coding", Role: "pi-port-coding", Prompt: "Read the local assignment file named in context. Port its TypeScript modules to the assigned Go package, using the upstream source and relevant unit tests. Run and fix ordinary package tests; preserve behavior without redesign or unrelated features. You own only the listed paths in this isolated worktree. Do not edit other packages, shared contracts, this workflow or the handoff, and do not commit or push. If a shared contract blocks you, report it instead of inventing a competing type. Report what changed and the tests you ran.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 200}, Session: "pi-port-scope", Role: "pi-port-scope", Instruction: "Steer only against expanding this assignment, redesigning the upstream, or building elaborate test machinery. Preserve the requested behavior and relevant upstream unit tests. Do not edit files."},
						}},
						workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 203}, Name: "package-test"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 208}, Key: "package test"},
						workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 209}, Branches: []workflow.Branch{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 209}, Case: "exit == 0", Exits: true, Body: []workflow.Operation{}},
						}},
					}},
				}},
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 216}, Name: "files", Services: []workflow.Service{}, Body: []workflow.Operation{
					workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 218}, Branches: []workflow.Branch{
						{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 218}, Case: "task == nil", Exits: true, Body: []workflow.Operation{}},
					}},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 221}, Key: "assignment file"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 222}, Key: "allowed paths"},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 223}, Name: "pi-port-coding", From: ""},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 224}, Name: "pi-port-scope", From: ""},
					workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 226}, Name: "attempt", Services: []workflow.Service{}, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 227}, Key: "previous check"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 228}, Session: "pi-port-coding", Role: "pi-port-coding", Prompt: "Read the local assignment file named in context. Port its TypeScript modules to the assigned Go package, using the upstream source and relevant unit tests. Run and fix ordinary package tests; preserve behavior without redesign or unrelated features. You own only the listed paths in this isolated worktree. Do not edit other packages, shared contracts, this workflow or the handoff, and do not commit or push. If a shared contract blocks you, report it instead of inventing a competing type. Report what changed and the tests you ran.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 228}, Session: "pi-port-scope", Role: "pi-port-scope", Instruction: "Steer only against expanding this assignment, redesigning the upstream, or building elaborate test machinery. Preserve the requested behavior and relevant upstream unit tests. Do not edit files."},
						}},
						workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 231}, Name: "package-test"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 236}, Key: "package test"},
						workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 237}, Branches: []workflow.Branch{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 237}, Case: "exit == 0", Exits: true, Body: []workflow.Operation{}},
						}},
					}},
				}},
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 244}, Name: "readtools", Services: []workflow.Service{}, Body: []workflow.Operation{
					workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 246}, Branches: []workflow.Branch{
						{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 246}, Case: "task == nil", Exits: true, Body: []workflow.Operation{}},
					}},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 249}, Key: "assignment file"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 250}, Key: "allowed paths"},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 251}, Name: "pi-port-coding", From: ""},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 252}, Name: "pi-port-scope", From: ""},
					workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 254}, Name: "attempt", Services: []workflow.Service{}, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 255}, Key: "previous check"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 256}, Session: "pi-port-coding", Role: "pi-port-coding", Prompt: "Read the local assignment file named in context. Port its TypeScript modules to the assigned Go package, using the upstream source and relevant unit tests. Run and fix ordinary package tests; preserve behavior without redesign or unrelated features. You own only the listed paths in this isolated worktree. Do not edit other packages, shared contracts, this workflow or the handoff, and do not commit or push. If a shared contract blocks you, report it instead of inventing a competing type. Report what changed and the tests you ran.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 256}, Session: "pi-port-scope", Role: "pi-port-scope", Instruction: "Steer only against expanding this assignment, redesigning the upstream, or building elaborate test machinery. Preserve the requested behavior and relevant upstream unit tests. Do not edit files."},
						}},
						workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 259}, Name: "package-test"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 264}, Key: "package test"},
						workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 265}, Branches: []workflow.Branch{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 265}, Case: "exit == 0", Exits: true, Body: []workflow.Operation{}},
						}},
					}},
				}},
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 272}, Name: "edittools", Services: []workflow.Service{}, Body: []workflow.Operation{
					workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 274}, Branches: []workflow.Branch{
						{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 274}, Case: "task == nil", Exits: true, Body: []workflow.Operation{}},
					}},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 277}, Key: "assignment file"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 278}, Key: "allowed paths"},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 279}, Name: "pi-port-coding", From: ""},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 280}, Name: "pi-port-scope", From: ""},
					workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 282}, Name: "attempt", Services: []workflow.Service{}, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 283}, Key: "previous check"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 284}, Session: "pi-port-coding", Role: "pi-port-coding", Prompt: "Read the local assignment file named in context. Port its TypeScript modules to the assigned Go package, using the upstream source and relevant unit tests. Run and fix ordinary package tests; preserve behavior without redesign or unrelated features. You own only the listed paths in this isolated worktree. Do not edit other packages, shared contracts, this workflow or the handoff, and do not commit or push. If a shared contract blocks you, report it instead of inventing a competing type. Report what changed and the tests you ran.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 284}, Session: "pi-port-scope", Role: "pi-port-scope", Instruction: "Steer only against expanding this assignment, redesigning the upstream, or building elaborate test machinery. Preserve the requested behavior and relevant upstream unit tests. Do not edit files."},
						}},
						workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 287}, Name: "package-test"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 292}, Key: "package test"},
						workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 293}, Branches: []workflow.Branch{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 293}, Case: "exit == 0", Exits: true, Body: []workflow.Operation{}},
						}},
					}},
				}},
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 300}, Name: "shell", Services: []workflow.Service{}, Body: []workflow.Operation{
					workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 302}, Branches: []workflow.Branch{
						{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 302}, Case: "task == nil", Exits: true, Body: []workflow.Operation{}},
					}},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 305}, Key: "assignment file"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 306}, Key: "allowed paths"},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 307}, Name: "pi-port-coding", From: ""},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 308}, Name: "pi-port-scope", From: ""},
					workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 310}, Name: "attempt", Services: []workflow.Service{}, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 311}, Key: "previous check"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 312}, Session: "pi-port-coding", Role: "pi-port-coding", Prompt: "Read the local assignment file named in context. Port its TypeScript modules to the assigned Go package, using the upstream source and relevant unit tests. Run and fix ordinary package tests; preserve behavior without redesign or unrelated features. You own only the listed paths in this isolated worktree. Do not edit other packages, shared contracts, this workflow or the handoff, and do not commit or push. If a shared contract blocks you, report it instead of inventing a competing type. Report what changed and the tests you ran.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 312}, Session: "pi-port-scope", Role: "pi-port-scope", Instruction: "Steer only against expanding this assignment, redesigning the upstream, or building elaborate test machinery. Preserve the requested behavior and relevant upstream unit tests. Do not edit files."},
						}},
						workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 315}, Name: "package-test"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 320}, Key: "package test"},
						workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 321}, Branches: []workflow.Branch{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 321}, Case: "exit == 0", Exits: true, Body: []workflow.Operation{}},
						}},
					}},
				}},
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 328}, Name: "resources", Services: []workflow.Service{}, Body: []workflow.Operation{
					workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 330}, Branches: []workflow.Branch{
						{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 330}, Case: "task == nil", Exits: true, Body: []workflow.Operation{}},
					}},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 333}, Key: "assignment file"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 334}, Key: "allowed paths"},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 335}, Name: "pi-port-coding", From: ""},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 336}, Name: "pi-port-scope", From: ""},
					workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 338}, Name: "attempt", Services: []workflow.Service{}, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 339}, Key: "previous check"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 340}, Session: "pi-port-coding", Role: "pi-port-coding", Prompt: "Read the local assignment file named in context. Port its TypeScript modules to the assigned Go package, using the upstream source and relevant unit tests. Run and fix ordinary package tests; preserve behavior without redesign or unrelated features. You own only the listed paths in this isolated worktree. Do not edit other packages, shared contracts, this workflow or the handoff, and do not commit or push. If a shared contract blocks you, report it instead of inventing a competing type. Report what changed and the tests you ran.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 340}, Session: "pi-port-scope", Role: "pi-port-scope", Instruction: "Steer only against expanding this assignment, redesigning the upstream, or building elaborate test machinery. Preserve the requested behavior and relevant upstream unit tests. Do not edit files."},
						}},
						workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 343}, Name: "package-test"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 348}, Key: "package test"},
						workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 349}, Branches: []workflow.Branch{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 349}, Case: "exit == 0", Exits: true, Body: []workflow.Operation{}},
						}},
					}},
				}},
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 356}, Name: "history", Services: []workflow.Service{}, Body: []workflow.Operation{
					workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 358}, Branches: []workflow.Branch{
						{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 358}, Case: "task == nil", Exits: true, Body: []workflow.Operation{}},
					}},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 361}, Key: "assignment file"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 362}, Key: "allowed paths"},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 363}, Name: "pi-port-coding", From: ""},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 364}, Name: "pi-port-scope", From: ""},
					workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 366}, Name: "attempt", Services: []workflow.Service{}, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 367}, Key: "previous check"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 368}, Session: "pi-port-coding", Role: "pi-port-coding", Prompt: "Read the local assignment file named in context. Port its TypeScript modules to the assigned Go package, using the upstream source and relevant unit tests. Run and fix ordinary package tests; preserve behavior without redesign or unrelated features. You own only the listed paths in this isolated worktree. Do not edit other packages, shared contracts, this workflow or the handoff, and do not commit or push. If a shared contract blocks you, report it instead of inventing a competing type. Report what changed and the tests you ran.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 368}, Session: "pi-port-scope", Role: "pi-port-scope", Instruction: "Steer only against expanding this assignment, redesigning the upstream, or building elaborate test machinery. Preserve the requested behavior and relevant upstream unit tests. Do not edit files."},
						}},
						workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 371}, Name: "package-test"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 376}, Key: "package test"},
						workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 377}, Branches: []workflow.Branch{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 377}, Case: "exit == 0", Exits: true, Body: []workflow.Operation{}},
						}},
					}},
				}},
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 384}, Name: "compact", Services: []workflow.Service{}, Body: []workflow.Operation{
					workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 386}, Branches: []workflow.Branch{
						{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 386}, Case: "task == nil", Exits: true, Body: []workflow.Operation{}},
					}},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 389}, Key: "assignment file"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 390}, Key: "allowed paths"},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 391}, Name: "pi-port-coding", From: ""},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 392}, Name: "pi-port-scope", From: ""},
					workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 394}, Name: "attempt", Services: []workflow.Service{}, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 395}, Key: "previous check"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 396}, Session: "pi-port-coding", Role: "pi-port-coding", Prompt: "Read the local assignment file named in context. Port its TypeScript modules to the assigned Go package, using the upstream source and relevant unit tests. Run and fix ordinary package tests; preserve behavior without redesign or unrelated features. You own only the listed paths in this isolated worktree. Do not edit other packages, shared contracts, this workflow or the handoff, and do not commit or push. If a shared contract blocks you, report it instead of inventing a competing type. Report what changed and the tests you ran.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 396}, Session: "pi-port-scope", Role: "pi-port-scope", Instruction: "Steer only against expanding this assignment, redesigning the upstream, or building elaborate test machinery. Preserve the requested behavior and relevant upstream unit tests. Do not edit files."},
						}},
						workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 399}, Name: "package-test"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 404}, Key: "package test"},
						workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 405}, Branches: []workflow.Branch{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 405}, Case: "exit == 0", Exits: true, Body: []workflow.Operation{}},
						}},
					}},
				}},
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 412}, Name: "agent", Services: []workflow.Service{}, Body: []workflow.Operation{
					workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 414}, Branches: []workflow.Branch{
						{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 414}, Case: "task == nil", Exits: true, Body: []workflow.Operation{}},
					}},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 417}, Key: "assignment file"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 418}, Key: "allowed paths"},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 419}, Name: "pi-port-coding", From: ""},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 420}, Name: "pi-port-scope", From: ""},
					workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 422}, Name: "attempt", Services: []workflow.Service{}, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 423}, Key: "previous check"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 424}, Session: "pi-port-coding", Role: "pi-port-coding", Prompt: "Read the local assignment file named in context. Port its TypeScript modules to the assigned Go package, using the upstream source and relevant unit tests. Run and fix ordinary package tests; preserve behavior without redesign or unrelated features. You own only the listed paths in this isolated worktree. Do not edit other packages, shared contracts, this workflow or the handoff, and do not commit or push. If a shared contract blocks you, report it instead of inventing a competing type. Report what changed and the tests you ran.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 424}, Session: "pi-port-scope", Role: "pi-port-scope", Instruction: "Steer only against expanding this assignment, redesigning the upstream, or building elaborate test machinery. Preserve the requested behavior and relevant upstream unit tests. Do not edit files."},
						}},
						workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 427}, Name: "package-test"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 432}, Key: "package test"},
						workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 433}, Branches: []workflow.Branch{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 433}, Case: "exit == 0", Exits: true, Body: []workflow.Operation{}},
						}},
					}},
				}},
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 440}, Name: "session", Services: []workflow.Service{}, Body: []workflow.Operation{
					workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 442}, Branches: []workflow.Branch{
						{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 442}, Case: "task == nil", Exits: true, Body: []workflow.Operation{}},
					}},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 445}, Key: "assignment file"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 446}, Key: "allowed paths"},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 447}, Name: "pi-port-coding", From: ""},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 448}, Name: "pi-port-scope", From: ""},
					workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 450}, Name: "attempt", Services: []workflow.Service{}, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 451}, Key: "previous check"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 452}, Session: "pi-port-coding", Role: "pi-port-coding", Prompt: "Read the local assignment file named in context. Port its TypeScript modules to the assigned Go package, using the upstream source and relevant unit tests. Run and fix ordinary package tests; preserve behavior without redesign or unrelated features. You own only the listed paths in this isolated worktree. Do not edit other packages, shared contracts, this workflow or the handoff, and do not commit or push. If a shared contract blocks you, report it instead of inventing a competing type. Report what changed and the tests you ran.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 452}, Session: "pi-port-scope", Role: "pi-port-scope", Instruction: "Steer only against expanding this assignment, redesigning the upstream, or building elaborate test machinery. Preserve the requested behavior and relevant upstream unit tests. Do not edit files."},
						}},
						workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 455}, Name: "package-test"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 460}, Key: "package test"},
						workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 461}, Branches: []workflow.Branch{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 461}, Case: "exit == 0", Exits: true, Body: []workflow.Operation{}},
						}},
					}},
				}},
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 468}, Name: "adapter", Services: []workflow.Service{}, Body: []workflow.Operation{
					workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 470}, Branches: []workflow.Branch{
						{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 470}, Case: "task == nil", Exits: true, Body: []workflow.Operation{}},
					}},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 473}, Key: "assignment file"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 474}, Key: "allowed paths"},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 475}, Name: "pi-port-coding", From: ""},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 476}, Name: "pi-port-scope", From: ""},
					workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 478}, Name: "attempt", Services: []workflow.Service{}, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 479}, Key: "previous check"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 480}, Session: "pi-port-coding", Role: "pi-port-coding", Prompt: "Read the local assignment file named in context. Port its TypeScript modules to the assigned Go package, using the upstream source and relevant unit tests. Run and fix ordinary package tests; preserve behavior without redesign or unrelated features. You own only the listed paths in this isolated worktree. Do not edit other packages, shared contracts, this workflow or the handoff, and do not commit or push. If a shared contract blocks you, report it instead of inventing a competing type. Report what changed and the tests you ran.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 480}, Session: "pi-port-scope", Role: "pi-port-scope", Instruction: "Steer only against expanding this assignment, redesigning the upstream, or building elaborate test machinery. Preserve the requested behavior and relevant upstream unit tests. Do not edit files."},
						}},
						workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 483}, Name: "package-test"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 488}, Key: "package test"},
						workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 489}, Branches: []workflow.Branch{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 489}, Case: "exit == 0", Exits: true, Body: []workflow.Operation{}},
						}},
					}},
				}},
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 496}, Name: "integration", Services: []workflow.Service{}, Body: []workflow.Operation{
					workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 498}, Branches: []workflow.Branch{
						{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 498}, Case: "task == nil", Exits: true, Body: []workflow.Operation{}},
					}},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 501}, Key: "assignment file"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 502}, Key: "allowed paths"},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 503}, Name: "pi-port-coding", From: ""},
					workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 504}, Name: "pi-port-scope", From: ""},
					workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 506}, Name: "attempt", Services: []workflow.Service{}, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 507}, Key: "previous check"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 508}, Session: "pi-port-coding", Role: "pi-port-coding", Prompt: "Read the local assignment file named in context. Port its TypeScript modules to the assigned Go package, using the upstream source and relevant unit tests. Run and fix ordinary package tests; preserve behavior without redesign or unrelated features. You own only the listed paths in this isolated worktree. Do not edit other packages, shared contracts, this workflow or the handoff, and do not commit or push. If a shared contract blocks you, report it instead of inventing a competing type. Report what changed and the tests you ran.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 508}, Session: "pi-port-scope", Role: "pi-port-scope", Instruction: "Steer only against expanding this assignment, redesigning the upstream, or building elaborate test machinery. Preserve the requested behavior and relevant upstream unit tests. Do not edit files."},
						}},
						workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 511}, Name: "package-test"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 516}, Key: "package test"},
						workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 517}, Branches: []workflow.Branch{
							{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 517}, Case: "exit == 0", Exits: true, Body: []workflow.Operation{}},
						}},
					}},
				}},
			}},
			workflow.Iterate{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 535}, Name: "integrate", Services: []workflow.Service{}, Body: []workflow.Operation{
				workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 536}, Name: "candidate-head"},
				workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 540}, Branches: []workflow.Branch{
					{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 540}, Case: "exit != 0 || strings.TrimSpace(head) != baseline", Exits: true, Body: []workflow.Operation{}},
				}},
				workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 543}, Name: "changed-paths"},
				workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 547}, Branches: []workflow.Branch{
					{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 547}, Case: "exit != 0", Exits: true, Body: []workflow.Operation{}},
				}},
				workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 550}, Name: "new-paths"},
				workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 554}, Branches: []workflow.Branch{
					{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 554}, Case: "exit != 0", Exits: true, Body: []workflow.Operation{}},
				}},
				workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 560}, Name: "stage"},
				workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 564}, Branches: []workflow.Branch{
					{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 564}, Case: "exit != 0", Exits: true, Body: []workflow.Operation{}},
				}},
				workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 567}, Name: "commit"},
				workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 571}, Branches: []workflow.Branch{
					{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 571}, Case: "exit != 0", Exits: true, Body: []workflow.Operation{}},
				}},
				workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 574}, Name: "candidate-commit"},
				workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 578}, Branches: []workflow.Branch{
					{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 578}, Case: "exit != 0", Exits: true, Body: []workflow.Operation{}},
				}},
				workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 581}, Name: "cherry-pick"},
				workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 585}, Branches: []workflow.Branch{
					{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 585}, Case: "exit != 0", Exits: true, Body: []workflow.Operation{}},
				}},
				workflow.Command{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 588}, Name: "integrated-test"},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 589}, Key: "integrated test"},
				workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 593}, Branches: []workflow.Branch{
					{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 593}, Case: "exit != 0", Exits: true, Body: []workflow.Operation{}},
				}},
			}},
			workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 601}, Key: "wave assignments"},
			workflow.Session{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 602}, Name: "pi-port-review", From: ""},
			workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 603}, Session: "pi-port-review", Role: "pi-port-review", Prompt: "Read the wave assignments at their local paths, inspect the integrated Go code against the assigned TypeScript and tests, and run relevant checks. Make no edits. Report only concrete missing behavior or incorrect translations that block these assignments. Ordinary relevant unit tests are sufficient here; do not demand new frameworks, exhaustive test matrices, or work assigned to later waves. Complete is true when these assignments are implemented with no substantial gap."},
			workflow.Set{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 607}, Key: "assessment"},
			workflow.Condition{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 608}, Branches: []workflow.Branch{
				{Source: workflow.Source{File: "internal/workflows/piport/piport.go", Line: 608}, Case: "!assessment.Complete", Exits: true, Body: []workflow.Operation{}},
			}},
		}},
	},
}
