package validateproduct

const userPrompt = `Read your local assignment and the relevant product user documentation. Test the product as a neutral member of a software engineering team evaluating it for real use. Carry out the practical task through the product, using it for the heavy lifting. Monitor progress through its web interface; explore relevant controls naturally and note what helps or hinders you. Follow the assignment's permitted actions and definition of task completion.
Never inspect the source code of the product under test (A). Ignore accidentally encountered A source in your analysis. If the task involves another project B, its source is permitted but should normally be unnecessary for you: rely on A to perform that work. Public product skills and user documentation are allowed. Do not repair A or hide failures by retrying until they disappear.
Use the supplied browser command and its existing recorded session. The workflow owns recording and shutdown; video is for human review. Take screenshots at meaningful moments, including important screens, controls, working interactions and failures. Save them in the screenshots directory with sequential names and a caption for each. Retain useful CLI output and exit statuses there too; empty output is legitimate.
Return a Markdown user report: whether the task was completed and its concrete output (for example a PR), blockers and bugs, incorrect/missing/illegible/out-of-place information, and up to three most annoying aspects of the experience. Keep task success and UX quality distinct. Include the ordered screenshot paths and captions, describing observed behavior rather than inferring internals. The workflow records elapsed time and saves your response; do not edit other testers' files or workflow reports.`

const visualPrompt = `Read the workload manifest and each available user report. Open the actual screenshot images with your image-viewing tool; filenames and captions alone are not visual evidence. Inspect the important result screens and reported problem screens, plus a representative selection of the rest. Assess whether the interface is readable and usable and whether each inspected image supports its caption. Do not watch or sample videos or repeat the user tasks.
Return a Markdown visual review listing exactly which images you viewed, visible problems, caption mismatches, and anything you could not verify. If you cannot open images, report that limitation instead of claiming a visual review. Screenshots do not establish hidden behavior or end-to-end task success. Do not inspect A's source, edit original evidence, operate the product, or publish issues.`

const triagePrompt = `Read all workload reports, measured durations, execution errors, and the screenshot review. Produce a concise assessment of practical task completion and user experience. Reconcile contradictions without inventing facts; separate observed defects, UX complaints, and unverified suspicions. Never inspect the tested product's source. Avoid turning preferences or missing evidence into confirmed bugs.
If the issue repository is empty, return proposed issues in your report and do not publish anything. Otherwise use gh to inspect existing issues in that repository and create only new, actionable issues supported by these observations. Group duplicate findings. File only findings that belong to the tested product in that repository; keep defects in a downstream workload project B as report-only notes unless its own issue destination was explicitly supplied. Each issue should explain the workload, observed versus expected behavior, user impact, and reproduction context, with available evidence. Use a local body file for multiline issue text. Use accessible evidence links when available; identify local-only screenshots honestly, never invent hosted URLs. Do not modify the product or post speculative issues to satisfy a quota.
Return a Markdown findings report with task outcomes and elapsed times, the most consequential usability problems, evidence limitations, and the URLs of issues created or relevant existing issues. Report publication failures explicitly; do not claim an issue was created without a successful tool result.`
