package validateproduct

const userPrompt = `Read your local assignment and the relevant product user documentation. Test the product as a neutral member of a software engineering team evaluating it for real use. Carry out the practical task through the product, using it for the heavy lifting. Monitor progress through its web interface; explore relevant controls naturally and note what helps or hinders you. Pay attention to the overall experience of using A, including what feels clear, helpful, confusing, or frustrating; completing work in B is only part of this evaluation. Follow the assignment's permitted actions and definition of task completion.
Never inspect the source code of the product under test (A). Ignore accidentally encountered A source in your analysis. If the task involves another project B, its source is permitted but should normally be unnecessary for you: rely on A to perform that work. Public product skills and user documentation are allowed. Do not repair A or hide failures by retrying until they disappear.
Use the supplied browser command and its existing recorded session. Navigate with the goto command, including when visiting project B; calling open again replaces the browser and loses the recording. The workflow owns recording and shutdown; video is for human review. Take screenshots at meaningful moments, including important screens, controls, working interactions and failures. Save them in the screenshots directory with sequential names and a caption for each. After saving a screenshot, open that exact image with your image-viewing tool before writing or citing its caption. Describe only what is visibly supported in that saved image, name visible errors, and use its exact path when referring to it. If relevant content is off-screen, capture it separately or narrow the claim. Retain useful CLI output and exit statuses there too; empty output is legitimate.
Return a Markdown user report: whether the task was completed and its concrete output (for example a PR), blockers and bugs, incorrect/missing/illegible/out-of-place information. Keep task success and the overall UI/UX experience distinct; a short follow-up will ask for your preferences. Include the ordered screenshot paths and captions, describing visible evidence rather than browser transcript, memory, or inference. The workflow records elapsed time and saves your response; do not edit other testers' files or workflow reports.`

const experiencePrompt = `Reflect on the product under test (A) you just used, using this session's interactions and screenshots. Give a brief overall assessment, then four ranked lists: your three favorite and three least favorite aspects of the user experience (UX), and your three favorite and three least favorite aspects of the user interface (UI).
For UX, consider how well the task flowed: discoverability, effort, progress feedback, control, and recovery. For UI, consider presentation: layout, navigation, controls, readability, and visual hierarchy. For each item, describe a concrete moment or screen, why it helped or hindered you, and cite an existing screenshot when relevant. Before citing one, reopen that exact image; use its exact path and claim only what it visibly supports. Distinguish a preference from a defect. If you observed fewer than three meaningful items in a category, say so instead of inventing or padding it.
Return only this UI/UX debrief in Markdown; it will be appended to your earlier task report. Discuss A, not the quality of downstream project B. Do not restart the task, perform more browser interactions, inspect source, or create issues.`

const visualPrompt = `Read the workload manifest and each available user report. Open the actual screenshot images with your image-viewing tool; filenames and captions alone are not visual evidence. Inspect the important result screens and reported problem screens, plus a representative selection of the rest. Assess whether the interface is readable and usable and whether each inspected image supports its caption. Do not watch or sample videos or repeat the user tasks.
Return a Markdown visual review listing exactly which images you viewed, visible problems, caption mismatches, and anything you could not verify. If you cannot open images, report that limitation instead of claiming a visual review. Screenshots do not establish hidden behavior or end-to-end task success. Do not inspect A's source, edit original evidence, operate the product, or publish issues.`

const triagePrompt = `Read all workload reports, measured durations, execution errors, and the screenshot review. Produce a concise assessment of practical task completion and the overall UI/UX experience. Include what users liked as well as the main frustrations from their debriefs; keep UX and UI feedback distinct. Reconcile contradictions without inventing facts; separate observed defects, UX complaints, and unverified suspicions. For visual claims and screenshot references, use the screenshot review's corrections instead of repeating a caption it found unsupported or a reference it found incorrect. Never inspect the tested product's source. Avoid turning preferences or missing evidence into confirmed bugs.
Use gh to inspect existing issues in the issue repository and create only new, actionable issues supported by these observations. Group duplicate findings. File only findings that belong to the tested product in that repository; keep defects in a downstream workload project B as report-only notes unless its own issue destination was explicitly supplied. For each new issue, explain the workload, observed versus expected behavior, user impact, and reproduction context. Reopen the exact supporting screenshots and check that each visible claim is supported. Upload those screenshots with gimble upload-artifact, verify the public URLs, and include the hosted images in the issue body. If a claim cannot be supported by the screenshots, qualify it or leave it in the local report. Use a local body file for multiline issue text. Do not publish an issue with local-only screenshot links or invent hosted URLs. If an upload or GitHub publication fails, report the failure clearly. Do not modify the product or post speculative issues to satisfy a quota.
Return a Markdown findings report with task outcomes and elapsed times, the most consequential usability problems, evidence limitations, and the URLs of issues created or relevant existing issues. Report publication failures explicitly; do not claim an issue was created without a successful tool result.`
