package validateproduct

const userPrompt = `Read your local assignment and the relevant product user documentation. Test the product as a neutral member of a software engineering team evaluating it for real use. Carry out the practical task through the product, using it for the heavy lifting. Monitor progress through its web interface; explore relevant controls naturally and note what helps or hinders you. Pay attention to the overall experience of using A, including what feels clear, helpful, confusing, or frustrating; completing work in B is only part of this evaluation. Follow the assignment's permitted actions and definition of task completion.
Never inspect the source code of the product under test (A). Ignore accidentally encountered A source in your analysis. If the task involves another project B, its source is permitted but should normally be unnecessary for you: rely on A to perform that work. Public product skills and user documentation are allowed. Do not repair A or hide failures by retrying until they disappear.
Use the supplied browser command and its existing recorded session. The workflow owns recording and shutdown; video is for human review. Take screenshots at meaningful moments, including important screens, controls, working interactions and failures. Save them in the screenshots directory with sequential names and a caption for each. After saving a screenshot, open that exact image with your image-viewing tool before writing or citing its caption. Describe only what is visibly supported in that saved image, name visible errors, and use its exact path when referring to it. If relevant content is off-screen, capture it separately or narrow the claim. Retain useful CLI output and exit statuses there too; empty output is legitimate.
Return a Markdown user report: whether the task was completed and its concrete output (for example a PR), blockers and bugs, incorrect/missing/illegible/out-of-place information. Keep task success and the overall UI/UX experience distinct; a short follow-up will ask for your preferences. Include the ordered screenshot paths and captions, describing visible evidence rather than browser transcript, memory, or inference. The workflow records elapsed time and saves your response; do not edit other testers' files or workflow reports.`

const experiencePrompt = `Reflect on the product under test (A) you just used, using this session's interactions and screenshots. Give a brief overall assessment, then four ranked lists: your three favorite and three least favorite aspects of the user experience (UX), and your three favorite and three least favorite aspects of the user interface (UI).
For UX, consider how well the task flowed: discoverability, effort, progress feedback, control, and recovery. For UI, consider presentation: layout, navigation, controls, readability, and visual hierarchy. For each item, describe a concrete moment or screen, why it helped or hindered you, and cite an existing screenshot when relevant. Before citing one, reopen that exact image; use its exact path and claim only what it visibly supports. Distinguish a preference from a defect. If you observed fewer than three meaningful items in a category, say so instead of inventing or padding it.
Return only this UI/UX debrief in Markdown; it will be appended to your earlier task report. Discuss A, not the quality of downstream project B. Do not restart the task, perform more browser interactions, inspect source, or create issues.`

const visualPrompt = `Read the current user report named in the context. Open every screenshot it cites with your image-viewing tool; filenames, captions, browser transcripts, and prior conversation are not visual evidence. Check only whether each image's visible contents support its caption, reference, and visible claim. Do not judge hidden behavior or end-to-end task success. Do not watch videos, repeat the task, inspect A's source, edit evidence, operate the product, or publish issues.
Set review_completed false if any cited image cannot be opened, list only the exact image paths you actually opened, and explain the evidence limitation. Otherwise set review_completed true. Set supported true only when every inspected image supports the report's visual claims. When unsupported, identify each mismatch precisely enough for the tester to correct an overstated caption or capture clearer evidence. A preference about the interface is not a mismatch.`

const correctionPrompt = `Read the current user report and the screenshot review named in the context. Correct the evidence, not the product and not the task outcome. For each mismatch, either narrow or correct the report and caption to what the saved image visibly shows, or use the existing browser session to capture a clearer screenshot when the original claim is still important. Open every new or retained cited image with your image-viewing tool. Do not repeat the workload, hide a failure, inspect A's source, or invent support.
Return the complete replacement Markdown user report, preserving accurate findings and using exact screenshot paths. Do not edit the workflow-owned report file yourself; the workflow will replace it with your response.`

const triagePrompt = `Read all workload reports, measured durations, execution errors, and their screenshot reviews. Produce a concise assessment of practical task completion and the overall UI/UX experience. Include what users liked as well as the main frustrations from their debriefs; keep UX and UI feedback distinct. Reconcile contradictions without inventing facts; separate observed defects, UX complaints, and unverified suspicions. For visual claims and screenshot references, use the final screenshot-review verdict instead of repeating a caption it found unsupported or a reference it found incorrect. Never inspect the tested product's source. Avoid turning preferences or missing evidence into confirmed bugs.
If the issue repository is empty, return proposed issues in your report and do not publish anything. Otherwise use gh to inspect existing issues in that repository and create only new, actionable issues supported by these observations. Group duplicate findings. File only findings that belong to the tested product in that repository; keep defects in a downstream workload project B as report-only notes unless its own issue destination was explicitly supplied. Each issue should explain the workload, observed versus expected behavior, user impact, and reproduction context, with available evidence. Use a local body file for multiline issue text. Use accessible evidence links when available; identify local-only screenshots honestly, never invent hosted URLs. Do not modify the product or post speculative issues to satisfy a quota.
Return a Markdown findings report with task outcomes and elapsed times, the most consequential usability problems, evidence limitations, and the URLs of issues created or relevant existing issues. Report publication failures explicitly; do not claim an issue was created without a successful tool result.`
