// Package workflow is the draft type contract for issue 201's workflow graph.
//
// This directory is the handoff copy of the future production package
// github.com/tylergannon/gimble/workflow. It compiles on its own inside the
// gimble module, and its test builds the graph of internal/workflows/sprint
// by hand and proves the JSON round trip of nested bodies and nested
// supervision. Nothing here is imported by production code yet.
//
// What the graph is for. Three things, and a field earns its place only by
// serving one of them or by lining a node up against the runtime's records:
// showing the shape of a workflow before it runs, showing how the context is
// built up, and showing what the prompts look like. A run is observed by the
// runtime, which records every scope, session, turn, and usage row as it
// happens. The page shows the graph and those records together, so anything
// the runtime already records is left out here: no adapter, model, or
// reasoning effort, which are parameters of a run and not knowable at build
// time; no results, timings, or costs.
//
// Shape decisions:
//
//   - The Go model is the natural recursive one. Ordered bodies are
//     []Operation and the bodied forms hold bodies. Nothing is flattened into
//     reference tables.
//   - Operation is a sealed interface whose variants are the same-package
//     structs declaring the unexported marker: Session, AgentCall, Command,
//     Set, Scope, Loop, Group, and Condition.
//   - Supervision is a separate, unordered hierarchy hanging off the call it
//     watches, not a step in an ordered body. A Supervisor holds the
//     supervisors of its own look turns.
//   - No node carries an identifier. The runtime names every scope, session,
//     and turn in one namespace of name.ordinal segments, so a node is
//     addressed by its path of names from the root: a runtime key with the
//     ordinal stripped from each segment. The graph's coder sits at
//     round/sprint/task/coder and a run's at round.2/sprint.1/task.3/coder.1.
//     That join is the whole identity scheme, and it needs no field here.
//
// Wire format. Each operation is one JSON object whose "kind" property is the
// snake_case Go type name and whose other properties are the struct's own
// fields. Nil slices encode as [], and a nil ordered body is an error rather
// than a null. The codecs are generated by gen.go; run go generate.
// jsonschema_gen.go is polytype's fixed output name and holds no schema.
//
// No JSON Schema. A schema is what lets a type be handed to a model as
// structured output, and a Graph is only ever serialized for the page. JSON
// Schema is also the one polytype output that cannot express this model:
// asked for a schema, generation reports a circular dependency, at Supervisor
// and again at Operation. Selecting Go JSON codecs alone through
// codegen.GoJSON avoids the schema entirely and generates the recursion
// without complaint.
package workflow

//go:generate go run gen.go
