//go:build !jsonschema

// Code generated by internal/generate. DO NOT EDIT.

package researchdocument

import (
	"context"
	"os"
	"os/signal"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/tylergannon/gimble"
	"github.com/tylergannon/gimble/internal/binding"
	"github.com/tylergannon/gimble/web"
	"github.com/tylergannon/gimble/workflow"
	"github.com/tylergannon/polytype"
)

func init() { gimble.RegisterGraph(Graph) }

// Graph is the shape of this workflow, read from the source of ResearchDocument.
var Graph = workflow.Graph{
	Name:     "research-document",
	Source:   workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 114},
	Services: []workflow.Service{},
	Body: []workflow.Operation{
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 116}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 116}, Case: "goal == \"\"", Exits: true, Body: []workflow.Operation{}},
		}},
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 119}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 119}, Case: "params.TokenBudget < 1", Exits: true, Body: []workflow.Operation{}},
		}},
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 126}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 126}, Case: "minSources < 1", Exits: true, Body: []workflow.Operation{}},
		}},
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 133}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 133}, Case: "maxRounds < 1", Exits: true, Body: []workflow.Operation{}},
		}},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 157}, Key: "document goal"},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 158}, Key: "document path"},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 159}, Key: "semantic index path"},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 160}, Key: "research directory"},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 161}, Key: "document token budget"},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 162}, Key: "token counter executable"},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 163}, Key: "minimum sources per topic"},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 164}, Key: "maximum editorial rounds"},
		workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 166}, Name: "research-planning", From: ""},
		workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 167}, Session: "research-planning", Role: "research-planning", Prompt: "Break the research needed for the document into exactly five groups of adjacent or related topics, one group for each parallel researcher. Every group must contain at least one topic. For each topic, give the specific questions its researcher must answer. Cover what the audience needs for the requested understanding; do not plan globally comprehensive research."},
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 171}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 171}, Case: "len(plan.Groups) != 5", Exits: true, Body: []workflow.Operation{}},
		}},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 174}, Key: "research plan"},
		workflow.Group{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 200}, Name: "research", Children: []workflow.GroupChild{
			{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 201}, Name: "agent1", Services: []workflow.Service{}, Body: []workflow.Operation{
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 202}, Key: "assigned topic group"},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 203}, Key: "topic directories"},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 204}, Key: "minimum sources per assigned topic"},
				workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 205}, Name: "research-indexing", From: ""},
				workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 206}, Name: "document-supervision", From: ""},
				workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 207}, Session: "research-indexing", Role: "research-indexing", Prompt: "Research every assigned topic for the final document. The topic directories align with the assigned topics in the same order. For each topic, download at least the required number of useful sources into that topic directory's sources subdirectory. Address every assigned question or explicitly mark it unresolved. Write INDEX.md in each topic directory with a concise goal-relevant synthesis, citations to the local source files, and links to longer clips in its clips subdirectory when summarizing would lose important detail. Return the files and questions you actually addressed. Stop once this definition of done is met for every assigned topic.", Supervisors: []workflow.Supervisor{
					{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 208}, Session: "document-supervision", Role: "document-supervision", Instruction: "The goal is the best possible document within its token budget, not a perfect corpus or index. Ensure the worker meets the stated research floor, preserves useful evidence locally, and makes the index sufficient for writing. Object to work beyond what would materially improve the document."},
				}},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 212}, Key: "research result"},
			}},
			{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 220}, Name: "agent2", Services: []workflow.Service{}, Body: []workflow.Operation{
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 221}, Key: "assigned topic group"},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 222}, Key: "topic directories"},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 223}, Key: "minimum sources per assigned topic"},
				workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 224}, Name: "research-indexing", From: ""},
				workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 225}, Name: "document-supervision", From: ""},
				workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 226}, Session: "research-indexing", Role: "research-indexing", Prompt: "Research every assigned topic for the final document. The topic directories align with the assigned topics in the same order. For each topic, download at least the required number of useful sources into that topic directory's sources subdirectory. Address every assigned question or explicitly mark it unresolved. Write INDEX.md in each topic directory with a concise goal-relevant synthesis, citations to the local source files, and links to longer clips in its clips subdirectory when summarizing would lose important detail. Return the files and questions you actually addressed. Stop once this definition of done is met for every assigned topic.", Supervisors: []workflow.Supervisor{
					{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 227}, Session: "document-supervision", Role: "document-supervision", Instruction: "The goal is the best possible document within its token budget, not a perfect corpus or index. Ensure the worker meets the stated research floor, preserves useful evidence locally, and makes the index sufficient for writing. Object to work beyond what would materially improve the document."},
				}},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 231}, Key: "research result"},
			}},
			{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 239}, Name: "agent3", Services: []workflow.Service{}, Body: []workflow.Operation{
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 240}, Key: "assigned topic group"},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 241}, Key: "topic directories"},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 242}, Key: "minimum sources per assigned topic"},
				workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 243}, Name: "research-indexing", From: ""},
				workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 244}, Name: "document-supervision", From: ""},
				workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 245}, Session: "research-indexing", Role: "research-indexing", Prompt: "Research every assigned topic for the final document. The topic directories align with the assigned topics in the same order. For each topic, download at least the required number of useful sources into that topic directory's sources subdirectory. Address every assigned question or explicitly mark it unresolved. Write INDEX.md in each topic directory with a concise goal-relevant synthesis, citations to the local source files, and links to longer clips in its clips subdirectory when summarizing would lose important detail. Return the files and questions you actually addressed. Stop once this definition of done is met for every assigned topic.", Supervisors: []workflow.Supervisor{
					{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 246}, Session: "document-supervision", Role: "document-supervision", Instruction: "The goal is the best possible document within its token budget, not a perfect corpus or index. Ensure the worker meets the stated research floor, preserves useful evidence locally, and makes the index sufficient for writing. Object to work beyond what would materially improve the document."},
				}},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 250}, Key: "research result"},
			}},
			{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 258}, Name: "agent4", Services: []workflow.Service{}, Body: []workflow.Operation{
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 259}, Key: "assigned topic group"},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 260}, Key: "topic directories"},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 261}, Key: "minimum sources per assigned topic"},
				workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 262}, Name: "research-indexing", From: ""},
				workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 263}, Name: "document-supervision", From: ""},
				workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 264}, Session: "research-indexing", Role: "research-indexing", Prompt: "Research every assigned topic for the final document. The topic directories align with the assigned topics in the same order. For each topic, download at least the required number of useful sources into that topic directory's sources subdirectory. Address every assigned question or explicitly mark it unresolved. Write INDEX.md in each topic directory with a concise goal-relevant synthesis, citations to the local source files, and links to longer clips in its clips subdirectory when summarizing would lose important detail. Return the files and questions you actually addressed. Stop once this definition of done is met for every assigned topic.", Supervisors: []workflow.Supervisor{
					{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 265}, Session: "document-supervision", Role: "document-supervision", Instruction: "The goal is the best possible document within its token budget, not a perfect corpus or index. Ensure the worker meets the stated research floor, preserves useful evidence locally, and makes the index sufficient for writing. Object to work beyond what would materially improve the document."},
				}},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 269}, Key: "research result"},
			}},
			{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 277}, Name: "agent5", Services: []workflow.Service{}, Body: []workflow.Operation{
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 278}, Key: "assigned topic group"},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 279}, Key: "topic directories"},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 280}, Key: "minimum sources per assigned topic"},
				workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 281}, Name: "research-indexing", From: ""},
				workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 282}, Name: "document-supervision", From: ""},
				workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 283}, Session: "research-indexing", Role: "research-indexing", Prompt: "Research every assigned topic for the final document. The topic directories align with the assigned topics in the same order. For each topic, download at least the required number of useful sources into that topic directory's sources subdirectory. Address every assigned question or explicitly mark it unresolved. Write INDEX.md in each topic directory with a concise goal-relevant synthesis, citations to the local source files, and links to longer clips in its clips subdirectory when summarizing would lose important detail. Return the files and questions you actually addressed. Stop once this definition of done is met for every assigned topic.", Supervisors: []workflow.Supervisor{
					{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 284}, Session: "document-supervision", Role: "document-supervision", Instruction: "The goal is the best possible document within its token budget, not a perfect corpus or index. Ensure the worker meets the stated research floor, preserves useful evidence locally, and makes the index sufficient for writing. Object to work beyond what would materially improve the document."},
				}},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 288}, Key: "research result"},
			}},
		}},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 299}, Key: "topic index paths"},
		workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 301}, Name: "index-curation", From: ""},
		workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 302}, Name: "document-supervision", From: ""},
		workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 303}, Session: "index-curation", Role: "index-curation", Prompt: "Build the semantic index at the exact semantic index path from the topic indexes. Organize it for the document goal: preserve the important knowledge, cite local evidence, and link to longer clips when compression would lose something the author may need. The index should be the author's sufficient entry point into the corpus. Stop when it supports writing the document; do not perfect it for its own sake.", Supervisors: []workflow.Supervisor{
			{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 304}, Session: "document-supervision", Role: "document-supervision", Instruction: "The goal is the best possible document within its token budget, not a perfect corpus or index. Ensure the worker meets the stated research floor, preserves useful evidence locally, and makes the index sufficient for writing. Object to work beyond what would materially improve the document."},
		}},
		workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 311}, Name: "document-authoring", From: ""},
		workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 312}, Name: "document-supervision", From: ""},
		workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 313}, Session: "document-authoring", Role: "document-authoring", Prompt: "Write the requested document at the exact document path. Use the semantic index as the only entry point to the research; follow its links to longer local clips only when needed. Maximize the audience's understanding of the most important knowledge within the token budget. Prefer strong lossy compression over accumulating facts. Do not browse the corpus independently or spend work improving the index. Before finishing, repeatedly run the token counter executable with \"count-tokens\" and the document path, editing the document until the reported count is at or below the budget.", Supervisors: []workflow.Supervisor{
			{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 314}, Session: "document-supervision", Role: "document-supervision", Instruction: "The goal is the most important understanding the token budget can hold. Ensure the author actively measures the document with the supplied token counter and edits it under budget. Object when low-value specifics, examples, qualifications, or secondary claims displace the central explanation."},
		}},
		workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 321}, Name: "editorial-review", From: ""},
		workflow.Repeat{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 322}, Cond: "round := 1; round <= maxRounds; round++", Body: []workflow.Operation{
			workflow.Scope{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 324}, Name: "editorial-round", Services: []workflow.Service{}, Body: []workflow.Operation{
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 325}, Key: "editorial round"},
				workflow.Command{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 326}, Name: "count-tokens"},
				workflow.Condition{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 330}, Branches: []workflow.Branch{
					{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 330}, Case: "exit != 0", Exits: true, Body: []workflow.Operation{}},
				}},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 337}, Key: "document token count"},
				workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 339}, Session: "editorial-review", Role: "editorial-review", Prompt: "Independently read the document and semantic index at their exact paths. Assess whether the document achieves its goal within the token budget. OnlyNitpicks is true only when nothing important is absent, misleading, badly prioritized, or wasteful enough to justify another revision. Put authoring or compression defects in MaterialIssues. Put a topic in MissingTopics only when the semantic index lacks the knowledge needed to repair the document."},
				workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 343}, Key: "editorial verdict"},
				workflow.Condition{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 344}, Branches: []workflow.Branch{
					{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 344}, Case: "tokens <= params.TokenBudget && verdict.OnlyNitpicks && len(verdict.MaterialIssues) == 0 && len(verdict.MissingTopics) == 0", Exits: true, Body: []workflow.Operation{}},
				}},
				workflow.Condition{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 349}, Branches: []workflow.Branch{
					{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 349}, Case: "len(verdict.MissingTopics) > 0", Exits: false, Body: []workflow.Operation{
						workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 359}, Key: "missing topics"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 360}, Key: "gap research directory"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 361}, Key: "gap research index path"},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 362}, Key: "minimum gap source files"},
						workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 364}, Name: "research-indexing", From: ""},
						workflow.Session{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 365}, Name: "document-supervision", From: ""},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 366}, Session: "research-indexing", Role: "research-indexing", Prompt: "Research the missing topics identified by the editor. Download at least the required number of useful sources into the gap research sources directory, using the same minimum per missing topic. Write INDEX.md at the exact gap research index path with a concise goal-relevant synthesis, local citations, and links to indispensable longer clips. Return what you actually researched. Stop when the gaps can support the document.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 367}, Session: "document-supervision", Role: "document-supervision", Instruction: "The goal is the best possible document within its token budget, not a perfect corpus or index. Ensure the worker meets the stated research floor, preserves useful evidence locally, and makes the index sufficient for writing. Object to work beyond what would materially improve the document."},
						}},
						workflow.Set{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 371}, Key: "gap research result"},
						workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 375}, Session: "index-curation", Role: "index-curation", Prompt: "Update the semantic index with the gap research identified in this editorial round. Preserve its usefulness as the author's single entry point, add the important missing knowledge and local citations, and stop when the document can be repaired.", Supervisors: []workflow.Supervisor{
							{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 376}, Session: "document-supervision", Role: "document-supervision", Instruction: "The goal is the best possible document within its token budget, not a perfect corpus or index. Ensure the worker meets the stated research floor, preserves useful evidence locally, and makes the index sufficient for writing. Object to work beyond what would materially improve the document."},
						}},
					}},
				}},
				workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 381}, Session: "document-authoring", Role: "document-authoring", Prompt: "Revise the document at its exact path using the editorial verdict, measured token count, and current semantic index. Fix every material issue. Protect the most important understanding; remove lower-value specifics, examples, qualifications, and secondary claims before weakening the central explanation. Before finishing, repeatedly run the token counter executable with \"count-tokens\" and the document path, editing until the reported count is at or below the budget.", Supervisors: []workflow.Supervisor{
					{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 382}, Session: "document-supervision", Role: "document-supervision", Instruction: "The goal is the most important understanding the token budget can hold. Ensure the author actively measures the document with the supplied token counter and edits it under budget. Object when low-value specifics, examples, qualifications, or secondary claims displace the central explanation."},
				}},
			}},
			workflow.Condition{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 390}, Branches: []workflow.Branch{
				{Source: workflow.Source{File: "internal/workflows/researchdocument/researchdocument.go", Line: 390}, Case: "accepted", Exits: true, Body: []workflow.Operation{}},
			}},
		}},
	},
}

// Command is gimble run research-document: Gimble's environment flag, a flag for each field of Params, a
// model flag for each role ResearchDocument names with defaults supplied by the caller,
// the web application's flags, and a run of ResearchDocument on the runtime.
func Command(defaults map[gimble.WorkflowRole]string) *cobra.Command {
	var params Params
	var optMinSourcesPerTopic int
	var optMaxEditorialRounds int
	var researchPlanningModel string
	var researchIndexingModel string
	var documentSupervisionModel string
	var indexCurationModel string
	var documentAuthoringModel string
	var editorialReviewModel string
	var workDir string
	var port int
	var uds string
	var noWeb bool
	cmd := &cobra.Command{
		Use:   "research-document",
		Short: "ResearchDocument produces a research-backed document within a token budget.",
		Long:  "Package researchdocument researches a subject into a local semantic index,\nwrites a size-bounded document, and revises it until an independent editor\nfinds only nitpicks.\n\nThe planner returns exactly five coherent groups of adjacent or related\ntopics, one for each explicitly named parallel researcher. Each topic must\nleave at least the requested number of useful local source files, address\nevery assigned question or mark it unresolved, and write an INDEX.md that\ncites those sources and links to longer clips when compression would lose\nimportant detail. The index is a means to the document, not a completeness\nproject.\n\nThe author uses the combined semantic index as its entry point to the corpus.\nAn editorial pass checks the document against the goal, index, and token\nbudget. Material omissions trigger targeted research and index repair before\nanother revision. The workflow succeeds when the document is within budget\nand the editor reports only nitpicks, or returns an error after the editorial\nround limit.\n\nModel cost guidance: the configured defaults reserve Astra for\ndocument-authoring and editorial-review; research, indexing, curation, and\nsupervision already use Luna. Keep Astra for ambiguous, contested,\nhigh-stakes, or technically difficult synthesis. For a clearly bounded,\nroutine document, deliberately tune those two roles down to Sol or Opus:\n\n\t--document-authoring gpt-5.6-sol:high \\\n\t--editorial-review claude-opus-5:high\n\nExample:\n\n\tgimble run research-document \\\n\t  --goal \"Explain passkeys to security-conscious product managers\" \\\n\t  --research-dir ./passkeys-research \\\n\t  --output ./passkeys.md \\\n\t  --token-budget 4000",
		Args:  cobra.NoArgs,
	}
	cmd.Flags().StringVar(&params.Goal, "goal", "", "Goal describes the audience, subject, and understanding the document must produce. (required)")
	cmd.Flags().StringVar(&params.ResearchDir, "research-dir", "", "ResearchDir receives downloaded sources, clips, topic indexes, and the combined INDEX.md. (required)")
	cmd.Flags().StringVar(&params.Output, "output", "", "Output is the document file the author creates or revises. (required)")
	cmd.Flags().IntVar(&params.TokenBudget, "token-budget", 0, "TokenBudget is the maximum o200k_base token count accepted for the document. (required)")
	cmd.Flags().IntVar(&optMinSourcesPerTopic, "min-sources-per-topic", 0, "MinSourcesPerTopic overrides the default minimum of three useful local source files per planned topic.")
	cmd.Flags().IntVar(&optMaxEditorialRounds, "max-editorial-rounds", 0, "MaxEditorialRounds overrides the default limit of three editorial passes.")
	_ = cmd.MarkFlagRequired("goal")
	_ = cmd.MarkFlagRequired("research-dir")
	_ = cmd.MarkFlagRequired("output")
	_ = cmd.MarkFlagRequired("token-budget")
	cmd.Flags().StringVar(&workDir, "work-dir", ".", "the working directory for this run")
	researchPlanningModelDefault := defaults[gimble.WorkflowRole("research-planning")]
	if researchPlanningModelDefault == "" {
		cmd.Flags().StringVar(&researchPlanningModel, "research-planning", "", "the model for role research-planning, as model or model:effort")
		_ = cmd.MarkFlagRequired("research-planning")
	} else {
		cmd.Flags().StringVar(&researchPlanningModel, "research-planning", researchPlanningModelDefault, "advanced override for role research-planning, as model or model:effort; omit this flag to use the displayed workflow default")
	}
	researchIndexingModelDefault := defaults[gimble.WorkflowRole("research-indexing")]
	if researchIndexingModelDefault == "" {
		cmd.Flags().StringVar(&researchIndexingModel, "research-indexing", "", "the model for role research-indexing, as model or model:effort")
		_ = cmd.MarkFlagRequired("research-indexing")
	} else {
		cmd.Flags().StringVar(&researchIndexingModel, "research-indexing", researchIndexingModelDefault, "advanced override for role research-indexing, as model or model:effort; omit this flag to use the displayed workflow default")
	}
	documentSupervisionModelDefault := defaults[gimble.WorkflowRole("document-supervision")]
	if documentSupervisionModelDefault == "" {
		cmd.Flags().StringVar(&documentSupervisionModel, "document-supervision", "", "the model for role document-supervision, as model or model:effort")
		_ = cmd.MarkFlagRequired("document-supervision")
	} else {
		cmd.Flags().StringVar(&documentSupervisionModel, "document-supervision", documentSupervisionModelDefault, "advanced override for role document-supervision, as model or model:effort; omit this flag to use the displayed workflow default")
	}
	indexCurationModelDefault := defaults[gimble.WorkflowRole("index-curation")]
	if indexCurationModelDefault == "" {
		cmd.Flags().StringVar(&indexCurationModel, "index-curation", "", "the model for role index-curation, as model or model:effort")
		_ = cmd.MarkFlagRequired("index-curation")
	} else {
		cmd.Flags().StringVar(&indexCurationModel, "index-curation", indexCurationModelDefault, "advanced override for role index-curation, as model or model:effort; omit this flag to use the displayed workflow default")
	}
	documentAuthoringModelDefault := defaults[gimble.WorkflowRole("document-authoring")]
	if documentAuthoringModelDefault == "" {
		cmd.Flags().StringVar(&documentAuthoringModel, "document-authoring", "", "the model for role document-authoring, as model or model:effort")
		_ = cmd.MarkFlagRequired("document-authoring")
	} else {
		cmd.Flags().StringVar(&documentAuthoringModel, "document-authoring", documentAuthoringModelDefault, "advanced override for role document-authoring, as model or model:effort; omit this flag to use the displayed workflow default")
	}
	editorialReviewModelDefault := defaults[gimble.WorkflowRole("editorial-review")]
	if editorialReviewModelDefault == "" {
		cmd.Flags().StringVar(&editorialReviewModel, "editorial-review", "", "the model for role editorial-review, as model or model:effort")
		_ = cmd.MarkFlagRequired("editorial-review")
	} else {
		cmd.Flags().StringVar(&editorialReviewModel, "editorial-review", editorialReviewModelDefault, "advanced override for role editorial-review, as model or model:effort; omit this flag to use the displayed workflow default")
	}
	cmd.Flags().IntVar(&port, "port", 8080, "loopback TCP port for the web application")
	cmd.Flags().StringVar(&uds, "uds", "", "Unix-domain socket for the web application instead of TCP")
	cmd.Flags().BoolVar(&noWeb, "no-web", false, "run without the web application")
	cmd.RunE = func(cmd *cobra.Command, _ []string) error {
		if cmd.Flags().Changed("min-sources-per-topic") {
			params.MinSourcesPerTopic = polytype.Optional[int]{Present: true, Value: optMinSourcesPerTopic}
		}
		if cmd.Flags().Changed("max-editorial-rounds") {
			params.MaxEditorialRounds = polytype.Optional[int]{Present: true, Value: optMaxEditorialRounds}
		}
		workDir, err := filepath.Abs(workDir)
		if err != nil {
			return err
		}
		models, err := binding.Roles(map[gimble.WorkflowRole]string{gimble.WorkflowRole("research-planning"): researchPlanningModel, gimble.WorkflowRole("research-indexing"): researchIndexingModel, gimble.WorkflowRole("document-supervision"): documentSupervisionModel, gimble.WorkflowRole("index-curation"): indexCurationModel, gimble.WorkflowRole("document-authoring"): documentAuthoringModel, gimble.WorkflowRole("editorial-review"): editorialReviewModel})
		if err != nil {
			return err
		}
		ctx, stop := signal.NotifyContext(cmd.Context(), os.Interrupt)
		defer stop()
		var options []web.Option
		switch {
		case noWeb:
			options = append(options, web.WithNoWeb())
		case uds != "":
			options = append(options, web.WithUDS(uds))
		default:
			options = append(options, web.WithPort(port))
		}
		runtime, err := web.NewRuntime(ctx, filepath.Join(workDir, ".gimble"), options...)
		if err != nil {
			return err
		}
		env := gimble.Env{WorkDir: workDir}
		return runtime.Run(ctx, "research-document", models, func(ctx context.Context) error { return ResearchDocument(ctx, env, params) })
	}
	return cmd
}
