<script lang="ts">
  import BotIcon from "@lucide/svelte/icons/bot"; import ExternalLinkIcon from "@lucide/svelte/icons/external-link"; import GitBranchIcon from "@lucide/svelte/icons/git-branch"; import LoaderCircleIcon from "@lucide/svelte/icons/loader-circle"; import SendIcon from "@lucide/svelte/icons/send"; import TerminalSquareIcon from "@lucide/svelte/icons/square-terminal";
  import { sendConversationMessage, watchConversation } from "../../conversation.remote.js";
  import type { Conversation } from "#lib/skgo/conversation/types.js";
  let { data }: { data: { selected: Conversation } } = $props();
  const current = $derived((await watchConversation(data.selected.id)) as Conversation);
  const providerName = (name: string) => name === "agy" ? "agy / Gemini" : name === "codex" ? "Codex" : "Claude";
</script>
<section class="conversation-detail">
  <header class="conversation-header"><div><div class="title-row"><BotIcon size={20} aria-hidden="true" /><h2>{current.title}</h2><span class="provider-badge">{providerName(current.provider)}</span></div><p class="model">{current.model}</p></div><div class="git-facts"><div><GitBranchIcon size={15} /><code>{current.branch}</code></div><div><TerminalSquareIcon size={15} /><code>{current.worktree}</code></div></div></header>
  <div class="transcript" aria-live="polite">
    {#if current.runs.length > 0}<section class="conversation-runs" aria-label="Workflow runs"><span class="role">Workflow runs</span>{#each current.runs as run (run.id)}<a href={`/runs/${encodeURIComponent(run.id)}`}><span class="run-name">{run.workflow}</span><span class={{ running: run.status === "running", error: run.status === "error", "run-status": true }}>{run.status}</span><code>{run.id}</code><ExternalLinkIcon size={14} aria-hidden="true" /></a>{#if run.error}<p class="run-error">{run.error}</p>{/if}{/each}</section>{/if}
    {#each current.messages as entry, index (`${entry.created}-${index}`)}<article class={{ assistant: entry.role === "assistant", message: true }}><span class="role">{entry.role === "assistant" ? providerName(current.provider) : "You"}</span><p>{entry.text}</p></article>{:else}<div class="empty-transcript"><BotIcon size={30} aria-hidden="true" /><h3>Ready in its own worktree</h3><p>Send a message to start a continuing {providerName(current.provider)} session.</p></div>{/each}
    {#if sendConversationMessage.pending > 0 || current.status === "working"}<div class="working-state"><LoaderCircleIcon class="spin" size={16} />{providerName(current.provider)} is working in {current.branch}</div>{/if}
    {#if current.error}<div class="error-state"><strong>Conversation error</strong><span>{current.error}</span></div>{/if}
    {#if !current.live}<div class="history-state"><strong>Saved history</strong><span>The provider session ended when the server restarted. Start a new conversation to continue.</span></div>{/if}
  </div>
  <form class="composer" {...sendConversationMessage}><input {...sendConversationMessage.fields.conversation.as("hidden", current.id)} /><textarea {...sendConversationMessage.fields.message.as("text")} rows={3} placeholder={`Message ${providerName(current.provider)}…`} aria-label="Message" disabled={!current.live || sendConversationMessage.pending > 0 || current.status === "working"}></textarea>{#each sendConversationMessage.fields.message.issues() ?? [] as issue}<p class="issue">{issue.message}</p>{/each}{#each sendConversationMessage.fields.allIssues() ?? [] as issue}<p class="issue">{issue.message}</p>{/each}<button class="send" type="submit" aria-label="Send message" disabled={!current.live || !sendConversationMessage.fields.message.value()?.trim() || sendConversationMessage.pending > 0 || current.status === "working"}><SendIcon size={18} /></button></form>
</section>
<style>
  .conversation-detail { display: grid; min-height: 0; grid-template-rows: auto minmax(0, 1fr) auto; } h2, h3, p { margin: 0; } .conversation-header { display: flex; align-items: flex-start; justify-content: space-between; gap: 24px; padding: 20px 28px; border-bottom: 1px solid var(--border); } .title-row { display: flex; align-items: center; gap: 9px; } .title-row h2 { font-size: 1.03rem; } .model { margin: 4px 0 0 29px; color: var(--muted-foreground); font-family: var(--font-mono); font-size: .72rem; } .provider-badge, .run-status { padding: 2px 8px; border: 1px solid var(--border); border-radius: 999px; color: var(--muted-foreground); background: var(--surface); font-size: .67rem; font-weight: 700; } .git-facts { display: grid; max-width: 52%; gap: 5px; } .git-facts div { display: flex; align-items: center; justify-content: flex-end; gap: 7px; color: var(--muted-foreground); } code { overflow: hidden; font-family: var(--font-mono); font-size: .68rem; text-overflow: ellipsis; white-space: nowrap; }
  .transcript { display: flex; flex-direction: column; gap: 18px; overflow: auto; padding: 34px max(28px, calc((100% - 780px) / 2)); } .message { align-self: flex-end; max-width: min(680px, 86%); } .message.assistant { align-self: flex-start; width: min(680px, 92%); } .role { display: block; margin-bottom: 5px; color: var(--muted-foreground); font-size: .7rem; font-weight: 700; } .message p { padding: 11px 14px; border-radius: 16px 16px 4px 16px; background: var(--accent); white-space: pre-wrap; } .message.assistant p { padding: 0; border-radius: 0; background: transparent; }
  .conversation-runs { display: grid; gap: 7px; padding: 12px; border: 1px solid var(--border); border-radius: var(--radius-lg); background: var(--surface); } .conversation-runs a { display: grid; grid-template-columns: auto auto minmax(0, 1fr) auto; align-items: center; gap: 9px; color: inherit; text-decoration: none; } .run-name { font-size: .8rem; font-weight: 700; text-transform: capitalize; } .run-status.running { color: var(--status-running); } .run-status.error, .run-error, .issue { color: var(--destructive); } .run-error, .issue { font-size: .72rem; }
  .working-state, .error-state, .history-state { display: flex; width: fit-content; align-items: center; gap: 8px; color: var(--muted-foreground); font-size: .78rem; } .error-state, .history-state { align-items: flex-start; flex-direction: column; padding: 10px 12px; border: 1px solid var(--border); border-radius: var(--radius); background: var(--surface); } .error-state { color: var(--destructive); } .empty-transcript { display: grid; place-items: center; align-content: center; gap: 8px; height: 100%; color: var(--muted-foreground); text-align: center; } .empty-transcript h3 { color: var(--foreground); } .empty-transcript p { max-width: 480px; font-size: .86rem; }
  .composer { position: relative; width: min(780px, calc(100% - 56px)); margin: 0 auto 25px; } textarea { box-sizing: border-box; width: 100%; min-height: 82px; resize: vertical; padding: 13px 50px 13px 14px; border: 1px solid var(--input); border-radius: calc(var(--radius) - 2px); color: var(--foreground); background: var(--card); font: inherit; box-shadow: var(--shadow-md); } .send { position: absolute; right: 10px; bottom: 10px; display: inline-flex; width: 34px; height: 34px; align-items: center; justify-content: center; border: 0; border-radius: 9px; color: var(--primary-foreground); background: var(--primary); } .send:disabled { opacity: .5; } @media (max-width: 800px) { .conversation-header { flex-direction: column; } .git-facts { max-width: 100%; } .git-facts div { justify-content: flex-start; } }
</style>
