//go:build !jsonschema

// Code generated by internal/generate. DO NOT EDIT.

package implementinterview

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/tylergannon/gimble"
	"github.com/tylergannon/gimble/web"
	"github.com/tylergannon/gimble/workflow"
)

func init() { gimble.RegisterGraph(Graph) }

// Graph is the shape of this workflow, read from the source of ImplementInterview.
var Graph = workflow.Graph{
	Name:     "implement-interview",
	Source:   workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 45},
	Services: []workflow.Service{},
	Body: []workflow.Operation{
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 46}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 46}, Case: "!filepath.IsAbs(params.RequirementsFile) || !filepath.IsAbs(params.ReferenceDir)", Exits: true, Body: []workflow.Operation{}},
		}},
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 49}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 49}, Case: "params.MaxTasks < 1", Exits: true, Body: []workflow.Operation{}},
		}},
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 55}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 55}, Case: "info, err := os.Stat(params.ReferenceDir); err != nil || !info.IsDir()", Exits: true, Body: []workflow.Operation{}},
		}},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 59}, Key: "requirements-file"},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 60}, Key: "reference-directory"},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 61}, Key: "repository"},
		workflow.Group{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 63}, Name: "reconnaissance", Children: []workflow.GroupChild{
			{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 64}, Name: "backend", Services: []workflow.Service{}, Body: []workflow.Operation{
				workflow.Session{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 65}, Name: "api-research", From: ""},
				workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 66}, Session: "api-research", Role: "api-research", Prompt: "Read the saved issue, current Go API and design docs, pinned dependencies, runtime/events/generation code, Polytype use, and skgo Go remote-function APIs. Do not edit source. Under the reference directory, create backend/index.md with deep implementation notes and provenance, and save useful official source documentation under backend/. Distinguish verified facts from proposals."},
			}},
			{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 69}, Name: "frontend", Services: []workflow.Service{}, Body: []workflow.Operation{
				workflow.Session{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 70}, Name: "frontend-research", From: ""},
				workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 71}, Session: "frontend-research", Role: "frontend-research", Prompt: "Read the saved issue, current live-run UI, pinned frontend dependencies, and installed shadcn-svelte components. Research the actual Svelte, SvelteKit, shadcn-svelte, and Bits UI APIs needed by the issue. Do not edit source. Under the reference directory, create frontend/index.md with deep implementation notes and provenance, and save useful official source documentation under frontend/. Distinguish verified facts from proposals."},
			}},
		}},
		workflow.Session{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 78}, Name: "sprint-planning", From: ""},
		workflow.Session{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 79}, Name: "coding", From: ""},
		workflow.Session{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 80}, Name: "implementation-scope-review", From: ""},
		workflow.Session{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 81}, Name: "architectural-critique", From: ""},
		workflow.PromiseLoop{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 84}, Name: "implementation", Planner: "sprint-planning", Services: []workflow.Service{}, Body: []workflow.Operation{
			workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 92}, Session: "coding", Role: "coding", Prompt: "Read the saved issue and the local reference directory, then implement only the selected task in the repository. Do not expand the specification, modify the requirements or this build workflow, weaken its fixed checks, commit, merge, or add proof scripts or run output. Preserve unrelated work. Answer with what changed and what you personally ran or observed.", Supervisors: []workflow.Supervisor{
				{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 93}, Session: "implementation-scope-review", Role: "implementation-scope-review", Instruction: "Watch only for concrete backend or public-API work beyond the saved issue 249. Steer against unnecessary wrappers, frameworks, speculative APIs, and unrelated features. Do not edit source, object on style, or demand improvements outside the requirements."},
				{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 94}, Session: "architectural-critique", Role: "architectural-critique", Instruction: "Watch only for concrete frontend or general implementation work beyond the saved issue 249. Steer against unnecessary abstractions, frameworks, speculative features, and unrelated polish. Do not edit source, object on style, or demand improvements outside the requirements."},
			}},
			workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 102}, Branches: []workflow.Branch{
				{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 102}, Case: "command := strings.TrimSpace(task.Validation.Command); command != \"\"", Exits: false, Body: []workflow.Operation{
					workflow.Command{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 103}, Name: "task-check"},
					workflow.Set{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 104}, Key: "task check"},
				}},
			}},
			workflow.Command{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 112}, Name: "build"},
			workflow.Set{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 113}, Key: "just build"},
			workflow.Command{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 118}, Name: "vet"},
			workflow.Set{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 119}, Key: "just vet"},
			workflow.Command{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 124}, Name: "test"},
			workflow.Set{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 125}, Key: "just test"},
			workflow.Session{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 131}, Name: "qa-orchestration", From: ""},
			workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 132}, Session: "qa-orchestration", Role: "qa-orchestration", Prompt: "Independently read the saved issue, reference directory, implementation, tests, and recorded command results. Make no source changes and do not treat the worker report as evidence. Start the generated interview example on a separate port with its interviewer bound to Terra or Sonnet, never Gemini. Use the installed Playwright through the shell to conduct successive human answers in a real browser; do not write proof programs or commit run artifacts, and cleanly stop the example process afterward. Complete is true only if you personally demonstrate every requirement in that running interface; tests and reports alone are insufficient."},
			workflow.Set{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 137}, Key: "independent assessment"},
			workflow.Set{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 138}, Key: "worker report"},
			workflow.Set{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 140}, Key: "deterministic checks passed"},
			workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 141}, Branches: []workflow.Branch{
				{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 141}, Case: "checksPassed && assessment.Complete", Exits: true, Body: []workflow.Operation{}},
			}},
			workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 145}, Branches: []workflow.Branch{
				{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 145}, Case: "tasksRun >= params.MaxTasks", Exits: true, Body: []workflow.Operation{}},
			}},
		}},
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 156}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 156}, Case: "completed", Exits: true, Body: []workflow.Operation{}},
		}},
		workflow.Condition{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 159}, Branches: []workflow.Branch{
			{Source: workflow.Source{File: "internal/workflows/implementinterview/implementinterview.go", Line: 159}, Case: "exhausted", Exits: true, Body: []workflow.Operation{}},
		}},
	},
}

// Hosted is the entry ImplementInterview supplies to the persistent instance.
func Hosted() web.WorkflowEntry {
	return func(ctx context.Context, env gimble.Env, raw json.RawMessage) error {
		var params InterviewBuildParams
		if err := json.Unmarshal(raw, &params); err != nil {
			return err
		}
		return ImplementInterview(ctx, env, params)
	}
}

// Command is gimble run implement-interview: a flag for each field of InterviewBuildParams, a
// model flag for each role ImplementInterview names, instance and project selection,
// and optional waiting for the hosted run's terminal result.
func Command(defaults map[gimble.WorkflowRole]string) *cobra.Command {
	var params InterviewBuildParams
	var apiResearchModel string
	var frontendResearchModel string
	var sprintPlanningModel string
	var codingModel string
	var implementationScopeReviewModel string
	var architecturalCritiqueModel string
	var qaOrchestrationModel string
	var workDir string
	var project string
	var instanceDir string
	var conversation string
	var follow bool
	cmd := &cobra.Command{
		Use:   "implement-interview",
		Short: "ImplementInterview researches, implements, and independently validates issue 249.",
		Long:  "Package implementinterview builds and demonstrates Gimble issue 249." + "\n\nThe selected persistent instance owns this run. --project selects its admitted repository; --work-dir selects the execution directory independently. --instance-dir selects the instance state directory (or GIMBLE_INSTANCE_DIR, default .gimble). --follow waits for terminal success or failure; otherwise the run continues after this client exits. Each role flag chooses a model and optional effort. Executable lookup, PATH, and provider configuration come from the instance startup environment.",
		Args:  cobra.NoArgs,
	}
	cmd.Flags().StringVar(&params.RequirementsFile, "requirements-file", "", "RequirementsFile is the absolute path to the locally saved issue 249. (required)")
	cmd.Flags().StringVar(&params.ReferenceDir, "reference-dir", "", "ReferenceDir is the absolute untracked directory where researchers write their notes and downloaded primary sources. (required)")
	cmd.Flags().IntVar(&params.MaxTasks, "max-tasks", 0, "MaxTasks is the maximum number of planner assignments the workflow may run. (required)")
	_ = cmd.MarkFlagRequired("requirements-file")
	_ = cmd.MarkFlagRequired("reference-dir")
	_ = cmd.MarkFlagRequired("max-tasks")
	cmd.Flags().StringVar(&workDir, "work-dir", "", "execution directory (default: owning project)")
	cmd.Flags().StringVar(&project, "project", ".", "admitted repository owning this run and its observation")
	instanceDefault := os.Getenv("GIMBLE_INSTANCE_DIR")
	if instanceDefault == "" {
		instanceDefault = ".gimble"
	}
	cmd.Flags().StringVar(&instanceDir, "instance-dir", instanceDefault, "selected running instance state directory (default: GIMBLE_INSTANCE_DIR or .gimble)")
	cmd.Flags().StringVar(&conversation, "conversation", "", "associate this run with a conversation in the owning project")
	cmd.Flags().BoolVar(&follow, "follow", false, "wait for the hosted run's terminal result; without this flag the run survives client exit")
	apiResearchModelDefault := defaults[gimble.WorkflowRole("api-research")]
	if apiResearchModelDefault == "" {
		cmd.Flags().StringVar(&apiResearchModel, "api-research", "", "the model for role api-research, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model")
		_ = cmd.MarkFlagRequired("api-research")
	} else {
		cmd.Flags().StringVar(&apiResearchModel, "api-research", apiResearchModelDefault, "advanced override for role api-research, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model; omit this flag to use the displayed workflow default")
	}
	frontendResearchModelDefault := defaults[gimble.WorkflowRole("frontend-research")]
	if frontendResearchModelDefault == "" {
		cmd.Flags().StringVar(&frontendResearchModel, "frontend-research", "", "the model for role frontend-research, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model")
		_ = cmd.MarkFlagRequired("frontend-research")
	} else {
		cmd.Flags().StringVar(&frontendResearchModel, "frontend-research", frontendResearchModelDefault, "advanced override for role frontend-research, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model; omit this flag to use the displayed workflow default")
	}
	sprintPlanningModelDefault := defaults[gimble.WorkflowRole("sprint-planning")]
	if sprintPlanningModelDefault == "" {
		cmd.Flags().StringVar(&sprintPlanningModel, "sprint-planning", "", "the model for role sprint-planning, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model")
		_ = cmd.MarkFlagRequired("sprint-planning")
	} else {
		cmd.Flags().StringVar(&sprintPlanningModel, "sprint-planning", sprintPlanningModelDefault, "advanced override for role sprint-planning, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model; omit this flag to use the displayed workflow default")
	}
	codingModelDefault := defaults[gimble.WorkflowRole("coding")]
	if codingModelDefault == "" {
		cmd.Flags().StringVar(&codingModel, "coding", "", "the model for role coding, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model")
		_ = cmd.MarkFlagRequired("coding")
	} else {
		cmd.Flags().StringVar(&codingModel, "coding", codingModelDefault, "advanced override for role coding, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model; omit this flag to use the displayed workflow default")
	}
	implementationScopeReviewModelDefault := defaults[gimble.WorkflowRole("implementation-scope-review")]
	if implementationScopeReviewModelDefault == "" {
		cmd.Flags().StringVar(&implementationScopeReviewModel, "implementation-scope-review", "", "the model for role implementation-scope-review, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model")
		_ = cmd.MarkFlagRequired("implementation-scope-review")
	} else {
		cmd.Flags().StringVar(&implementationScopeReviewModel, "implementation-scope-review", implementationScopeReviewModelDefault, "advanced override for role implementation-scope-review, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model; omit this flag to use the displayed workflow default")
	}
	architecturalCritiqueModelDefault := defaults[gimble.WorkflowRole("architectural-critique")]
	if architecturalCritiqueModelDefault == "" {
		cmd.Flags().StringVar(&architecturalCritiqueModel, "architectural-critique", "", "the model for role architectural-critique, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model")
		_ = cmd.MarkFlagRequired("architectural-critique")
	} else {
		cmd.Flags().StringVar(&architecturalCritiqueModel, "architectural-critique", architecturalCritiqueModelDefault, "advanced override for role architectural-critique, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model; omit this flag to use the displayed workflow default")
	}
	qaOrchestrationModelDefault := defaults[gimble.WorkflowRole("qa-orchestration")]
	if qaOrchestrationModelDefault == "" {
		cmd.Flags().StringVar(&qaOrchestrationModel, "qa-orchestration", "", "the model for role qa-orchestration, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model")
		_ = cmd.MarkFlagRequired("qa-orchestration")
	} else {
		cmd.Flags().StringVar(&qaOrchestrationModel, "qa-orchestration", qaOrchestrationModelDefault, "advanced override for role qa-orchestration, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model; omit this flag to use the displayed workflow default")
	}
	cmd.RunE = func(cmd *cobra.Command, _ []string) error {
		project, err := filepath.Abs(project)
		if err != nil {
			return err
		}
		if workDir == "" {
			workDir = project
		}
		workDir, err = filepath.Abs(workDir)
		if err != nil {
			return err
		}
		values := map[string]any{
			"RequirementsFile": params.RequirementsFile,
			"ReferenceDir":     params.ReferenceDir,
			"MaxTasks":         params.MaxTasks,
		}
		paramsJSON, err := json.Marshal(values)
		if err != nil {
			return err
		}
		admitted, err := web.Submit(cmd.Context(), instanceDir, project, web.Submission{
			Name: "implement-interview", Params: paramsJSON, WorkDir: workDir, Conversation: conversation,
			Models: map[gimble.WorkflowRole]string{gimble.WorkflowRole("api-research"): apiResearchModel, gimble.WorkflowRole("frontend-research"): frontendResearchModel, gimble.WorkflowRole("sprint-planning"): sprintPlanningModel, gimble.WorkflowRole("coding"): codingModel, gimble.WorkflowRole("implementation-scope-review"): implementationScopeReviewModel, gimble.WorkflowRole("architectural-critique"): architecturalCritiqueModel, gimble.WorkflowRole("qa-orchestration"): qaOrchestrationModel},
		})
		if err != nil {
			return err
		}
		fmt.Fprintln(cmd.OutOrStdout(), admitted.ID)
		if !follow {
			return nil
		}
		result, err := web.Follow(cmd.Context(), instanceDir, project, admitted.ID)
		if err != nil {
			return err
		}
		if result.Status != "completed" {
			return fmt.Errorf("run %s %s: %s", admitted.ID, result.Status, result.Error)
		}
		return nil
	}
	return cmd
}
