package main

import (
	"bytes"
	"testing"
)

const fixture = `{
  "openai": {"models": {
    "late": {"id":"z-model","name":"Z","release_date":"2026-01-02","last_updated":"2026-01-03","cost":{"input":4,"output":20,"cache_read":0.4,"cache_write":5}},
    "early": {"id":"a-model","name":"A","release_date":"2026-01-01","last_updated":"2026-01-02","cost":{"input":0.2,"output":1.2,"cache_read":0.02,"cache_write":0.25}},
    "free": {"id":"unpriced","name":"Unpriced"}
  }},
  "anthropic": {"models": {
    "haiku": {"id":"claude-haiku-4-5-20251001","name":"Claude Haiku 4.5","release_date":"2025-10-15","last_updated":"2025-10-15","cost":{"input":1,"output":5,"cache_read":0.1,"cache_write":1.25}}
  }},
  "google": {"models": {
    "flash": {"id":"gemini-3.8-flash","name":"Gemini 3.8 Flash","release_date":"2026-09-02","last_updated":"2026-09-02","cost":{"input":0.75,"output":3.75,"cache_read":0.075}}
  }}
}`

func TestDecodeAndRenderAreDeterministic(t *testing.T) {
	rows, err := decode([]byte(fixture))
	if err != nil {
		t.Fatal(err)
	}
	if len(rows) != 4 {
		t.Fatalf("priced rows = %d, want 4", len(rows))
	}
	if rows[0].Provider != "anthropic" || rows[0].ID != "claude-haiku-4-5-20251001" || rows[3].ID != "z-model" {
		t.Fatalf("rows are not sorted by provider and model: %#v", rows)
	}
	if rows[1].ID != "gemini-3.8-flash" || rows[1].CacheWrite != 0 {
		t.Fatalf("optional cache write = %#v, want zero", rows[1])
	}
	first, err := render(rows)
	if err != nil {
		t.Fatal(err)
	}
	rowsAgain, err := decode([]byte(fixture))
	if err != nil {
		t.Fatal(err)
	}
	second, err := render(rowsAgain)
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(first, second) {
		t.Fatal("same catalog bytes rendered different source")
	}
	want := `// Code generated by modelpricesgen; DO NOT EDIT.

package observation

var modelPrices = []modelPrice{
	{provider: "anthropic", id: "claude-haiku-4-5-20251001", name: "Claude Haiku 4.5", releaseDate: "2025-10-15", lastUpdated: "2025-10-15", input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25},
	{provider: "google", id: "gemini-3.8-flash", name: "Gemini 3.8 Flash", releaseDate: "2026-09-02", lastUpdated: "2026-09-02", input: 0.75, output: 3.75, cacheRead: 0.075, cacheWrite: 0},
	{provider: "openai", id: "a-model", name: "A", releaseDate: "2026-01-01", lastUpdated: "2026-01-02", input: 0.2, output: 1.2, cacheRead: 0.02, cacheWrite: 0.25},
	{provider: "openai", id: "z-model", name: "Z", releaseDate: "2026-01-02", lastUpdated: "2026-01-03", input: 4, output: 20, cacheRead: 0.4, cacheWrite: 5},
}
`
	if string(first) != want {
		t.Fatalf("rendered source:\n%s\nwant:\n%s", first, want)
	}
	for _, row := range rows {
		if row.ID == "unpriced" {
			t.Fatal("model without an input and output price was included")
		}
	}
}

func TestDecodeRejectsMissingProvider(t *testing.T) {
	if _, err := decode([]byte(`{"anthropic":{"models":{}},"openai":{"models":{}}}`)); err == nil {
		t.Fatal("decode accepted a catalog without google")
	}
}
