//go:build !jsonschema

// Code generated by internal/generate. DO NOT EDIT.

package review

import (
	"context"
	"os"
	"os/signal"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/tylergannon/gimble"
	"github.com/tylergannon/gimble/internal/binding"
	"github.com/tylergannon/gimble/web"
	"github.com/tylergannon/gimble/workflow"
)

func init() { gimble.RegisterGraph(Graph) }

// Graph is the shape of this workflow, read from the source of Review.
var Graph = workflow.Graph{
	Name:   "review",
	Source: workflow.Source{File: "internal/workflows/review/review.go", Line: 26},
	Body: []workflow.Operation{
		workflow.Set{Source: workflow.Source{File: "internal/workflows/review/review.go", Line: 27}, Key: "goal"},
		workflow.Session{Source: workflow.Source{File: "internal/workflows/review/review.go", Line: 28}, Name: "code-review", From: ""},
		workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/review/review.go", Line: 29}, Session: "code-review", Role: "code-review", Prompt: "Read the code in your working directory. Assess the goal given below. Report concrete correctness issues; return an empty findings list when there are none. Make no changes."},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/review/review.go", Line: 33}, Key: "result"},
	},
}

// Command is gimble run review: Gimble's environment flag, a flag for each field of ReviewParams, a
// model flag for each role Review names with defaults supplied by the caller,
// the web application's flags, and a run of Review on the runtime.
func Command(defaults map[gimble.WorkflowRole]string) *cobra.Command {
	var params ReviewParams
	var codeReviewModel string
	var workDir string
	var port int
	var uds string
	var noWeb bool
	cmd := &cobra.Command{
		Use:   "review",
		Short: "Review asks one reviewer to inspect the repository read-only and record its findings.",
		Long:  "Package review is a small read-only code review workflow.",
		Args:  cobra.NoArgs,
	}
	cmd.Flags().StringVar(&params.Goal, "goal", "", "Goal says what the review should assess. (required)")
	_ = cmd.MarkFlagRequired("goal")
	cmd.Flags().StringVar(&workDir, "work-dir", ".", "the working directory for this run")
	codeReviewModelDefault := defaults[gimble.WorkflowRole("code-review")]
	if codeReviewModelDefault == "" {
		cmd.Flags().StringVar(&codeReviewModel, "code-review", "", "the model for role code-review, as model or model:effort")
		_ = cmd.MarkFlagRequired("code-review")
	} else {
		cmd.Flags().StringVar(&codeReviewModel, "code-review", codeReviewModelDefault, "advanced override for role code-review, as model or model:effort; omit this flag to use the displayed workflow default")
	}
	cmd.Flags().IntVar(&port, "port", 8080, "loopback TCP port for the web application")
	cmd.Flags().StringVar(&uds, "uds", "", "Unix-domain socket for the web application instead of TCP")
	cmd.Flags().BoolVar(&noWeb, "no-web", false, "run without the web application")
	cmd.RunE = func(cmd *cobra.Command, _ []string) error {
		workDir, err := filepath.Abs(workDir)
		if err != nil {
			return err
		}
		models, err := binding.Roles(map[gimble.WorkflowRole]string{gimble.WorkflowRole("code-review"): codeReviewModel})
		if err != nil {
			return err
		}
		ctx, stop := signal.NotifyContext(cmd.Context(), os.Interrupt)
		defer stop()
		var options []web.Option
		switch {
		case noWeb:
			options = append(options, web.WithNoWeb())
		case uds != "":
			options = append(options, web.WithUDS(uds))
		default:
			options = append(options, web.WithPort(port))
		}
		runtime, err := web.NewRuntime(ctx, filepath.Join(workDir, ".gimble"), options...)
		if err != nil {
			return err
		}
		env := gimble.Env{WorkDir: workDir}
		return runtime.Run(ctx, "review", models, func(ctx context.Context) error { return Review(ctx, env, params) })
	}
	return cmd
}
