//go:build !jsonschema

// Code generated by internal/generate. DO NOT EDIT.

package review

import (
	"github.com/tylergannon/gimble"
	"github.com/tylergannon/gimble/workflow"
)

func init() { gimble.RegisterGraph(Graph) }

// Graph is the shape of this workflow, read from the source of Review.
var Graph = workflow.Graph{
	Name:     "review",
	Source:   workflow.Source{File: "internal/workflows/review/review.go", Line: 26},
	Services: []workflow.Service{},
	Body: []workflow.Operation{
		workflow.Set{Source: workflow.Source{File: "internal/workflows/review/review.go", Line: 27}, Key: "goal"},
		workflow.Session{Source: workflow.Source{File: "internal/workflows/review/review.go", Line: 28}, Name: "code-review", From: ""},
		workflow.AgentCall{Source: workflow.Source{File: "internal/workflows/review/review.go", Line: 29}, Session: "code-review", Role: "code-review", Prompt: "Read the code in your working directory. Assess the goal given below. Report concrete correctness issues; return an empty findings list when there are none. Make no changes."},
		workflow.Set{Source: workflow.Source{File: "internal/workflows/review/review.go", Line: 33}, Key: "result"},
	},
}
