// Code generated by skgo. DO NOT EDIT.

package conversations

import (
	appstate "github.com/tylergannon/gimbal/internal/webapp"
	skgo "github.com/tylergannon/skgo"
)

// RouteParams stores converted values; only accessors record load dependencies.
type RouteParams struct {
	event        *skgo.Event
	valueProject string
}

func (p RouteParams) Project() string { skgo.TrackLoadParam(p.event, "project"); return p.valueProject }

type PageRequestEvent = skgo.RequestEvent[RouteParams, appstate.Locals]

func SkgoPageRequestEvent(event *skgo.Event) PageRequestEvent {
	return PageRequestEvent{Event: event, Locals: appstate.LocalsFrom(event.Request().Context()), Params: skgoRouteParams(event)}
}
func skgoRouteParams(event *skgo.Event) RouteParams {
	p := RouteParams{event: event}
	p.valueProject = skgo.LoadParamValue[string](event, "project")

	return p
}
func SkgoParamMatchers() map[string]skgo.ParamMatcher {
	return map[string]skgo.ParamMatcher{}
}

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_Load is Load, published as the server load of src/routes/projects/[project]/conversations/+page.server.ts.
	Skgo_Load = Load
)
