// Code generated by skgo. DO NOT EDIT.
import type { RequestEvent } from "@sveltejs/kit";
import type { ProjectChoice } from "../lib/skgo/host/types";

export const load = async (event: RequestEvent): Promise<{ projects: Array<ProjectChoice> }> => {
  throw new Error("skgo: implemented in Go");
};
