// Code generated by internal/generate. DO NOT EDIT.

package routes

import (
	"context"
	"strings"

	"github.com/tylergannon/gimbal"
	"github.com/tylergannon/gimbal/internal/workflows/implementation"
	"github.com/tylergannon/polytype"
	"github.com/tylergannon/skgo"
)

// StartImplementInput is the flat typed request for the implement workflow.
type StartImplementInput struct {
	ProjectDir                string                    `json:"project_dir"`
	WorkDir                   string                    `json:"work_dir"`
	Conversation              string                    `json:"conversation"`
	OutcomesFile              string                    `json:"outcomes_file"`
	MaxTasksPerOutcome        int                       `json:"max_tasks_per_outcome"`
	RoleSprintPlanning        polytype.Optional[string] `json:"role_sprint_planning,omitzero"`
	RoleArchitecturalCritique polytype.Optional[string] `json:"role_architectural_critique,omitzero"`
	RoleCoding                polytype.Optional[string] `json:"role_coding,omitzero"`
	RoleQaOrchestration       polytype.Optional[string] `json:"role_qa_orchestration,omitzero"`
}

func startImplement(ctx context.Context, in StartImplementInput) (StartAccepted, error) {
	if strings.TrimSpace(in.OutcomesFile) == "" {
		return StartAccepted{}, skgo.Invalidf("outcomes_file", "Give outcomes_file.")
	}
	if in.MaxTasksPerOutcome <= 0 {
		return StartAccepted{}, skgo.Invalidf("max_tasks_per_outcome", "Give a positive max_tasks_per_outcome.")
	}
	return startWorkflow(ctx, in.ProjectDir, in.WorkDir, in.Conversation, "implement",
		map[gimbal.WorkflowRole]polytype.Optional[string]{
			gimbal.WorkflowRole("sprint-planning"):        in.RoleSprintPlanning,
			gimbal.WorkflowRole("architectural-critique"): in.RoleArchitecturalCritique,
			gimbal.WorkflowRole("coding"):                 in.RoleCoding,
			gimbal.WorkflowRole("qa-orchestration"):       in.RoleQaOrchestration,
		}, func(runCtx context.Context, workDir string) error {
			return implementation.Implement(runCtx, gimbal.Env{WorkDir: workDir}, implementation.Params{
				OutcomesFile:       in.OutcomesFile,
				MaxTasksPerOutcome: in.MaxTasksPerOutcome,
			})
		})
}

var _ = skgo.Form(startImplement)
