// Code generated by internal/generate. DO NOT EDIT.

package routes

import (
	"context"
	"strings"

	"github.com/tylergannon/gimbal"
	"github.com/tylergannon/gimbal/internal/workflows/researchdocument"
	"github.com/tylergannon/polytype"
	"github.com/tylergannon/skgo"
)

// StartResearchDocumentInput is the flat typed request for the research-document workflow.
type StartResearchDocumentInput struct {
	ProjectDir              string                    `json:"project_dir"`
	WorkDir                 string                    `json:"work_dir"`
	Conversation            string                    `json:"conversation"`
	Goal                    string                    `json:"goal"`
	ResearchDir             string                    `json:"research_dir"`
	Output                  string                    `json:"output"`
	TokenBudget             int                       `json:"token_budget"`
	MinSourcesPerTopic      polytype.Optional[int]    `json:"min_sources_per_topic,omitzero"`
	MaxEditorialRounds      polytype.Optional[int]    `json:"max_editorial_rounds,omitzero"`
	RoleResearchPlanning    polytype.Optional[string] `json:"role_research_planning,omitzero"`
	RoleResearchIndexing    polytype.Optional[string] `json:"role_research_indexing,omitzero"`
	RoleDocumentSupervision polytype.Optional[string] `json:"role_document_supervision,omitzero"`
	RoleIndexCuration       polytype.Optional[string] `json:"role_index_curation,omitzero"`
	RoleDocumentAuthoring   polytype.Optional[string] `json:"role_document_authoring,omitzero"`
	RoleEditorialReview     polytype.Optional[string] `json:"role_editorial_review,omitzero"`
}

func startResearchDocument(ctx context.Context, in StartResearchDocumentInput) (StartAccepted, error) {
	if strings.TrimSpace(in.Goal) == "" {
		return StartAccepted{}, skgo.Invalidf("goal", "Give goal.")
	}
	if strings.TrimSpace(in.ResearchDir) == "" {
		return StartAccepted{}, skgo.Invalidf("research_dir", "Give research_dir.")
	}
	if strings.TrimSpace(in.Output) == "" {
		return StartAccepted{}, skgo.Invalidf("output", "Give output.")
	}
	if in.TokenBudget <= 0 {
		return StartAccepted{}, skgo.Invalidf("token_budget", "Give a positive token_budget.")
	}
	return startWorkflow(ctx, in.ProjectDir, in.WorkDir, in.Conversation, "research-document",
		map[gimbal.WorkflowRole]polytype.Optional[string]{
			gimbal.WorkflowRole("research-planning"):    in.RoleResearchPlanning,
			gimbal.WorkflowRole("research-indexing"):    in.RoleResearchIndexing,
			gimbal.WorkflowRole("document-supervision"): in.RoleDocumentSupervision,
			gimbal.WorkflowRole("index-curation"):       in.RoleIndexCuration,
			gimbal.WorkflowRole("document-authoring"):   in.RoleDocumentAuthoring,
			gimbal.WorkflowRole("editorial-review"):     in.RoleEditorialReview,
		}, func(runCtx context.Context, workDir string) error {
			return researchdocument.ResearchDocument(runCtx, gimbal.Env{WorkDir: workDir}, researchdocument.Params{
				Goal:               in.Goal,
				ResearchDir:        in.ResearchDir,
				Output:             in.Output,
				TokenBudget:        in.TokenBudget,
				MinSourcesPerTopic: in.MinSourcesPerTopic,
				MaxEditorialRounds: in.MaxEditorialRounds,
			})
		})
}

var _ = skgo.Form(startResearchDocument)
