// Code generated by skgo. DO NOT EDIT.

package routes

// The functions this package declares, published under names the generated
// bindings package can spell. Each is the function itself and not a wrapper:
// skgo.Refresh finds a query by the code pointer of the function it names.
var (
	// Skgo_guide is guide, published as src/routes/guide.remote.ts#guide.
	Skgo_guide = guide
	// Skgo_steer is steer, published as src/routes/steer.remote.ts#steer.
	Skgo_steer = steer
	// Skgo_steerLoop is steerLoop, published as src/routes/steer.remote.ts#steerLoop.
	Skgo_steerLoop = steerLoop
)

type (
	// SkgoArg_steer is the type steer takes.
	SkgoArg_steer = Steer
	// SkgoArg_steerLoop is the type steerLoop takes.
	SkgoArg_steerLoop = LoopMessage
)
