// Code generated by internal/generate. DO NOT EDIT.

package routes

import (
	"context"
	"strings"

	"github.com/tylergannon/gimbal"
	"github.com/tylergannon/gimbal/internal/workflows/validateproduct"
	"github.com/tylergannon/polytype"
	"github.com/tylergannon/skgo"
)

// StartValidateProductInput is the flat typed request for the validate-product workflow.
type StartValidateProductInput struct {
	ProjectDir              string                    `json:"project_dir"`
	WorkDir                 string                    `json:"work_dir"`
	Conversation            string                    `json:"conversation"`
	SuiteFile               string                    `json:"suite_file"`
	RoleProductOperation    polytype.Optional[string] `json:"role_product_operation,omitzero"`
	RoleProductVisualReview polytype.Optional[string] `json:"role_product_visual_review,omitzero"`
	RoleProductTriage       polytype.Optional[string] `json:"role_product_triage,omitzero"`
}

func startValidateProduct(ctx context.Context, in StartValidateProductInput) (StartAccepted, error) {
	if strings.TrimSpace(in.SuiteFile) == "" {
		return StartAccepted{}, skgo.Invalidf("suite_file", "Give suite_file.")
	}
	return startWorkflow(ctx, in.ProjectDir, in.WorkDir, in.Conversation, "validate-product",
		map[gimbal.WorkflowRole]polytype.Optional[string]{
			gimbal.WorkflowRole("product-operation"):     in.RoleProductOperation,
			gimbal.WorkflowRole("product-visual-review"): in.RoleProductVisualReview,
			gimbal.WorkflowRole("product-triage"):        in.RoleProductTriage,
		}, func(runCtx context.Context, workDir string) error {
			return validateproduct.ValidateProduct(runCtx, gimbal.Env{WorkDir: workDir}, validateproduct.Params{
				SuiteFile: in.SuiteFile,
			})
		})
}

var _ = skgo.Form(startValidateProduct)
