// Code generated by polytype. DO NOT EDIT.

/**
 * Graph is the shape of one workflow as its source writes it: the scopes, the sessions declared in them, the agent calls those sessions make, the commands, and the context each scope writes, in order. It describes a workflow before it runs.
 * It is not a model of the program. Ordinary Go calculation and error handling are absent. While a run is going the runtime records what actually happened, and a viewer shows the two together, so nothing the runtime already records belongs here: no adapter, model, or reasoning effort, which are a run's bindings; no results, timings, or costs.
 * A node carries no identifier. The runtime names every scope, session, and turn in one namespace of name.ordinal segments, so a node is addressed by its path of names from the root, which is a runtime key with the ordinal stripped from each segment. This graph's coder sits at round/sprint/task/coder and a run's at round.2/sprint.1/task.3/coder.1.
 */
export type Graph = {
  /**
   * Name is the workflow's name, which is also the run's name.
   */
  name: string;
  /**
   * Source anchors the entry function.
   */
  source: Source;
  /**
   * Services are the long-lived commands the root scope owns, in source order. They are declarations on the scope, not ordered operations.
   */
  services: Array<Service>;
  /**
   * Body is the entry function's operations, in source order.
   */
  body: Array<
    | (Omit<AgentCall, "kind"> & {
        kind: "agent_call";
      })
    | (Omit<Command, "kind"> & {
        kind: "command";
      })
    | (Omit<Condition, "kind"> & {
        kind: "condition";
      })
    | (Omit<Group, "kind"> & {
        kind: "group";
      })
    | (Omit<Interview, "kind"> & {
        kind: "interview";
      })
    | (Omit<Iterate, "kind"> & {
        kind: "iterate";
      })
    | (Omit<PromiseLoop, "kind"> & {
        kind: "promise_loop";
      })
    | (Omit<Repeat, "kind"> & {
        kind: "repeat";
      })
    | (Omit<Scope, "kind"> & {
        kind: "scope";
      })
    | (Omit<Session, "kind"> & {
        kind: "session";
      })
    | (Omit<Set, "kind"> & {
        kind: "set";
      })
  >;
  /**
   * Diagnostics records what the extractor could not read. A graph with diagnostics has honest holes; it is never completed by a guess.
   */
  diagnostics: Array<Diagnostic>;
};

/**
 * Source is where an operation is written, so a reader can go look at it.
 */
export type Source = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
};

/**
 * Service is one gimble.Service declaration. The containing Graph, Scope, Iterate, PromiseLoop task, or GroupChild owns its lifetime. It is not an ordered operation; the command line and runtime process are the run's record.
 */
export type Service = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
  name: string;
};

/**
 * AgentCall is one Session.Generate. Session is the name of the session that speaks, resolved outward to the nearest body declaring it, so two calls on one name are two steps on one conversation. Role is the role that session runs as: its own name for a NewSession, its ancestor's for a fork, so the coder's role is "researcher".
 */
export type AgentCall = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
  session: string;
  role: string;
  /**
   * Prompt is the constant the source passes (#230). The scope's context the run appends to it is the run's record.
   */
  prompt: string;
  /**
   * Supervisors watch this call. They are unordered and are not steps in the body. Their looks and steers are the run's record.
   */
  supervisors: Array<Supervisor>;
};

/**
 * Supervisor is one gimble.WithSupervisor on a call: a session watching the work and the constant it was told to watch for. Its own supervisors watch its look turns. How often it looks is a knob the run records, not shape.
 */
export type Supervisor = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
  session: string;
  role: string;
  instruction: string;
  supervisors: Array<Supervisor>;
};

/**
 * Command is one gimble.RunCommand or gimble.Check. Name is the constant name RunCommand gives it, or the constant context key Check gives it; the command line and its outcome are the run's record.
 */
export type Command = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
  name: string;
};

/**
 * Condition is an if/else chain or a switch, recorded when one of its branches contains an operation or exits. A branch guarding nothing but error handling is not shape and does not appear. Branch order is source order and is not an execution order. A Condition creates no Gimble scope.
 */
export type Condition = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
  branches: Array<Branch>;
};

/**
 * Branch is one alternative. Case is the condition or case as written; an empty Case is the else or default branch. Exits is set when the branch ends in break, continue, or return, so the operations after the Condition are what happens when no exiting branch is taken: the sprint commits only when the task passed, and stops its rounds when the validator has no findings.
 */
export type Branch = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
  case: string;
  exits: boolean;
  body: Array<
    | (Omit<AgentCall, "kind"> & {
        kind: "agent_call";
      })
    | (Omit<Command, "kind"> & {
        kind: "command";
      })
    | (Omit<Condition, "kind"> & {
        kind: "condition";
      })
    | (Omit<Group, "kind"> & {
        kind: "group";
      })
    | (Omit<Interview, "kind"> & {
        kind: "interview";
      })
    | (Omit<Iterate, "kind"> & {
        kind: "iterate";
      })
    | (Omit<PromiseLoop, "kind"> & {
        kind: "promise_loop";
      })
    | (Omit<Repeat, "kind"> & {
        kind: "repeat";
      })
    | (Omit<Scope, "kind"> & {
        kind: "scope";
      })
    | (Omit<Session, "kind"> & {
        kind: "session";
      })
    | (Omit<Set, "kind"> & {
        kind: "set";
      })
  >;
};

/**
 * Group is a gimble.Group call. Its children run concurrently; their order is source order and implies nothing about the order they finish in.
 */
export type Group = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
  name: string;
  children: Array<GroupChild>;
};

/**
 * GroupChild is one Group.Go call: a named body in its own scope.
 */
export type GroupChild = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
  name: string;
  services: Array<Service>;
  body: Array<
    | (Omit<AgentCall, "kind"> & {
        kind: "agent_call";
      })
    | (Omit<Command, "kind"> & {
        kind: "command";
      })
    | (Omit<Condition, "kind"> & {
        kind: "condition";
      })
    | (Omit<Group, "kind"> & {
        kind: "group";
      })
    | (Omit<Interview, "kind"> & {
        kind: "interview";
      })
    | (Omit<Iterate, "kind"> & {
        kind: "iterate";
      })
    | (Omit<PromiseLoop, "kind"> & {
        kind: "promise_loop";
      })
    | (Omit<Repeat, "kind"> & {
        kind: "repeat";
      })
    | (Omit<Scope, "kind"> & {
        kind: "scope";
      })
    | (Omit<Session, "kind"> & {
        kind: "session";
      })
    | (Omit<Set, "kind"> & {
        kind: "set";
      })
  >;
};

/**
 * Interview is one gimble.Interview. Session is the conversation conducting it; its questions, answers, and internal turns are runtime facts.
 */
export type Interview = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
  name: string;
  session: string;
};

/**
 * Iterate ranges over a collection supplied by ordinary Go. Each item runs in a fresh child scope named Name. The collection's values and length are runtime data, so the graph records only the scoped body.
 */
export type Iterate = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
  name: string;
  services: Array<Service>;
  body: Array<
    | (Omit<AgentCall, "kind"> & {
        kind: "agent_call";
      })
    | (Omit<Command, "kind"> & {
        kind: "command";
      })
    | (Omit<Condition, "kind"> & {
        kind: "condition";
      })
    | (Omit<Group, "kind"> & {
        kind: "group";
      })
    | (Omit<Interview, "kind"> & {
        kind: "interview";
      })
    | (Omit<Iterate, "kind"> & {
        kind: "iterate";
      })
    | (Omit<PromiseLoop, "kind"> & {
        kind: "promise_loop";
      })
    | (Omit<Repeat, "kind"> & {
        kind: "repeat";
      })
    | (Omit<Scope, "kind"> & {
        kind: "scope";
      })
    | (Omit<Session, "kind"> & {
        kind: "session";
      })
    | (Omit<Set, "kind"> & {
        kind: "set";
      })
  >;
};

/**
 * PromiseLoop is planner-directed dispatch. Planner names the planner session; Supervisors watch each planning decision. Body runs under a child scope named "task", where the runtime writes key "task". How many tasks there will be is the planner's decision.
 */
export type PromiseLoop = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
  name: string;
  planner: string;
  supervisors: Array<Supervisor>;
  /**
   * Services belong to each task scope described by Body.
   */
  services: Array<Service>;
  body: Array<
    | (Omit<AgentCall, "kind"> & {
        kind: "agent_call";
      })
    | (Omit<Command, "kind"> & {
        kind: "command";
      })
    | (Omit<Condition, "kind"> & {
        kind: "condition";
      })
    | (Omit<Group, "kind"> & {
        kind: "group";
      })
    | (Omit<Interview, "kind"> & {
        kind: "interview";
      })
    | (Omit<Iterate, "kind"> & {
        kind: "iterate";
      })
    | (Omit<PromiseLoop, "kind"> & {
        kind: "promise_loop";
      })
    | (Omit<Repeat, "kind"> & {
        kind: "repeat";
      })
    | (Omit<Scope, "kind"> & {
        kind: "scope";
      })
    | (Omit<Session, "kind"> & {
        kind: "session";
      })
    | (Omit<Set, "kind"> & {
        kind: "set";
      })
  >;
};

/**
 * Repeat is a Go for or range statement whose body contains an operation, such as the sprint's rounds. Cond is the loop header as written. It creates no Gimble scope; how many times it runs is the run's record.
 */
export type Repeat = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
  cond: string;
  body: Array<
    | (Omit<AgentCall, "kind"> & {
        kind: "agent_call";
      })
    | (Omit<Command, "kind"> & {
        kind: "command";
      })
    | (Omit<Condition, "kind"> & {
        kind: "condition";
      })
    | (Omit<Group, "kind"> & {
        kind: "group";
      })
    | (Omit<Interview, "kind"> & {
        kind: "interview";
      })
    | (Omit<Iterate, "kind"> & {
        kind: "iterate";
      })
    | (Omit<PromiseLoop, "kind"> & {
        kind: "promise_loop";
      })
    | (Omit<Repeat, "kind"> & {
        kind: "repeat";
      })
    | (Omit<Scope, "kind"> & {
        kind: "scope";
      })
    | (Omit<Session, "kind"> & {
        kind: "session";
      })
    | (Omit<Set, "kind"> & {
        kind: "set";
      })
  >;
};

/**
 * Scope is a gimble.Scope call: a named body that owns the sessions declared in it and holds the values set in it.
 */
export type Scope = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
  name: string;
  services: Array<Service>;
  body: Array<
    | (Omit<AgentCall, "kind"> & {
        kind: "agent_call";
      })
    | (Omit<Command, "kind"> & {
        kind: "command";
      })
    | (Omit<Condition, "kind"> & {
        kind: "condition";
      })
    | (Omit<Group, "kind"> & {
        kind: "group";
      })
    | (Omit<Interview, "kind"> & {
        kind: "interview";
      })
    | (Omit<Iterate, "kind"> & {
        kind: "iterate";
      })
    | (Omit<PromiseLoop, "kind"> & {
        kind: "promise_loop";
      })
    | (Omit<Repeat, "kind"> & {
        kind: "repeat";
      })
    | (Omit<Scope, "kind"> & {
        kind: "scope";
      })
    | (Omit<Session, "kind"> & {
        kind: "session";
      })
    | (Omit<Set, "kind"> & {
        kind: "set";
      })
  >;
};

/**
 * Session is one gimble.NewSession or Session.Fork, standing where the source creates it: the body containing it is the scope that owns the conversation, which is how the runtime names it too. Name is the role for NewSession and the fork's name for Fork. From is the name of the session this one forks, empty for NewSession. What it runs on is a run's binding and is not here.
 */
export type Session = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
  name: string;
  from: string;
};

/**
 * Set is one gimble.Set or SetJSON: a key written into the containing scope. The order of these in a body is the order an agent reads them back. The value written is the run's, not the source's.
 */
export type Set = {
  /**
   * File is the path relative to the module root, with forward slashes.
   */
  file: string;
  line: number;
  key: string;
};

/**
 * Diagnostic is one thing the extractor could not read.
 */
export type Diagnostic = {
  source: Source;
  message: string;
};
