// Package temporalgen implements the bounded experimental Temporal target.
// It reads typed authored Go independently of visualization graph extraction.
package temporalgen

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/constant"
	"go/format"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"

	"golang.org/x/tools/go/packages"
	"golang.org/x/tools/go/types/typeutil"
	"golang.org/x/tools/imports"
)

const gimbalPath = "github.com/tylergannon/gimbal"

// Source replaces output with the complete target for entry. A rejected input
// replaces old output with a compile error, so it cannot masquerade as current.
func Source(dir, entry, name, output string) (err error) {
	defer func() {
		if err != nil {
			invalid := "// Code generation failed: " + strings.ReplaceAll(err.Error(), "\n", "\n// ") + "\npackage main\nvar _ = temporalGenerationFailed\n"
			if e := os.WriteFile(output, []byte(invalid), 0644); e != nil {
				err = fmt.Errorf("%w; invalidating output: %v", err, e)
			}
		}
	}()
	pkgs, err := packages.Load(&packages.Config{Dir: dir, Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles | packages.NeedSyntax | packages.NeedTypes | packages.NeedTypesInfo | packages.NeedImports | packages.NeedDeps}, ".")
	if err != nil {
		return err
	}
	if len(pkgs) != 1 {
		return fmt.Errorf("expected one input package")
	}
	p := pkgs[0]
	if len(p.Errors) > 0 {
		return fmt.Errorf("%s", p.Errors[0])
	}
	var fn *ast.FuncDecl
	for _, f := range p.Syntax {
		for _, d := range f.Decls {
			if v, ok := d.(*ast.FuncDecl); ok && v.Name.Name == entry {
				fn = v
			}
		}
	}
	if fn == nil {
		return fmt.Errorf("%s: entry %s not found", dir, entry)
	}
	e := &emitter{pkg: p, entry: entry, imports: map[string]string{}, names: map[types.Object]string{}, loops: map[types.Object]*loop{}, counts: map[string]int{}}
	// A finite surface is deliberate: only the existing (context, Env) -> error entry.
	sig := p.TypesInfo.Defs[fn.Name].Type().(*types.Signature)
	if sig.TypeParams().Len() != 0 || sig.Params().Len() != 2 || types.TypeString(sig.Params().At(0).Type(), nil) != "context.Context" || types.TypeString(sig.Params().At(1).Type(), nil) != gimbalPath+".Env" || sig.Results().Len() != 1 || sig.Results().At(0).Type() != types.Universe.Lookup("error").Type() {
		return e.fail(fn, "entry must have signature (context.Context, gimbal.Env) error")
	}
	e.env = sig.Params().At(1)
	// Context is a lexical scope token, never an ordinary replayed value.
	e.addImport("context", "context")
	e.addImport("errors", "errors")
	e.addImport("fmt", "fmt")
	e.addImport("time", "time")
	e.addImport(gimbalPath, "gimbal")
	e.addImport(gimbalPath+"/internal/compiledscope", "compiledscope")
	e.addImport("go.temporal.io/sdk/workflow", "workflow")
	e.addImport("go.temporal.io/sdk/temporal", "temporal")
	s := scope{id: `""`, snapshot: "root", ctx: sig.Params().At(0)}
	e.line("func %sWorkflow(ctx workflow.Context, in Input) (retErr error) {", entry)
	e.b.WriteString(strings.ReplaceAll(workflowStart, "$NAME", strconv.Quote(name)))
	if err = e.block(fn.Body, s); err != nil {
		return err
	}
	e.line("}")
	e.line("func register%s(reg interface{RegisterWorkflow(any)}) {reg.RegisterWorkflow(%sWorkflow)}", entry, entry)
	for _, l := range e.loops {
		if !l.ranged {
			return e.fail(fn, "PromiseLoop must be iterated once")
		}
	}
	var source bytes.Buffer
	source.WriteString("// Code generated by internal/temporalgen. DO NOT EDIT.\npackage main\nimport (\n")
	paths := make([]string, 0, len(e.imports))
	for path := range e.imports {
		paths = append(paths, path)
	}
	sort.Strings(paths)
	for _, path := range paths {
		fmt.Fprintf(&source, "%s %q\n", e.imports[path], path)
	}
	source.WriteString(")\n")
	source.Write(e.b.Bytes())
	source.Write(e.activities.Bytes())
	// imports.Process only removes unused imports; all names were type-resolved.
	formatted, err := format.Source(source.Bytes())
	if err != nil {
		return fmt.Errorf("emitting %s: %w", entry, err)
	}
	formatted, err = imports.Process(output, formatted, &imports.Options{Comments: true})
	if err != nil {
		return err
	}
	return os.WriteFile(output, formatted, 0644)
}

type scope struct {
	id, snapshot, keys, task string
	ctx                      types.Object
}
type loop struct {
	id, goal, session, snapshot, err, name, open string
	ranged                                       bool
}
type emitter struct {
	pkg           *packages.Package
	entry         string
	env           types.Object
	b, activities bytes.Buffer
	imports       map[string]string
	names         map[types.Object]string
	loops         map[types.Object]*loop
	counts        map[string]int
	serial        int
}

func (e *emitter) fail(n ast.Node, msg string) error {
	return fmt.Errorf("%s: %s", e.pkg.Fset.Position(n.Pos()), msg)
}
func (e *emitter) line(f string, a ...any) { fmt.Fprintf(&e.b, f+"\n", a...) }
func (e *emitter) fresh() string           { e.serial++; return fmt.Sprintf("v%d", e.serial) }
func (e *emitter) addImport(path, name string) string {
	if n := e.imports[path]; n != "" {
		return n
	}
	for _, n := range e.imports {
		if n == name {
			name = "pkg" + strconv.Itoa(len(e.imports))
			break
		}
	}
	e.imports[path] = name
	return name
}
func (e *emitter) typ(t types.Type) string {
	return types.TypeString(t, func(p *types.Package) string { return e.addImport(p.Path(), p.Name()) })
}
func (e *emitter) obj(x ast.Expr) types.Object {
	if id, ok := x.(*ast.Ident); ok {
		return e.pkg.TypesInfo.ObjectOf(id)
	}
	return nil
}
func (e *emitter) local(id *ast.Ident) string {
	if id.Name == "_" {
		return "_"
	}
	o := e.pkg.TypesInfo.ObjectOf(id)
	if n := e.names[o]; n != "" {
		return n
	}
	n := id.Name + e.fresh()
	e.names[o] = n
	return n
}
func (e *emitter) callName(c *ast.CallExpr) string {
	f := typeutil.Callee(e.pkg.TypesInfo, c)
	if f != nil && f.Pkg() != nil && f.Pkg().Path() == gimbalPath {
		return f.Name()
	}
	return ""
}
func receiver(c *ast.CallExpr) ast.Expr {
	f := c.Fun
	if i, ok := f.(*ast.IndexExpr); ok {
		f = i.X
	}
	if s, ok := f.(*ast.SelectorExpr); ok {
		return s.X
	}
	return nil
}
func (e *emitter) expr(x ast.Expr) (string, error) {
	if x == nil {
		return "", nil
	}
	switch v := x.(type) {
	case *ast.Ident:
		o := e.pkg.TypesInfo.ObjectOf(v)
		if n := e.names[o]; n != "" {
			return n, nil
		}
		if c, ok := o.(*types.Const); ok {
			return e.constant(v, c)
		}
		if p, ok := o.(*types.PkgName); ok {
			return e.addImport(p.Imported().Path(), p.Imported().Name()), nil
		}
		if t, ok := o.(*types.TypeName); ok {
			return e.typ(t.Type()), nil
		}
		if o == nil || o.Parent() == types.Universe {
			return v.Name, nil
		}
		return "", e.fail(v, "unsupported capture or package variable: "+v.Name)
	case *ast.BasicLit:
		return v.Value, nil
	case *ast.SelectorExpr:
		if selection := e.pkg.TypesInfo.Selections[v]; selection != nil && !selection.Obj().Exported() {
			return "", e.fail(v, "selected fields must be exported from the authored package")
		}
		if e.obj(v.X) == e.env {
			if v.Sel.Name == "WorkDir" {
				return "workdir", nil
			}
			return "", e.fail(v, "only Env.WorkDir is supported")
		}
		if o := e.pkg.TypesInfo.Uses[v.Sel]; o != nil {
			if c, ok := o.(*types.Const); ok {
				return e.constant(v, c)
			}
		}
		if _, ok := e.obj(v.X).(*types.PkgName); ok {
			return "", e.fail(v, "unsupported imported package value: "+v.Sel.Name)
		}
		left, err := e.expr(v.X)
		return left + "." + v.Sel.Name, err
	case *ast.BinaryExpr:
		a, err := e.expr(v.X)
		if err != nil {
			return "", err
		}
		b, err := e.expr(v.Y)
		return "(" + a + " " + v.Op.String() + " " + b + ")", err
	case *ast.UnaryExpr:
		if v.Op != token.NOT && v.Op != token.SUB && v.Op != token.ADD {
			return "", e.fail(v, "unsupported pointer or channel expression")
		}
		a, err := e.expr(v.X)
		return v.Op.String() + a, err
	case *ast.ParenExpr:
		a, err := e.expr(v.X)
		return "(" + a + ")", err
	case *ast.CompositeLit:
		if named, ok := e.pkg.TypesInfo.TypeOf(v).(*types.Named); ok && !named.Obj().Exported() {
			return "", e.fail(v, "value types must be exported from the authored package")
		}
		t := e.typ(e.pkg.TypesInfo.TypeOf(v))
		var fields []string
		for i, el := range v.Elts {
			if kv, ok := el.(*ast.KeyValueExpr); ok {
				key, ok := kv.Key.(*ast.Ident)
				if !ok {
					return "", e.fail(kv, "only struct field keys supported")
				}
				if field := e.pkg.TypesInfo.Uses[key]; field != nil && !field.Exported() {
					return "", e.fail(key, "literal fields must be exported from the authored package")
				}
				val, err := e.expr(kv.Value)
				if err != nil {
					return "", err
				}
				fields = append(fields, key.Name+":"+val)
			} else {
				val, err := e.expr(el)
				if err != nil {
					return "", err
				}
				if st, ok := e.pkg.TypesInfo.TypeOf(v).Underlying().(*types.Struct); ok {
					if !st.Field(i).Exported() {
						return "", e.fail(v, "result fields must be exported")
					}
					val = st.Field(i).Name() + ":" + val
				}
				fields = append(fields, val)
			}
		}
		return t + "{" + strings.Join(fields, ",") + "}", nil
	case *ast.CallExpr:
		if v.Ellipsis.IsValid() {
			return "", e.fail(v, "variadic helper expansion is unsupported")
		}
		if e.callName(v) == "Err" {
			if l := e.loops[e.obj(receiver(v))]; l != nil {
				return l.err, nil
			}
		}
		f := typeutil.Callee(e.pkg.TypesInfo, v)
		if f == nil || f.Pkg() == nil || f.Pkg().Path() != "fmt" || f.Name() != "Errorf" {
			return "", e.fail(v, "unsupported helper/effect in workflow expression; only fmt.Errorf is admitted")
		}
		for _, arg := range v.Args {
			if err := e.valueMethods(arg, "format"); err != nil {
				return "", err
			}
		}
		args, err := e.args(v.Args)
		return "fmt.Errorf(" + strings.Join(args, ",") + ")", err
	}
	return "", e.fail(x, fmt.Sprintf("unsupported expression %T", x))
}
func (e *emitter) constant(n ast.Node, c *types.Const) (string, error) {
	if c.Val().Kind() != constant.String && c.Val().Kind() != constant.Int && c.Val().Kind() != constant.Bool {
		return "", e.fail(n, "only string, integer and boolean constants supported")
	}
	value := c.Val().ExactString()
	if b, ok := c.Type().(*types.Basic); ok && b.Info()&types.IsUntyped != 0 {
		return value, nil
	}
	return e.typ(c.Type()) + "(" + value + ")", nil
}

// Formatting and JSON encoding can invoke user methods without an explicit
// call expression. Do not smuggle those effects into replayed orchestration.
func (e *emitter) valueMethods(n ast.Expr, mode string) error {
	seen := map[types.Type]bool{}
	var visit func(types.Type) error
	visit = func(t types.Type) error {
		if t == nil || seen[t] {
			return nil
		}
		seen[t] = true
		if types.TypeString(t, nil) == "context.Context" {
			return e.fail(n, "context values are supported only as lexical operation arguments")
		}
		methodSets := []*types.MethodSet{types.NewMethodSet(t)}
		if mode == "json" {
			methodSets = append(methodSets, types.NewMethodSet(types.NewPointer(t)))
		}
		for _, methods := range methodSets {
			for method := range methods.Methods() {
				m := method.Obj()
				dangerous := mode == "json" && (m.Name() == "MarshalJSON" || m.Name() == "MarshalText" || m.Name() == "IsZero") || mode == "format" && (m.Name() == "String" || m.Name() == "Format" || m.Name() == "Error")
				// The operation error interface contains target-owned classified errors.
				if _, ok := t.Underlying().(*types.Interface); ok && types.Identical(t, types.Universe.Lookup("error").Type()) {
					continue
				}
				// time.Duration's standard scalar formatter is deterministic.
				if m.Pkg() != nil && m.Pkg().Path() == "time" && types.TypeString(t, nil) == "time.Duration" {
					continue
				}
				if dangerous {
					return e.fail(n, "unsupported implicit "+mode+" method: "+m.Name())
				}
			}
		}
		switch u := t.Underlying().(type) {
		case *types.Tuple:
			for v := range u.Variables() {
				if err := visit(v.Type()); err != nil {
					return err
				}
			}
		case *types.Interface:
			if !types.Identical(t, types.Universe.Lookup("error").Type()) {
				return e.fail(n, "opaque interface values cannot be checked for implicit "+mode+" effects")
			}
		case *types.Map:
			if err := visit(u.Key()); err != nil {
				return err
			}
			return visit(u.Elem())
		case *types.Struct:
			for field := range u.Fields() {
				if err := visit(field.Type()); err != nil {
					return err
				}
			}
		case *types.Pointer:
			return visit(u.Elem())
		case *types.Slice:
			return visit(u.Elem())
		case *types.Array:
			return visit(u.Elem())
		}
		return nil
	}
	return visit(e.pkg.TypesInfo.TypeOf(n))
}

func (e *emitter) args(xs []ast.Expr) ([]string, error) {
	out := make([]string, len(xs))
	for i, x := range xs {
		v, err := e.expr(x)
		if err != nil {
			return nil, err
		}
		out[i] = v
	}
	return out, nil
}
func (e *emitter) input(s scope, session string) string {
	if session == "" {
		session = "sessionHandle{}"
	}
	return fmt.Sprintf("operationInput{Scope:%s, Context:%s, Session:%s}", s.id, s.snapshot, session)
}
func (e *emitter) exitTask(s scope, err string) {
	if s.task != "" {
		e.line("%s = errors.Join(%s, workflow.ExecuteActivity(cleanupContext(ops), \"ExitScope\", %s, \"\").Get(cleanupContext(ops), nil))", err, err, s.task)
	}
}
func (e *emitter) abort(s scope, err string) { e.exitTask(s, err); e.line("return %s", err) }
func (e *emitter) activity(s scope, name string, args []string, dest string) {
	v := e.fresh()
	a := ""
	if len(args) > 0 {
		a = ", " + strings.Join(args, ", ")
	}
	if dest == "" {
		dest = "nil"
	} else {
		dest = "&" + dest
	}
	e.line("if %s := workflow.ExecuteActivity(ops, %q%s).Get(wait, %s); %s != nil {", v, name, a, dest, v)
	e.abort(s, v)
	e.line("}")
}
func (e *emitter) block(b *ast.BlockStmt, s scope) error {
	for _, st := range b.List {
		if err := e.stmt(st, s); err != nil {
			return err
		}
	}
	return nil
}
func (e *emitter) stmt(st ast.Stmt, s scope) error {
	switch v := st.(type) {
	case *ast.AssignStmt:
		if len(v.Rhs) == 1 {
			if c, ok := v.Rhs[0].(*ast.CallExpr); ok && e.callName(c) != "" && e.callName(c) != "Err" {
				return e.operation(v, c, s)
			}
		}
		left := make([]string, len(v.Lhs))
		for i, x := range v.Lhs {
			if id, ok := x.(*ast.Ident); ok {
				left[i] = e.local(id)
			} else {
				val, err := e.expr(x)
				if err != nil {
					return err
				}
				left[i] = val
			}
		}
		right, err := e.args(v.Rhs)
		if err != nil {
			return err
		}
		e.line("%s %s %s", strings.Join(left, ","), v.Tok, strings.Join(right, ","))
		return nil
	case *ast.ExprStmt:
		c, ok := v.X.(*ast.CallExpr)
		if !ok {
			return e.fail(v, "only Gimbal operations supported as statements")
		}
		return e.operation(nil, c, s)
	case *ast.IfStmt:
		e.line("{")
		if v.Init != nil {
			if err := e.stmt(v.Init, s); err != nil {
				return err
			}
		}
		cond, err := e.expr(v.Cond)
		if err != nil {
			return err
		}
		e.line("if %s {", cond)
		if err = e.block(v.Body, s); err != nil {
			return err
		}
		e.line("}")
		if v.Else != nil { // keep else adjacent to its closing brace
			e.b.Truncate(e.b.Len() - 1)
			e.line(" else {")
			if err = e.stmt(v.Else, s); err != nil {
				return err
			}
			e.line("}")
		}
		e.line("}")
		return nil
	case *ast.BlockStmt:
		e.line("{")
		err := e.block(v, s)
		e.line("}")
		return err
	case *ast.ReturnStmt:
		if len(v.Results) != 1 {
			return e.fail(v, "only explicit error returns supported")
		}
		r, err := e.expr(v.Results[0])
		if err != nil {
			return err
		}
		tmp := e.fresh()
		e.line("var %s error = %s", tmp, r)
		e.abort(s, tmp)
		return nil
	case *ast.RangeStmt:
		return e.taskRange(v, s)
	default:
		return e.fail(st, fmt.Sprintf("unsupported statement %T; no lowering is defined", st))
	}
}
func (e *emitter) bind(a *ast.AssignStmt, values []string) error {
	if a == nil {
		return nil
	}
	if len(a.Lhs) != len(values) {
		return e.fail(a, "operation result arity mismatch")
	}
	var lhs []string
	for _, x := range a.Lhs {
		id, ok := x.(*ast.Ident)
		if !ok {
			return e.fail(x, "operation assignment requires local identifiers")
		}
		lhs = append(lhs, e.local(id))
	}
	e.line("%s %s %s", strings.Join(lhs, ","), a.Tok, strings.Join(values, ","))
	return nil
}
func (e *emitter) site(kind string) string {
	e.counts[kind]++
	return e.entry + kind + strconv.Itoa(e.counts[kind])
}
func (e *emitter) operation(a *ast.AssignStmt, c *ast.CallExpr, s scope) error {
	kind := e.callName(c)
	if kind == "" {
		return e.fail(c, "unsupported helper/effect; no Gimbal operation lowering")
	}
	pos := e.pkg.Fset.Position(c.Pos())
	e.line("// %s:%d: %s", filepath.Base(pos.Filename), pos.Line, kind)
	if len(c.Args) == 0 || e.obj(c.Args[0]) != s.ctx {
		return e.fail(c, "operation must use the current lexical scope context")
	}
	if c.Ellipsis.IsValid() {
		return e.fail(c, "variadic expansion is unsupported")
	}
	switch kind {
	case "Set", "SetJSON":
		if len(c.Args) != 3 {
			return e.fail(c, "unsupported context write")
		}
		if err := e.valueMethods(c.Args[2], "json"); err != nil {
			return err
		}
		args, err := e.args(c.Args[1:])
		if err != nil {
			return err
		}
		key := e.fresh()
		e.line("%s := %s", key, args[0])
		e.activity(s, "SetValue", []string{s.id, s.snapshot, "contextEntry(" + key + "," + args[1] + ")"}, s.snapshot)
		if s.keys != "" {
			e.line("%s = append(%s, %s)", s.keys, s.keys, key)
		}
		return nil
	case "NewSession":
		if len(c.Args) != 3 {
			return e.fail(c, "NewSession options unsupported")
		}
		args, err := e.args(c.Args[1:])
		if err != nil {
			return err
		}
		id := e.site("Session")
		result := e.fresh()
		e.line("var %s sessionHandle", result)
		e.activity(s, "OpenSession", []string{s.id, strconv.Quote(id), "gimbal.WorkflowRole(" + args[0] + ")", args[1]}, result)
		return e.bind(a, []string{result})
	case "Generate":
		if err := e.valueMethods(c, "json"); err != nil {
			return err
		}
		if len(c.Args) != 2 {
			return e.fail(c, "Generate options unsupported")
		}
		session, err := e.expr(receiver(c))
		if err != nil {
			return err
		}
		promptValue := e.pkg.TypesInfo.Types[c.Args[1]].Value
		if promptValue == nil || promptValue.Kind() != constant.String {
			return e.fail(c.Args[1], "Generate prompt must be a compile-time string constant")
		}
		prompt := strconv.Quote(constant.StringVal(promptValue))
		tuple, ok := e.pkg.TypesInfo.TypeOf(c).(*types.Tuple)
		if !ok {
			return e.fail(c, "expected typed Generate results")
		}
		if named, ok := tuple.At(0).Type().(*types.Named); ok && !named.Obj().Exported() {
			return e.fail(c, "Generate result type must be exported")
		}
		typ := e.typ(tuple.At(0).Type())
		name := e.site("Generate")
		fmt.Fprintf(&e.activities, `func(a *Activities) %s(ctx context.Context, in operationInput) (operationResult[%s], error) {
 scoped, session, release, err := a.turnInput(ctx,in)
 if err != nil { return operationResult[%s]{},err }; defer release()
 value, err := session.Generate[%s](scoped,%s)
 return operationResult[%s]{value,failure(err)},nil
 }
`, name, typ, typ, typ, prompt, typ)
		result := e.fresh()
		e.line("var %s operationResult[%s]", result, typ)
		e.activity(s, name, []string{e.input(s, session)}, result)
		return e.bind(a, []string{result + ".Value", result + ".Err()"})
	case "Fork":
		if len(c.Args) != 2 {
			return e.fail(c, "Fork options unsupported")
		}
		session, err := e.expr(receiver(c))
		if err != nil {
			return err
		}
		name, err := e.expr(c.Args[1])
		if err != nil {
			return err
		}
		result := e.fresh()
		e.line("var %s operationResult[sessionHandle]", result)
		e.activity(s, "OpenFork", []string{e.input(s, session), name}, result)
		return e.bind(a, []string{result + ".Value", result + ".Err()"})
	case "RunCommand", "Check":
		if len(c.Args) < 4 {
			return e.fail(c, "command arguments missing")
		}
		args, err := e.args(c.Args[1:])
		if err != nil {
			return err
		}
		name := e.site(kind)
		result := e.fresh()
		typ, helper := "commandResult", "commandAt"
		if kind == "Check" {
			typ, helper = "checkResult", "checkAt"
		}
		fmt.Fprintf(&e.activities, `func(a *Activities) %s(ctx context.Context, in operationInput, name, dir, command string, args []string) (%s,error) { return a.%s(ctx,in,name,dir,command,args...) }
`, name, typ, helper)
		key := e.fresh()
		e.line("%s := %s", key, args[0])
		argv := "[]string{" + strings.Join(args[3:], ",") + "}"
		e.line("var %s %s", result, typ)
		e.activity(s, name, []string{e.input(s, ""), key, args[1], args[2], argv}, result)
		if kind == "Check" {
			e.line("%s = %s.Context", s.snapshot, result)
			if s.keys != "" {
				e.line("%s = append(%s,%s)", s.keys, s.keys, key)
			}
			return e.bind(a, []string{result + ".Err()"})
		}
		return e.bind(a, []string{result + ".ExitCode", result + ".Stdout", result + ".Stderr", result + ".Err()"})
	case "Scope":
		return e.scopeCall(a, c, s)
	case "PromiseLoop":
		return e.loopCall(a, c, s)
	default:
		return e.fail(c, "unsupported Gimbal operation: "+kind)
	}
}
func (e *emitter) scopeName(x ast.Expr) (string, error) {
	v := e.pkg.TypesInfo.Types[x].Value
	if v == nil || v.Kind() != constant.String {
		return "", e.fail(x, "scope name must be constant")
	}
	return constant.StringVal(v), nil
}
func (e *emitter) scopeCall(a *ast.AssignStmt, c *ast.CallExpr, s scope) error {
	if len(c.Args) != 3 {
		return e.fail(c, "unsupported Scope arguments")
	}
	body, ok := c.Args[2].(*ast.FuncLit)
	if !ok {
		return e.fail(c, "Scope needs an inline callback")
	}
	if len(body.Type.Params.List) != 1 || len(body.Type.Params.List[0].Names) != 1 {
		return e.fail(body, "Scope callback must name its context parameter")
	}
	name, err := e.scopeName(c.Args[1])
	if err != nil {
		return err
	}
	result, id, snap := e.fresh(), e.fresh(), e.fresh()
	e.line("%s := func() (scopeErr error) {", result)
	e.line("%s := nextScope(%s,%q)", id, s.id, name)
	e.line(`defer func(){ cleanup:=cleanupContext(ops); scopeErr=errors.Join(scopeErr,workflow.ExecuteActivity(cleanup,"ExitScope",%s,errorText(scopeErr)).Get(cleanup,nil)) }()`, id)
	child := scope{id: id, snapshot: snap, ctx: e.pkg.TypesInfo.Defs[body.Type.Params.List[0].Names[0]]}
	e.activity(child, "EnterScope", []string{"ScopeInput{" + id + "," + s.id + "," + strconv.Quote(name) + "}"}, "")
	e.line("%s := %s", snap, s.snapshot)
	e.line("_ = %s", snap)
	if err = e.block(body.Body, child); err != nil {
		return err
	}
	e.line("}()")
	if a == nil {
		e.line("_ = %s", result)
	}
	return e.bind(a, []string{result})
}
func (e *emitter) loopCall(a *ast.AssignStmt, c *ast.CallExpr, s scope) error {
	if a == nil || a.Tok != token.DEFINE || len(a.Lhs) != 1 || len(c.Args) != 4 {
		return e.fail(c, "only a directly bound PromiseLoop without options is supported")
	}
	name, err := e.scopeName(c.Args[1])
	if err != nil {
		return err
	}
	goal, err := e.expr(c.Args[2])
	if err != nil {
		return err
	}
	session, err := e.expr(c.Args[3])
	if err != nil {
		return err
	}
	if s.id != `""` {
		return e.fail(c, "PromiseLoop is supported only at entry scope")
	}
	l := &loop{id: e.fresh(), goal: e.fresh(), session: e.fresh(), snapshot: s.snapshot, err: e.fresh(), name: name, open: e.fresh()}
	e.loops[e.obj(a.Lhs[0])] = l
	e.line("%s := %s", l.goal, goal)
	e.line("%s := %s", l.session, session)
	e.line("var %s error", l.err)
	return nil
}
func (e *emitter) taskRange(v *ast.RangeStmt, s scope) error {
	sel, ok := v.X.(*ast.SelectorExpr)
	if !ok || sel.Sel.Name != "Tasks" {
		return e.fail(v, "only PromiseLoop.Tasks range supported")
	}
	l := e.loops[e.obj(sel.X)]
	if l == nil || l.ranged {
		return e.fail(v, "Tasks must refer to one directly bound, singly iterated PromiseLoop")
	}
	l.ranged = true
	if s.id != `""` {
		return e.fail(v, "PromiseLoop iteration is supported only at entry scope")
	}
	key, ok := v.Key.(*ast.Ident)
	if !ok || v.Tok != token.DEFINE {
		return e.fail(v, "Tasks needs a declared context range variable")
	}
	e.line("%s := nextScope(%s,%q)", l.id, s.id, l.name)
	e.activity(s, "EnterLoopScope", []string{"ScopeInput{" + l.id + "," + s.id + "," + strconv.Quote(l.name) + "}"}, "")
	e.line("%s := true", l.open)
	e.line(`defer func(){if %s {cleanup:=cleanupContext(ops);retErr=errors.Join(retErr,workflow.ExecuteActivity(cleanup,"ExitScope",%s,errorText(%s)).Get(cleanup,nil))}}()`, l.open, l.id, l.err)
	if v.Value != nil {
		id, ok := v.Value.(*ast.Ident)
		if !ok || id.Name != "_" {
			return e.fail(v, "named task range value not supported yet")
		}
	}
	tasks, feedback, plan, id, snap, keys := e.fresh(), e.fresh(), e.fresh(), e.fresh(), e.fresh(), e.fresh()
	e.line("%s := []gimbal.Task{}", tasks)
	e.line("%s := \"\"", feedback)
	e.line("for {")
	name := e.site("Plan")
	fmt.Fprintf(&e.activities, `func(a *Activities) %s(ctx context.Context,in operationInput,name,goal string,tasks []gimbal.Task,previous string)(planResult,error){return a.plan(ctx,in,name,goal,tasks,previous)}
`, name)
	e.line("var %s planResult", plan)
	e.line("%s = workflow.ExecuteActivity(ops,%q,%s,%q,%s,%s,%s).Get(wait,&%s)", l.err, name, e.input(scope{id: l.id, snapshot: l.snapshot}, l.session), l.name, l.goal, tasks, feedback, plan)
	e.line("if %s == nil { %s = %s.Err() }; if %s != nil { break }", l.err, l.err, plan, l.err)
	e.line("%s = workflow.ExecuteActivity(ops,\"RecordPlan\",%s,%s,%s.Value).Get(wait,nil); if %s != nil { break }", l.err, l.id, l.goal, plan, l.err)
	e.line("%s = %s.Value.Tasks; if %s.Value.Next == nil { break }", tasks, plan, plan)
	e.line("%s := nextScope(%s,\"task\")", id, l.id)
	task := tasks + "[*" + plan + ".Value.Next]"
	e.activity(s, "EnterTaskScope", []string{"ScopeInput{" + id + "," + l.id + ",\"task\"}", task}, "")
	child := scope{id: id, snapshot: snap, keys: keys, task: id, ctx: e.pkg.TypesInfo.Defs[key]}
	e.line("%s := %s", snap, s.snapshot)
	e.line("%s := []string{}", keys)
	e.activity(child, "SetValue", []string{id, snap, "contextEntry(\"task\"," + task + ")"}, snap)
	e.line("%s = append(%s,\"task\")", keys, keys)
	if err := e.block(v.Body, child); err != nil {
		return err
	}
	e.activity(child, "TaskFeedback", []string{e.input(child, ""), keys}, feedback)
	errvar := e.fresh()
	e.line("var %s error", errvar)
	e.exitTask(child, errvar)
	e.line("if %s != nil {return %s}", errvar, errvar)
	e.line("}")
	e.line("%s = false", l.open)
	e.line(`%s = errors.Join(%s,workflow.ExecuteActivity(cleanupContext(ops),"ExitScope",%s,errorText(%s)).Get(cleanupContext(ops),nil))`, l.err, l.err, l.id, l.err)
	return nil
}

const workflowStart = `
 defer func(){if ctx.Err()!=nil{retErr=temporal.NewCanceledError(errorText(retErr))}}()
 control:=workflow.WithActivityOptions(ctx,workflow.ActivityOptions{TaskQueue:controlQueue,StartToCloseTimeout:2*time.Minute,WaitForCancellation:true,RetryPolicy:&temporal.RetryPolicy{MaximumAttempts:1}})
 defer func(){cleanup:=cleanupContext(control);retErr=errors.Join(retErr,workflow.ExecuteActivity(cleanup,"ReleaseEnvironment").Get(cleanup,nil))}()
 var environment Environment
 if err:=workflow.ExecuteActivity(control,"ProvisionEnvironment").Get(control,&environment);err!=nil{return err}
 ops:=workflow.WithActivityOptions(ctx,workflow.ActivityOptions{TaskQueue:environment.Queue,ScheduleToStartTimeout:time.Minute,StartToCloseTimeout:5*time.Minute,HeartbeatTimeout:15*time.Second,WaitForCancellation:true,RetryPolicy:&temporal.RetryPolicy{MaximumAttempts:1}})
 wait,_:=workflow.NewDisconnectedContext(ops)
 defer func(){cleanup:=cleanupContext(ops);finish:="Finish";if ctx.Err()!=nil{finish="FinishCancelled";retErr=errors.Join(retErr,ctx.Err())};retErr=errors.Join(retErr,workflow.ExecuteActivity(cleanup,finish,errorText(retErr)).Get(cleanup,nil))}()
 var root compiledscope.Snapshot
 if err:=workflow.ExecuteActivity(ops,"Initialize",Data{Context:in.Context,Name:$NAME}).Get(wait,&root);err!=nil{return err}
 var workdir string
 if err:=workflow.ExecuteActivity(ops,"WorkDir").Get(wait,&workdir);err!=nil{return err}
 _ = workdir
 scopeCounts:=map[string]int{}
 nextScope:=func(parent,name string)string{key:=parent+"/"+name;scopeCounts[key]++;id:=fmt.Sprintf("%s.%d",name,scopeCounts[key]);if parent!=""{id=parent+"/"+id};return id}
 _ = nextScope
`
