// Code generated by polytype. DO NOT EDIT.

package skgo

import (
	"encoding/json"
	"fmt"
	"math"
	"slices"
	"strconv"
	"time"

	pkg_conversation "github.com/tylergannon/gimble/internal/conversation"
	pkg_observation "github.com/tylergannon/gimble/internal/observation"
	pkg_onzggl3sn52xizlt "github.com/tylergannon/gimble/internal/skgo/links/onzggl3sn52xizlt"
	pkg_src "github.com/tylergannon/gimble/web/src"
	devalue "github.com/tylergannon/polytype/devalue"
)

// dvAt renders a JSON-pointer-style path for a diagnostic. The root value has
// the empty path, which is spelled "/" so a message never starts with ": ".
func dvAt(at string) string {
	if at == "" {
		return "/"
	}
	return at
}

func dvErr(at string, format string, args ...any) error {
	return fmt.Errorf("%s: %s", dvAt(at), fmt.Sprintf(format, args...))
}

// dvKind names the devalue value model kind of v for wrong-kind diagnostics.
// Every tagged form is named so a rejected Date or Map says which one it was.
func dvKind(v any) string {
	switch v.(type) {
	case nil:
		return "null"
	case devalue.UndefinedValue:
		return "undefined"
	case devalue.HoleValue:
		return "a sparse-array hole"
	case bool:
		return "a boolean"
	case float64:
		return "a number"
	case string:
		return "a string"
	case []any:
		return "an array"
	case *devalue.Object:
		return "an object"
	case devalue.Date:
		return "a Date"
	case *devalue.Map:
		return "a Map"
	case *devalue.Set:
		return "a Set"
	case devalue.BigInt:
		return "a BigInt"
	case devalue.RegExp:
		return "a RegExp"
	case devalue.ArrayBuffer:
		return "an ArrayBuffer"
	case *devalue.Boxed:
		return "a boxed primitive"
	default:
		return fmt.Sprintf("a value of type %T", v)
	}
}

func dvBool(raw any, at string) (bool, error) {
	v, ok := raw.(bool)
	if !ok {
		return false, dvErr(at, "expected a boolean, got %s", dvKind(raw))
	}
	return v, nil
}

func dvString(raw any, at string) (string, error) {
	v, ok := raw.(string)
	if !ok {
		return "", dvErr(at, "expected a string, got %s", dvKind(raw))
	}
	return v, nil
}

func dvNumber(raw any, at string) (float64, error) {
	v, ok := raw.(float64)
	if !ok {
		return 0, dvErr(at, "expected a number, got %s", dvKind(raw))
	}
	return v, nil
}

// dvFloat32 narrows a wire number, refusing values outside float32's range so
// a decode never silently yields an infinity.
func dvFloat32(raw any, at string) (float32, error) {
	v, err := dvNumber(raw, at)
	if err != nil {
		return 0, err
	}
	if !math.IsInf(v, 0) && !math.IsNaN(v) && math.Abs(v) > math.MaxFloat32 {
		return 0, dvErr(at, "number %v is out of range for float32", v)
	}
	return float32(v), nil
}

// dvInteger admits only integral numbers inside [min, max]. The bounds are
// float64 because every wire number is one; kinds wider than 2^53 are checked
// against the rounded bound, which is the same precision the encoder has.
func dvInteger(raw any, at string, min, max float64) (float64, error) {
	v, err := dvNumber(raw, at)
	if err != nil {
		return 0, err
	}
	if math.IsInf(v, 0) || math.IsNaN(v) || v != math.Trunc(v) {
		return 0, dvErr(at, "expected an integer, got %v", v)
	}
	if v < min || v > max {
		return 0, dvErr(at, "number %v is out of range", v)
	}
	return v, nil
}

func dvArray(raw any, at string) ([]any, error) {
	v, ok := raw.([]any)
	if !ok {
		return nil, dvErr(at, "expected an array, got %s", dvKind(raw))
	}
	for i, item := range v {
		if _, hole := item.(devalue.HoleValue); hole {
			return nil, dvErr(at+"/"+strconv.Itoa(i), "array element is a hole")
		}
	}
	return v, nil
}

func dvObject(raw any, at string) (*devalue.Object, error) {
	v, ok := raw.(*devalue.Object)
	if !ok {
		return nil, dvErr(at, "expected an object, got %s", dvKind(raw))
	}
	return v, nil
}

func dvKnown(o *devalue.Object, at string, known ...string) error {
	for _, key := range o.Keys() {
		if !slices.Contains(known, key) {
			return dvErr(at, "unknown property %q", key)
		}
	}
	return nil
}

// dvRequired reads a property that must be present and must not be undefined.
// at is the property's own path, so the diagnostic points at the value.
func dvRequired(o *devalue.Object, key string, at string) (any, error) {
	v, ok := o.Get(key)
	if !ok {
		return nil, dvErr(at, "missing required property %q", key)
	}
	if _, undefined := v.(devalue.UndefinedValue); undefined {
		return nil, dvErr(at, "value is undefined")
	}
	return v, nil
}

// dvPresent reads an optional property. It reports absence, and rejects an
// explicit undefined, which is not the same thing on this wire.
func dvPresent(o *devalue.Object, key string, at string) (any, bool, error) {
	v, ok := o.Get(key)
	if !ok {
		return nil, false, nil
	}
	if _, undefined := v.(devalue.UndefinedValue); undefined {
		return nil, false, dvErr(at, "value is undefined")
	}
	return v, true, nil
}

// dvWithout copies o omitting key, so a union payload decoder does not see the
// discriminator it never declared as a field.
func dvWithout(o *devalue.Object, key string) *devalue.Object {
	out := devalue.NewObject()
	for _, k := range o.Keys() {
		if k == key {
			continue
		}
		v, _ := o.Get(k)
		out.Set(k, v)
	}
	return out
}

// dvTagged rebuilds a union payload with the discriminator first, leaving any
// discriminator the payload itself carried out of the result.
func dvTagged(payload any, discriminator string, tag string, at string) (any, error) {
	o, err := dvObject(payload, at)
	if err != nil {
		return nil, err
	}
	out := devalue.NewObject()
	out.Set(discriminator, tag)
	for _, k := range o.Keys() {
		if k == discriminator {
			continue
		}
		v, _ := o.Get(k)
		out.Set(k, v)
	}
	return out, nil
}

// dvEncodeTime and dvDecodeTime use time.Time's own JSON methods, so the wire
// string is exactly the one encoding/json would produce and accept.
func dvEncodeTime(v time.Time, at string) (any, error) {
	encoded, err := v.MarshalJSON()
	if err != nil {
		return nil, dvErr(at, "%v", err)
	}
	var s string
	if err := json.Unmarshal(encoded, &s); err != nil {
		return nil, dvErr(at, "%v", err)
	}
	return s, nil
}

func dvDecodeTime(raw any, at string) (time.Time, error) {
	s, err := dvString(raw, at)
	if err != nil {
		return time.Time{}, err
	}
	quoted, err := json.Marshal(s)
	if err != nil {
		return time.Time{}, dvErr(at, "%v", err)
	}
	var v time.Time
	if err := v.UnmarshalJSON(quoted); err != nil {
		return time.Time{}, dvErr(at, "%v", err)
	}
	return v, nil
}

func encCancelRun(v pkg_onzggl3sn52xizlt.CancelRun, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = string(v.Run)
	enc1.Set("run", enc2)
	return enc1, nil
}

func decCancelRun(raw any, at string) (pkg_onzggl3sn52xizlt.CancelRun, error) {
	var dvZero pkg_onzggl3sn52xizlt.CancelRun
	var dec1 pkg_onzggl3sn52xizlt.CancelRun
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "run"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "run", at+"/run")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvString(raw3, at+"/run")
	if err != nil {
		return dvZero, err
	}
	dec1.Run = dec4
	return dec1, nil
}

// EncodeCancelRun converts v into the devalue value model.
func EncodeCancelRun(v pkg_onzggl3sn52xizlt.CancelRun) (any, error) { return encCancelRun(v, "") }

// DecodeCancelRun converts a devalue value model tree into a pkg_onzggl3sn52xizlt.CancelRun, rejecting any
// shape the type grammar does not admit.
func DecodeCancelRun(raw any) (pkg_onzggl3sn52xizlt.CancelRun, error) { return decCancelRun(raw, "") }

// StringifyCancelRun encodes v and serializes it with devalue.
func StringifyCancelRun(v pkg_onzggl3sn52xizlt.CancelRun) (string, error) {
	encoded, err := encCancelRun(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseCancelRun parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.CancelRun.
func ParseCancelRun(s string) (pkg_onzggl3sn52xizlt.CancelRun, error) {
	var zero pkg_onzggl3sn52xizlt.CancelRun
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decCancelRun(parsed, "")
}

func encControlAccepted(v pkg_onzggl3sn52xizlt.ControlAccepted, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = bool(v.Accepted)
	enc1.Set("accepted", enc2)
	return enc1, nil
}

func decControlAccepted(raw any, at string) (pkg_onzggl3sn52xizlt.ControlAccepted, error) {
	var dvZero pkg_onzggl3sn52xizlt.ControlAccepted
	var dec1 pkg_onzggl3sn52xizlt.ControlAccepted
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "accepted"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "accepted", at+"/accepted")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvBool(raw3, at+"/accepted")
	if err != nil {
		return dvZero, err
	}
	dec1.Accepted = dec4
	return dec1, nil
}

// EncodeControlAccepted converts v into the devalue value model.
func EncodeControlAccepted(v pkg_onzggl3sn52xizlt.ControlAccepted) (any, error) {
	return encControlAccepted(v, "")
}

// DecodeControlAccepted converts a devalue value model tree into a pkg_onzggl3sn52xizlt.ControlAccepted, rejecting any
// shape the type grammar does not admit.
func DecodeControlAccepted(raw any) (pkg_onzggl3sn52xizlt.ControlAccepted, error) {
	return decControlAccepted(raw, "")
}

// StringifyControlAccepted encodes v and serializes it with devalue.
func StringifyControlAccepted(v pkg_onzggl3sn52xizlt.ControlAccepted) (string, error) {
	encoded, err := encControlAccepted(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseControlAccepted parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.ControlAccepted.
func ParseControlAccepted(s string) (pkg_onzggl3sn52xizlt.ControlAccepted, error) {
	var zero pkg_onzggl3sn52xizlt.ControlAccepted
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decControlAccepted(parsed, "")
}

func encStopTurn(v pkg_onzggl3sn52xizlt.StopTurn, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = string(v.Run)
	enc1.Set("run", enc2)
	var enc3 any = string(v.Turn)
	enc1.Set("turn", enc3)
	return enc1, nil
}

func decStopTurn(raw any, at string) (pkg_onzggl3sn52xizlt.StopTurn, error) {
	var dvZero pkg_onzggl3sn52xizlt.StopTurn
	var dec1 pkg_onzggl3sn52xizlt.StopTurn
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "run", "turn"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "run", at+"/run")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvString(raw3, at+"/run")
	if err != nil {
		return dvZero, err
	}
	dec1.Run = dec4
	raw5, err := dvRequired(obj2, "turn", at+"/turn")
	if err != nil {
		return dvZero, err
	}
	dec6, err := dvString(raw5, at+"/turn")
	if err != nil {
		return dvZero, err
	}
	dec1.Turn = dec6
	return dec1, nil
}

// EncodeStopTurn converts v into the devalue value model.
func EncodeStopTurn(v pkg_onzggl3sn52xizlt.StopTurn) (any, error) { return encStopTurn(v, "") }

// DecodeStopTurn converts a devalue value model tree into a pkg_onzggl3sn52xizlt.StopTurn, rejecting any
// shape the type grammar does not admit.
func DecodeStopTurn(raw any) (pkg_onzggl3sn52xizlt.StopTurn, error) { return decStopTurn(raw, "") }

// StringifyStopTurn encodes v and serializes it with devalue.
func StringifyStopTurn(v pkg_onzggl3sn52xizlt.StopTurn) (string, error) {
	encoded, err := encStopTurn(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseStopTurn parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.StopTurn.
func ParseStopTurn(s string) (pkg_onzggl3sn52xizlt.StopTurn, error) {
	var zero pkg_onzggl3sn52xizlt.StopTurn
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decStopTurn(parsed, "")
}

func encCreateConversation(v pkg_onzggl3sn52xizlt.CreateConversation, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = string(v.Title)
	enc1.Set("title", enc2)
	var enc3 any = string(v.Provider)
	enc1.Set("provider", enc3)
	var enc4 any = string(v.Model)
	enc1.Set("model", enc4)
	return enc1, nil
}

func decCreateConversation(raw any, at string) (pkg_onzggl3sn52xizlt.CreateConversation, error) {
	var dvZero pkg_onzggl3sn52xizlt.CreateConversation
	var dec1 pkg_onzggl3sn52xizlt.CreateConversation
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "title", "provider", "model"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "title", at+"/title")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvString(raw3, at+"/title")
	if err != nil {
		return dvZero, err
	}
	dec1.Title = dec4
	raw5, err := dvRequired(obj2, "provider", at+"/provider")
	if err != nil {
		return dvZero, err
	}
	dec6, err := dvString(raw5, at+"/provider")
	if err != nil {
		return dvZero, err
	}
	dec1.Provider = dec6
	raw7, err := dvRequired(obj2, "model", at+"/model")
	if err != nil {
		return dvZero, err
	}
	dec8, err := dvString(raw7, at+"/model")
	if err != nil {
		return dvZero, err
	}
	dec1.Model = dec8
	return dec1, nil
}

// EncodeCreateConversation converts v into the devalue value model.
func EncodeCreateConversation(v pkg_onzggl3sn52xizlt.CreateConversation) (any, error) {
	return encCreateConversation(v, "")
}

// DecodeCreateConversation converts a devalue value model tree into a pkg_onzggl3sn52xizlt.CreateConversation, rejecting any
// shape the type grammar does not admit.
func DecodeCreateConversation(raw any) (pkg_onzggl3sn52xizlt.CreateConversation, error) {
	return decCreateConversation(raw, "")
}

// StringifyCreateConversation encodes v and serializes it with devalue.
func StringifyCreateConversation(v pkg_onzggl3sn52xizlt.CreateConversation) (string, error) {
	encoded, err := encCreateConversation(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseCreateConversation parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.CreateConversation.
func ParseCreateConversation(s string) (pkg_onzggl3sn52xizlt.CreateConversation, error) {
	var zero pkg_onzggl3sn52xizlt.CreateConversation
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decCreateConversation(parsed, "")
}

func encConversation(v pkg_conversation.Conversation, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = string(v.ID)
	enc1.Set("id", enc2)
	var enc3 any = string(v.Title)
	enc1.Set("title", enc3)
	var enc4 any = string(v.Provider)
	enc1.Set("provider", enc4)
	var enc5 any = string(v.Model)
	enc1.Set("model", enc5)
	var enc6 any = string(v.Branch)
	enc1.Set("branch", enc6)
	var enc7 any = string(v.Worktree)
	enc1.Set("worktree", enc7)
	var enc8 any = string(v.NativeSession)
	enc1.Set("native_session", enc8)
	var enc9 any = bool(v.Live)
	enc1.Set("live", enc9)
	var enc10 any = string(v.Status)
	enc1.Set("status", enc10)
	var enc11 any = string(v.Error)
	enc1.Set("error", enc11)
	var enc12 any = float64(v.Created)
	enc1.Set("created", enc12)
	var enc13 any = float64(v.Updated)
	enc1.Set("updated", enc13)
	enc14 := make([]any, 0, len(v.Messages))
	for i15, item16 := range v.Messages {
		enc17, err := encMessage(item16, at+"/messages"+"/"+strconv.Itoa(i15))
		if err != nil {
			return nil, err
		}
		enc14 = append(enc14, enc17)
	}
	var enc18 any = enc14
	enc1.Set("messages", enc18)
	enc19 := make([]any, 0, len(v.Runs))
	for i20, item21 := range v.Runs {
		enc22, err := encRun(item21, at+"/runs"+"/"+strconv.Itoa(i20))
		if err != nil {
			return nil, err
		}
		enc19 = append(enc19, enc22)
	}
	var enc23 any = enc19
	enc1.Set("runs", enc23)
	return enc1, nil
}

func decConversation(raw any, at string) (pkg_conversation.Conversation, error) {
	var dvZero pkg_conversation.Conversation
	var dec1 pkg_conversation.Conversation
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "id", "title", "provider", "model", "branch", "worktree", "native_session", "live", "status", "error", "created", "updated", "messages", "runs"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "id", at+"/id")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvString(raw3, at+"/id")
	if err != nil {
		return dvZero, err
	}
	dec1.ID = dec4
	raw5, err := dvRequired(obj2, "title", at+"/title")
	if err != nil {
		return dvZero, err
	}
	dec6, err := dvString(raw5, at+"/title")
	if err != nil {
		return dvZero, err
	}
	dec1.Title = dec6
	raw7, err := dvRequired(obj2, "provider", at+"/provider")
	if err != nil {
		return dvZero, err
	}
	dec8, err := dvString(raw7, at+"/provider")
	if err != nil {
		return dvZero, err
	}
	dec1.Provider = dec8
	raw9, err := dvRequired(obj2, "model", at+"/model")
	if err != nil {
		return dvZero, err
	}
	dec10, err := dvString(raw9, at+"/model")
	if err != nil {
		return dvZero, err
	}
	dec1.Model = dec10
	raw11, err := dvRequired(obj2, "branch", at+"/branch")
	if err != nil {
		return dvZero, err
	}
	dec12, err := dvString(raw11, at+"/branch")
	if err != nil {
		return dvZero, err
	}
	dec1.Branch = dec12
	raw13, err := dvRequired(obj2, "worktree", at+"/worktree")
	if err != nil {
		return dvZero, err
	}
	dec14, err := dvString(raw13, at+"/worktree")
	if err != nil {
		return dvZero, err
	}
	dec1.Worktree = dec14
	raw15, err := dvRequired(obj2, "native_session", at+"/native_session")
	if err != nil {
		return dvZero, err
	}
	dec16, err := dvString(raw15, at+"/native_session")
	if err != nil {
		return dvZero, err
	}
	dec1.NativeSession = dec16
	raw17, err := dvRequired(obj2, "live", at+"/live")
	if err != nil {
		return dvZero, err
	}
	dec18, err := dvBool(raw17, at+"/live")
	if err != nil {
		return dvZero, err
	}
	dec1.Live = dec18
	raw19, err := dvRequired(obj2, "status", at+"/status")
	if err != nil {
		return dvZero, err
	}
	dec20, err := dvString(raw19, at+"/status")
	if err != nil {
		return dvZero, err
	}
	dec1.Status = dec20
	raw21, err := dvRequired(obj2, "error", at+"/error")
	if err != nil {
		return dvZero, err
	}
	dec22, err := dvString(raw21, at+"/error")
	if err != nil {
		return dvZero, err
	}
	dec1.Error = dec22
	raw23, err := dvRequired(obj2, "created", at+"/created")
	if err != nil {
		return dvZero, err
	}
	num25, err := dvInteger(raw23, at+"/created", math.MinInt64, math.MaxInt64)
	if err != nil {
		return dvZero, err
	}
	dec24 := int64(num25)
	dec1.Created = dec24
	raw26, err := dvRequired(obj2, "updated", at+"/updated")
	if err != nil {
		return dvZero, err
	}
	num28, err := dvInteger(raw26, at+"/updated", math.MinInt64, math.MaxInt64)
	if err != nil {
		return dvZero, err
	}
	dec27 := int64(num28)
	dec1.Updated = dec27
	raw29, err := dvRequired(obj2, "messages", at+"/messages")
	if err != nil {
		return dvZero, err
	}
	items31, err := dvArray(raw29, at+"/messages")
	if err != nil {
		return dvZero, err
	}
	dec30 := make([]pkg_conversation.Message, 0, len(items31))
	for i32, item33 := range items31 {
		dec34, err := decMessage(item33, at+"/messages"+"/"+strconv.Itoa(i32))
		if err != nil {
			return dvZero, err
		}
		dec30 = append(dec30, dec34)
	}
	dec1.Messages = dec30
	raw35, err := dvRequired(obj2, "runs", at+"/runs")
	if err != nil {
		return dvZero, err
	}
	items37, err := dvArray(raw35, at+"/runs")
	if err != nil {
		return dvZero, err
	}
	dec36 := make([]pkg_conversation.Run, 0, len(items37))
	for i38, item39 := range items37 {
		dec40, err := decRun(item39, at+"/runs"+"/"+strconv.Itoa(i38))
		if err != nil {
			return dvZero, err
		}
		dec36 = append(dec36, dec40)
	}
	dec1.Runs = dec36
	return dec1, nil
}

// EncodeConversation converts v into the devalue value model.
func EncodeConversation(v pkg_conversation.Conversation) (any, error) { return encConversation(v, "") }

// DecodeConversation converts a devalue value model tree into a pkg_conversation.Conversation, rejecting any
// shape the type grammar does not admit.
func DecodeConversation(raw any) (pkg_conversation.Conversation, error) {
	return decConversation(raw, "")
}

// StringifyConversation encodes v and serializes it with devalue.
func StringifyConversation(v pkg_conversation.Conversation) (string, error) {
	encoded, err := encConversation(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseConversation parses a devalue document and decodes it into a pkg_conversation.Conversation.
func ParseConversation(s string) (pkg_conversation.Conversation, error) {
	var zero pkg_conversation.Conversation
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decConversation(parsed, "")
}

func encMessage(v pkg_conversation.Message, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = string(v.Role)
	enc1.Set("role", enc2)
	var enc3 any = string(v.Text)
	enc1.Set("text", enc3)
	var enc4 any = float64(v.Created)
	enc1.Set("created", enc4)
	return enc1, nil
}

func decMessage(raw any, at string) (pkg_conversation.Message, error) {
	var dvZero pkg_conversation.Message
	var dec1 pkg_conversation.Message
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "role", "text", "created"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "role", at+"/role")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvString(raw3, at+"/role")
	if err != nil {
		return dvZero, err
	}
	dec1.Role = dec4
	raw5, err := dvRequired(obj2, "text", at+"/text")
	if err != nil {
		return dvZero, err
	}
	dec6, err := dvString(raw5, at+"/text")
	if err != nil {
		return dvZero, err
	}
	dec1.Text = dec6
	raw7, err := dvRequired(obj2, "created", at+"/created")
	if err != nil {
		return dvZero, err
	}
	num9, err := dvInteger(raw7, at+"/created", math.MinInt64, math.MaxInt64)
	if err != nil {
		return dvZero, err
	}
	dec8 := int64(num9)
	dec1.Created = dec8
	return dec1, nil
}

// EncodeMessage converts v into the devalue value model.
func EncodeMessage(v pkg_conversation.Message) (any, error) { return encMessage(v, "") }

// DecodeMessage converts a devalue value model tree into a pkg_conversation.Message, rejecting any
// shape the type grammar does not admit.
func DecodeMessage(raw any) (pkg_conversation.Message, error) { return decMessage(raw, "") }

// StringifyMessage encodes v and serializes it with devalue.
func StringifyMessage(v pkg_conversation.Message) (string, error) {
	encoded, err := encMessage(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseMessage parses a devalue document and decodes it into a pkg_conversation.Message.
func ParseMessage(s string) (pkg_conversation.Message, error) {
	var zero pkg_conversation.Message
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decMessage(parsed, "")
}

func encRun(v pkg_conversation.Run, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = string(v.ID)
	enc1.Set("id", enc2)
	var enc3 any = string(v.Workflow)
	enc1.Set("workflow", enc3)
	var enc4 any = string(v.Status)
	enc1.Set("status", enc4)
	var enc5 any = string(v.Error)
	enc1.Set("error", enc5)
	return enc1, nil
}

func decRun(raw any, at string) (pkg_conversation.Run, error) {
	var dvZero pkg_conversation.Run
	var dec1 pkg_conversation.Run
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "id", "workflow", "status", "error"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "id", at+"/id")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvString(raw3, at+"/id")
	if err != nil {
		return dvZero, err
	}
	dec1.ID = dec4
	raw5, err := dvRequired(obj2, "workflow", at+"/workflow")
	if err != nil {
		return dvZero, err
	}
	dec6, err := dvString(raw5, at+"/workflow")
	if err != nil {
		return dvZero, err
	}
	dec1.Workflow = dec6
	raw7, err := dvRequired(obj2, "status", at+"/status")
	if err != nil {
		return dvZero, err
	}
	dec8, err := dvString(raw7, at+"/status")
	if err != nil {
		return dvZero, err
	}
	dec1.Status = dec8
	raw9, err := dvRequired(obj2, "error", at+"/error")
	if err != nil {
		return dvZero, err
	}
	dec10, err := dvString(raw9, at+"/error")
	if err != nil {
		return dvZero, err
	}
	dec1.Error = dec10
	return dec1, nil
}

// EncodeRun converts v into the devalue value model.
func EncodeRun(v pkg_conversation.Run) (any, error) { return encRun(v, "") }

// DecodeRun converts a devalue value model tree into a pkg_conversation.Run, rejecting any
// shape the type grammar does not admit.
func DecodeRun(raw any) (pkg_conversation.Run, error) { return decRun(raw, "") }

// StringifyRun encodes v and serializes it with devalue.
func StringifyRun(v pkg_conversation.Run) (string, error) {
	encoded, err := encRun(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRun parses a devalue document and decodes it into a pkg_conversation.Run.
func ParseRun(s string) (pkg_conversation.Run, error) {
	var zero pkg_conversation.Run
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRun(parsed, "")
}

func encSendConversationMessage(v pkg_onzggl3sn52xizlt.SendConversationMessage, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = string(v.Conversation)
	enc1.Set("conversation", enc2)
	var enc3 any = string(v.Message)
	enc1.Set("message", enc3)
	return enc1, nil
}

func decSendConversationMessage(raw any, at string) (pkg_onzggl3sn52xizlt.SendConversationMessage, error) {
	var dvZero pkg_onzggl3sn52xizlt.SendConversationMessage
	var dec1 pkg_onzggl3sn52xizlt.SendConversationMessage
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "conversation", "message"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "conversation", at+"/conversation")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvString(raw3, at+"/conversation")
	if err != nil {
		return dvZero, err
	}
	dec1.Conversation = dec4
	raw5, err := dvRequired(obj2, "message", at+"/message")
	if err != nil {
		return dvZero, err
	}
	dec6, err := dvString(raw5, at+"/message")
	if err != nil {
		return dvZero, err
	}
	dec1.Message = dec6
	return dec1, nil
}

// EncodeSendConversationMessage converts v into the devalue value model.
func EncodeSendConversationMessage(v pkg_onzggl3sn52xizlt.SendConversationMessage) (any, error) {
	return encSendConversationMessage(v, "")
}

// DecodeSendConversationMessage converts a devalue value model tree into a pkg_onzggl3sn52xizlt.SendConversationMessage, rejecting any
// shape the type grammar does not admit.
func DecodeSendConversationMessage(raw any) (pkg_onzggl3sn52xizlt.SendConversationMessage, error) {
	return decSendConversationMessage(raw, "")
}

// StringifySendConversationMessage encodes v and serializes it with devalue.
func StringifySendConversationMessage(v pkg_onzggl3sn52xizlt.SendConversationMessage) (string, error) {
	encoded, err := encSendConversationMessage(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseSendConversationMessage parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.SendConversationMessage.
func ParseSendConversationMessage(s string) (pkg_onzggl3sn52xizlt.SendConversationMessage, error) {
	var zero pkg_onzggl3sn52xizlt.SendConversationMessage
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decSendConversationMessage(parsed, "")
}

func encInterviewAnswered(v pkg_onzggl3sn52xizlt.InterviewAnswered, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = bool(v.Accepted)
	enc1.Set("accepted", enc2)
	return enc1, nil
}

func decInterviewAnswered(raw any, at string) (pkg_onzggl3sn52xizlt.InterviewAnswered, error) {
	var dvZero pkg_onzggl3sn52xizlt.InterviewAnswered
	var dec1 pkg_onzggl3sn52xizlt.InterviewAnswered
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "accepted"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "accepted", at+"/accepted")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvBool(raw3, at+"/accepted")
	if err != nil {
		return dvZero, err
	}
	dec1.Accepted = dec4
	return dec1, nil
}

// EncodeInterviewAnswered converts v into the devalue value model.
func EncodeInterviewAnswered(v pkg_onzggl3sn52xizlt.InterviewAnswered) (any, error) {
	return encInterviewAnswered(v, "")
}

// DecodeInterviewAnswered converts a devalue value model tree into a pkg_onzggl3sn52xizlt.InterviewAnswered, rejecting any
// shape the type grammar does not admit.
func DecodeInterviewAnswered(raw any) (pkg_onzggl3sn52xizlt.InterviewAnswered, error) {
	return decInterviewAnswered(raw, "")
}

// StringifyInterviewAnswered encodes v and serializes it with devalue.
func StringifyInterviewAnswered(v pkg_onzggl3sn52xizlt.InterviewAnswered) (string, error) {
	encoded, err := encInterviewAnswered(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseInterviewAnswered parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.InterviewAnswered.
func ParseInterviewAnswered(s string) (pkg_onzggl3sn52xizlt.InterviewAnswered, error) {
	var zero pkg_onzggl3sn52xizlt.InterviewAnswered
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decInterviewAnswered(parsed, "")
}

func encRunsData(v pkg_onzggl3sn52xizlt.RunsData, at string) (any, error) {
	enc1 := devalue.NewObject()
	enc2 := make([]any, 0, len(v.Items))
	for i3, item4 := range v.Items {
		enc5, err := encRunItem(item4, at+"/items"+"/"+strconv.Itoa(i3))
		if err != nil {
			return nil, err
		}
		enc2 = append(enc2, enc5)
	}
	var enc6 any = enc2
	enc1.Set("items", enc6)
	enc7 := make([]any, 0, len(v.Attention))
	for i8, item9 := range v.Attention {
		enc10, err := encInterviewRow(item9, at+"/attention"+"/"+strconv.Itoa(i8))
		if err != nil {
			return nil, err
		}
		enc7 = append(enc7, enc10)
	}
	var enc11 any = enc7
	enc1.Set("attention", enc11)
	var enc12 any = float64(v.Now)
	enc1.Set("now", enc12)
	return enc1, nil
}

func decRunsData(raw any, at string) (pkg_onzggl3sn52xizlt.RunsData, error) {
	var dvZero pkg_onzggl3sn52xizlt.RunsData
	var dec1 pkg_onzggl3sn52xizlt.RunsData
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "items", "attention", "now"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "items", at+"/items")
	if err != nil {
		return dvZero, err
	}
	items5, err := dvArray(raw3, at+"/items")
	if err != nil {
		return dvZero, err
	}
	dec4 := make([]pkg_onzggl3sn52xizlt.RunItem, 0, len(items5))
	for i6, item7 := range items5 {
		dec8, err := decRunItem(item7, at+"/items"+"/"+strconv.Itoa(i6))
		if err != nil {
			return dvZero, err
		}
		dec4 = append(dec4, dec8)
	}
	dec1.Items = dec4
	raw9, err := dvRequired(obj2, "attention", at+"/attention")
	if err != nil {
		return dvZero, err
	}
	items11, err := dvArray(raw9, at+"/attention")
	if err != nil {
		return dvZero, err
	}
	dec10 := make([]pkg_observation.InterviewRow, 0, len(items11))
	for i12, item13 := range items11 {
		dec14, err := decInterviewRow(item13, at+"/attention"+"/"+strconv.Itoa(i12))
		if err != nil {
			return dvZero, err
		}
		dec10 = append(dec10, dec14)
	}
	dec1.Attention = dec10
	raw15, err := dvRequired(obj2, "now", at+"/now")
	if err != nil {
		return dvZero, err
	}
	num17, err := dvInteger(raw15, at+"/now", math.MinInt64, math.MaxInt64)
	if err != nil {
		return dvZero, err
	}
	dec16 := int64(num17)
	dec1.Now = dec16
	return dec1, nil
}

// EncodeRunsData converts v into the devalue value model.
func EncodeRunsData(v pkg_onzggl3sn52xizlt.RunsData) (any, error) { return encRunsData(v, "") }

// DecodeRunsData converts a devalue value model tree into a pkg_onzggl3sn52xizlt.RunsData, rejecting any
// shape the type grammar does not admit.
func DecodeRunsData(raw any) (pkg_onzggl3sn52xizlt.RunsData, error) { return decRunsData(raw, "") }

// StringifyRunsData encodes v and serializes it with devalue.
func StringifyRunsData(v pkg_onzggl3sn52xizlt.RunsData) (string, error) {
	encoded, err := encRunsData(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRunsData parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.RunsData.
func ParseRunsData(s string) (pkg_onzggl3sn52xizlt.RunsData, error) {
	var zero pkg_onzggl3sn52xizlt.RunsData
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRunsData(parsed, "")
}

func encRunItem(v pkg_onzggl3sn52xizlt.RunItem, at string) (any, error) {
	enc1 := devalue.NewObject()
	enc2, err := encRunRow(v.Run, at+"/run")
	if err != nil {
		return nil, err
	}
	enc1.Set("run", enc2)
	var enc3 any = string(v.Summary)
	enc1.Set("summary", enc3)
	var enc4 any = string(v.Elapsed)
	enc1.Set("elapsed", enc4)
	var enc5 any = float64(v.ActivityAt)
	enc1.Set("activity_at", enc5)
	var enc6 any = string(v.Cost)
	enc1.Set("cost", enc6)
	var enc7 any = float64(v.SessionCount)
	enc1.Set("session_count", enc7)
	var enc8 any = float64(v.TurnCount)
	enc1.Set("turn_count", enc8)
	var enc9 any = string(v.Instruction)
	enc1.Set("instruction", enc9)
	return enc1, nil
}

func decRunItem(raw any, at string) (pkg_onzggl3sn52xizlt.RunItem, error) {
	var dvZero pkg_onzggl3sn52xizlt.RunItem
	var dec1 pkg_onzggl3sn52xizlt.RunItem
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "run", "summary", "elapsed", "activity_at", "cost", "session_count", "turn_count", "instruction"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "run", at+"/run")
	if err != nil {
		return dvZero, err
	}
	dec4, err := decRunRow(raw3, at+"/run")
	if err != nil {
		return dvZero, err
	}
	dec1.Run = dec4
	raw5, err := dvRequired(obj2, "summary", at+"/summary")
	if err != nil {
		return dvZero, err
	}
	dec6, err := dvString(raw5, at+"/summary")
	if err != nil {
		return dvZero, err
	}
	dec1.Summary = dec6
	raw7, err := dvRequired(obj2, "elapsed", at+"/elapsed")
	if err != nil {
		return dvZero, err
	}
	dec8, err := dvString(raw7, at+"/elapsed")
	if err != nil {
		return dvZero, err
	}
	dec1.Elapsed = dec8
	raw9, err := dvRequired(obj2, "activity_at", at+"/activity_at")
	if err != nil {
		return dvZero, err
	}
	num11, err := dvInteger(raw9, at+"/activity_at", math.MinInt64, math.MaxInt64)
	if err != nil {
		return dvZero, err
	}
	dec10 := int64(num11)
	dec1.ActivityAt = dec10
	raw12, err := dvRequired(obj2, "cost", at+"/cost")
	if err != nil {
		return dvZero, err
	}
	dec13, err := dvString(raw12, at+"/cost")
	if err != nil {
		return dvZero, err
	}
	dec1.Cost = dec13
	raw14, err := dvRequired(obj2, "session_count", at+"/session_count")
	if err != nil {
		return dvZero, err
	}
	num16, err := dvInteger(raw14, at+"/session_count", math.MinInt, math.MaxInt)
	if err != nil {
		return dvZero, err
	}
	dec15 := int(num16)
	dec1.SessionCount = dec15
	raw17, err := dvRequired(obj2, "turn_count", at+"/turn_count")
	if err != nil {
		return dvZero, err
	}
	num19, err := dvInteger(raw17, at+"/turn_count", math.MinInt, math.MaxInt)
	if err != nil {
		return dvZero, err
	}
	dec18 := int(num19)
	dec1.TurnCount = dec18
	raw20, err := dvRequired(obj2, "instruction", at+"/instruction")
	if err != nil {
		return dvZero, err
	}
	dec21, err := dvString(raw20, at+"/instruction")
	if err != nil {
		return dvZero, err
	}
	dec1.Instruction = dec21
	return dec1, nil
}

// EncodeRunItem converts v into the devalue value model.
func EncodeRunItem(v pkg_onzggl3sn52xizlt.RunItem) (any, error) { return encRunItem(v, "") }

// DecodeRunItem converts a devalue value model tree into a pkg_onzggl3sn52xizlt.RunItem, rejecting any
// shape the type grammar does not admit.
func DecodeRunItem(raw any) (pkg_onzggl3sn52xizlt.RunItem, error) { return decRunItem(raw, "") }

// StringifyRunItem encodes v and serializes it with devalue.
func StringifyRunItem(v pkg_onzggl3sn52xizlt.RunItem) (string, error) {
	encoded, err := encRunItem(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRunItem parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.RunItem.
func ParseRunItem(s string) (pkg_onzggl3sn52xizlt.RunItem, error) {
	var zero pkg_onzggl3sn52xizlt.RunItem
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRunItem(parsed, "")
}

func encRunRow(v pkg_observation.RunRow, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = string(v.ID)
	enc1.Set("id", enc2)
	var enc3 any = string(v.Name)
	enc1.Set("name", enc3)
	var enc4 any = string(v.Status)
	enc1.Set("status", enc4)
	var enc5 any = string(v.Error)
	enc1.Set("error", enc5)
	var enc6 any = float64(v.Started)
	enc1.Set("started", enc6)
	var enc7 any = float64(v.Ended)
	enc1.Set("ended", enc7)
	return enc1, nil
}

func decRunRow(raw any, at string) (pkg_observation.RunRow, error) {
	var dvZero pkg_observation.RunRow
	var dec1 pkg_observation.RunRow
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "id", "name", "status", "error", "started", "ended"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "id", at+"/id")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvString(raw3, at+"/id")
	if err != nil {
		return dvZero, err
	}
	dec1.ID = dec4
	raw5, err := dvRequired(obj2, "name", at+"/name")
	if err != nil {
		return dvZero, err
	}
	dec6, err := dvString(raw5, at+"/name")
	if err != nil {
		return dvZero, err
	}
	dec1.Name = dec6
	raw7, err := dvRequired(obj2, "status", at+"/status")
	if err != nil {
		return dvZero, err
	}
	dec8, err := dvString(raw7, at+"/status")
	if err != nil {
		return dvZero, err
	}
	dec1.Status = dec8
	raw9, err := dvRequired(obj2, "error", at+"/error")
	if err != nil {
		return dvZero, err
	}
	dec10, err := dvString(raw9, at+"/error")
	if err != nil {
		return dvZero, err
	}
	dec1.Error = dec10
	raw11, err := dvRequired(obj2, "started", at+"/started")
	if err != nil {
		return dvZero, err
	}
	num13, err := dvInteger(raw11, at+"/started", math.MinInt64, math.MaxInt64)
	if err != nil {
		return dvZero, err
	}
	dec12 := int64(num13)
	dec1.Started = dec12
	raw14, err := dvRequired(obj2, "ended", at+"/ended")
	if err != nil {
		return dvZero, err
	}
	num16, err := dvInteger(raw14, at+"/ended", math.MinInt64, math.MaxInt64)
	if err != nil {
		return dvZero, err
	}
	dec15 := int64(num16)
	dec1.Ended = dec15
	return dec1, nil
}

// EncodeRunRow converts v into the devalue value model.
func EncodeRunRow(v pkg_observation.RunRow) (any, error) { return encRunRow(v, "") }

// DecodeRunRow converts a devalue value model tree into a pkg_observation.RunRow, rejecting any
// shape the type grammar does not admit.
func DecodeRunRow(raw any) (pkg_observation.RunRow, error) { return decRunRow(raw, "") }

// StringifyRunRow encodes v and serializes it with devalue.
func StringifyRunRow(v pkg_observation.RunRow) (string, error) {
	encoded, err := encRunRow(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRunRow parses a devalue document and decodes it into a pkg_observation.RunRow.
func ParseRunRow(s string) (pkg_observation.RunRow, error) {
	var zero pkg_observation.RunRow
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRunRow(parsed, "")
}

func encInterviewRow(v pkg_observation.InterviewRow, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = string(v.Run)
	enc1.Set("run", enc2)
	var enc3 any = string(v.QuestionID)
	enc1.Set("question_id", enc3)
	var enc4 any = string(v.Name)
	enc1.Set("name", enc4)
	var enc5 any = string(v.Scope)
	enc1.Set("scope", enc5)
	var enc6 any = string(v.Session)
	enc1.Set("session", enc6)
	var enc7 any = string(v.Question)
	enc1.Set("question", enc7)
	var enc8 any = string(v.Status)
	enc1.Set("status", enc8)
	var enc9 any = string(v.Answer)
	enc1.Set("answer", enc9)
	var enc10 any = float64(v.Asked)
	enc1.Set("asked", enc10)
	var enc11 any = float64(v.Answered)
	enc1.Set("answered", enc11)
	return enc1, nil
}

func decInterviewRow(raw any, at string) (pkg_observation.InterviewRow, error) {
	var dvZero pkg_observation.InterviewRow
	var dec1 pkg_observation.InterviewRow
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "run", "question_id", "name", "scope", "session", "question", "status", "answer", "asked", "answered"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "run", at+"/run")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvString(raw3, at+"/run")
	if err != nil {
		return dvZero, err
	}
	dec1.Run = dec4
	raw5, err := dvRequired(obj2, "question_id", at+"/question_id")
	if err != nil {
		return dvZero, err
	}
	dec6, err := dvString(raw5, at+"/question_id")
	if err != nil {
		return dvZero, err
	}
	dec1.QuestionID = dec6
	raw7, err := dvRequired(obj2, "name", at+"/name")
	if err != nil {
		return dvZero, err
	}
	dec8, err := dvString(raw7, at+"/name")
	if err != nil {
		return dvZero, err
	}
	dec1.Name = dec8
	raw9, err := dvRequired(obj2, "scope", at+"/scope")
	if err != nil {
		return dvZero, err
	}
	dec10, err := dvString(raw9, at+"/scope")
	if err != nil {
		return dvZero, err
	}
	dec1.Scope = dec10
	raw11, err := dvRequired(obj2, "session", at+"/session")
	if err != nil {
		return dvZero, err
	}
	dec12, err := dvString(raw11, at+"/session")
	if err != nil {
		return dvZero, err
	}
	dec1.Session = dec12
	raw13, err := dvRequired(obj2, "question", at+"/question")
	if err != nil {
		return dvZero, err
	}
	dec14, err := dvString(raw13, at+"/question")
	if err != nil {
		return dvZero, err
	}
	dec1.Question = dec14
	raw15, err := dvRequired(obj2, "status", at+"/status")
	if err != nil {
		return dvZero, err
	}
	dec16, err := dvString(raw15, at+"/status")
	if err != nil {
		return dvZero, err
	}
	dec1.Status = dec16
	raw17, err := dvRequired(obj2, "answer", at+"/answer")
	if err != nil {
		return dvZero, err
	}
	dec18, err := dvString(raw17, at+"/answer")
	if err != nil {
		return dvZero, err
	}
	dec1.Answer = dec18
	raw19, err := dvRequired(obj2, "asked", at+"/asked")
	if err != nil {
		return dvZero, err
	}
	num21, err := dvInteger(raw19, at+"/asked", math.MinInt64, math.MaxInt64)
	if err != nil {
		return dvZero, err
	}
	dec20 := int64(num21)
	dec1.Asked = dec20
	raw22, err := dvRequired(obj2, "answered", at+"/answered")
	if err != nil {
		return dvZero, err
	}
	num24, err := dvInteger(raw22, at+"/answered", math.MinInt64, math.MaxInt64)
	if err != nil {
		return dvZero, err
	}
	dec23 := int64(num24)
	dec1.Answered = dec23
	return dec1, nil
}

// EncodeInterviewRow converts v into the devalue value model.
func EncodeInterviewRow(v pkg_observation.InterviewRow) (any, error) { return encInterviewRow(v, "") }

// DecodeInterviewRow converts a devalue value model tree into a pkg_observation.InterviewRow, rejecting any
// shape the type grammar does not admit.
func DecodeInterviewRow(raw any) (pkg_observation.InterviewRow, error) {
	return decInterviewRow(raw, "")
}

// StringifyInterviewRow encodes v and serializes it with devalue.
func StringifyInterviewRow(v pkg_observation.InterviewRow) (string, error) {
	encoded, err := encInterviewRow(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseInterviewRow parses a devalue document and decodes it into a pkg_observation.InterviewRow.
func ParseInterviewRow(s string) (pkg_observation.InterviewRow, error) {
	var zero pkg_observation.InterviewRow
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decInterviewRow(parsed, "")
}

func encSent(v pkg_onzggl3sn52xizlt.Sent, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = bool(v.Landed)
	enc1.Set("landed", enc2)
	return enc1, nil
}

func decSent(raw any, at string) (pkg_onzggl3sn52xizlt.Sent, error) {
	var dvZero pkg_onzggl3sn52xizlt.Sent
	var dec1 pkg_onzggl3sn52xizlt.Sent
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "landed"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "landed", at+"/landed")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvBool(raw3, at+"/landed")
	if err != nil {
		return dvZero, err
	}
	dec1.Landed = dec4
	return dec1, nil
}

// EncodeSent converts v into the devalue value model.
func EncodeSent(v pkg_onzggl3sn52xizlt.Sent) (any, error) { return encSent(v, "") }

// DecodeSent converts a devalue value model tree into a pkg_onzggl3sn52xizlt.Sent, rejecting any
// shape the type grammar does not admit.
func DecodeSent(raw any) (pkg_onzggl3sn52xizlt.Sent, error) { return decSent(raw, "") }

// StringifySent encodes v and serializes it with devalue.
func StringifySent(v pkg_onzggl3sn52xizlt.Sent) (string, error) {
	encoded, err := encSent(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseSent parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.Sent.
func ParseSent(s string) (pkg_onzggl3sn52xizlt.Sent, error) {
	var zero pkg_onzggl3sn52xizlt.Sent
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decSent(parsed, "")
}

func encWaiting(v pkg_onzggl3sn52xizlt.Waiting, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = string(v.Message)
	enc1.Set("message", enc2)
	return enc1, nil
}

func decWaiting(raw any, at string) (pkg_onzggl3sn52xizlt.Waiting, error) {
	var dvZero pkg_onzggl3sn52xizlt.Waiting
	var dec1 pkg_onzggl3sn52xizlt.Waiting
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "message"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "message", at+"/message")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvString(raw3, at+"/message")
	if err != nil {
		return dvZero, err
	}
	dec1.Message = dec4
	return dec1, nil
}

// EncodeWaiting converts v into the devalue value model.
func EncodeWaiting(v pkg_onzggl3sn52xizlt.Waiting) (any, error) { return encWaiting(v, "") }

// DecodeWaiting converts a devalue value model tree into a pkg_onzggl3sn52xizlt.Waiting, rejecting any
// shape the type grammar does not admit.
func DecodeWaiting(raw any) (pkg_onzggl3sn52xizlt.Waiting, error) { return decWaiting(raw, "") }

// StringifyWaiting encodes v and serializes it with devalue.
func StringifyWaiting(v pkg_onzggl3sn52xizlt.Waiting) (string, error) {
	encoded, err := encWaiting(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseWaiting parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.Waiting.
func ParseWaiting(s string) (pkg_onzggl3sn52xizlt.Waiting, error) {
	var zero pkg_onzggl3sn52xizlt.Waiting
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decWaiting(parsed, "")
}

func encRunSnapshot(v pkg_src.RunSnapshot, at string) (any, error) {
	enc1 := devalue.NewObject()
	var enc2 any = string(v.JSON)
	enc1.Set("json", enc2)
	return enc1, nil
}

func decRunSnapshot(raw any, at string) (pkg_src.RunSnapshot, error) {
	var dvZero pkg_src.RunSnapshot
	var dec1 pkg_src.RunSnapshot
	obj2, err := dvObject(raw, at)
	if err != nil {
		return dvZero, err
	}
	if err := dvKnown(obj2, at, "json"); err != nil {
		return dvZero, err
	}
	raw3, err := dvRequired(obj2, "json", at+"/json")
	if err != nil {
		return dvZero, err
	}
	dec4, err := dvString(raw3, at+"/json")
	if err != nil {
		return dvZero, err
	}
	dec1.JSON = dec4
	return dec1, nil
}

// EncodeRunSnapshot converts v into the devalue value model.
func EncodeRunSnapshot(v pkg_src.RunSnapshot) (any, error) { return encRunSnapshot(v, "") }

// DecodeRunSnapshot converts a devalue value model tree into a pkg_src.RunSnapshot, rejecting any
// shape the type grammar does not admit.
func DecodeRunSnapshot(raw any) (pkg_src.RunSnapshot, error) { return decRunSnapshot(raw, "") }

// StringifyRunSnapshot encodes v and serializes it with devalue.
func StringifyRunSnapshot(v pkg_src.RunSnapshot) (string, error) {
	encoded, err := encRunSnapshot(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRunSnapshot parses a devalue document and decodes it into a pkg_src.RunSnapshot.
func ParseRunSnapshot(s string) (pkg_src.RunSnapshot, error) {
	var zero pkg_src.RunSnapshot
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRunSnapshot(parsed, "")
}

func encRoot0(v pkg_onzggl3sn52xizlt.CancelRun, at string) (any, error) {
	enc1, err := encCancelRun(v, at)
	if err != nil {
		return nil, err
	}
	return enc1, nil
}

func decRoot0(raw any, at string) (pkg_onzggl3sn52xizlt.CancelRun, error) {
	var dvZero pkg_onzggl3sn52xizlt.CancelRun
	dec1, err := decCancelRun(raw, at)
	if err != nil {
		return dvZero, err
	}
	return dec1, nil
}

// EncodeRoot0 converts v into the devalue value model.
func EncodeRoot0(v pkg_onzggl3sn52xizlt.CancelRun) (any, error) { return encRoot0(v, "") }

// DecodeRoot0 converts a devalue value model tree into a pkg_onzggl3sn52xizlt.CancelRun, rejecting any
// shape the type grammar does not admit.
func DecodeRoot0(raw any) (pkg_onzggl3sn52xizlt.CancelRun, error) { return decRoot0(raw, "") }

// StringifyRoot0 encodes v and serializes it with devalue.
func StringifyRoot0(v pkg_onzggl3sn52xizlt.CancelRun) (string, error) {
	encoded, err := encRoot0(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRoot0 parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.CancelRun.
func ParseRoot0(s string) (pkg_onzggl3sn52xizlt.CancelRun, error) {
	var zero pkg_onzggl3sn52xizlt.CancelRun
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRoot0(parsed, "")
}

func encRoot1(v pkg_onzggl3sn52xizlt.ControlAccepted, at string) (any, error) {
	enc1, err := encControlAccepted(v, at)
	if err != nil {
		return nil, err
	}
	return enc1, nil
}

func decRoot1(raw any, at string) (pkg_onzggl3sn52xizlt.ControlAccepted, error) {
	var dvZero pkg_onzggl3sn52xizlt.ControlAccepted
	dec1, err := decControlAccepted(raw, at)
	if err != nil {
		return dvZero, err
	}
	return dec1, nil
}

// EncodeRoot1 converts v into the devalue value model.
func EncodeRoot1(v pkg_onzggl3sn52xizlt.ControlAccepted) (any, error) { return encRoot1(v, "") }

// DecodeRoot1 converts a devalue value model tree into a pkg_onzggl3sn52xizlt.ControlAccepted, rejecting any
// shape the type grammar does not admit.
func DecodeRoot1(raw any) (pkg_onzggl3sn52xizlt.ControlAccepted, error) { return decRoot1(raw, "") }

// StringifyRoot1 encodes v and serializes it with devalue.
func StringifyRoot1(v pkg_onzggl3sn52xizlt.ControlAccepted) (string, error) {
	encoded, err := encRoot1(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRoot1 parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.ControlAccepted.
func ParseRoot1(s string) (pkg_onzggl3sn52xizlt.ControlAccepted, error) {
	var zero pkg_onzggl3sn52xizlt.ControlAccepted
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRoot1(parsed, "")
}

func encRoot2(v pkg_onzggl3sn52xizlt.StopTurn, at string) (any, error) {
	enc1, err := encStopTurn(v, at)
	if err != nil {
		return nil, err
	}
	return enc1, nil
}

func decRoot2(raw any, at string) (pkg_onzggl3sn52xizlt.StopTurn, error) {
	var dvZero pkg_onzggl3sn52xizlt.StopTurn
	dec1, err := decStopTurn(raw, at)
	if err != nil {
		return dvZero, err
	}
	return dec1, nil
}

// EncodeRoot2 converts v into the devalue value model.
func EncodeRoot2(v pkg_onzggl3sn52xizlt.StopTurn) (any, error) { return encRoot2(v, "") }

// DecodeRoot2 converts a devalue value model tree into a pkg_onzggl3sn52xizlt.StopTurn, rejecting any
// shape the type grammar does not admit.
func DecodeRoot2(raw any) (pkg_onzggl3sn52xizlt.StopTurn, error) { return decRoot2(raw, "") }

// StringifyRoot2 encodes v and serializes it with devalue.
func StringifyRoot2(v pkg_onzggl3sn52xizlt.StopTurn) (string, error) {
	encoded, err := encRoot2(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRoot2 parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.StopTurn.
func ParseRoot2(s string) (pkg_onzggl3sn52xizlt.StopTurn, error) {
	var zero pkg_onzggl3sn52xizlt.StopTurn
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRoot2(parsed, "")
}

func encRoot3(v pkg_onzggl3sn52xizlt.CreateConversation, at string) (any, error) {
	enc1, err := encCreateConversation(v, at)
	if err != nil {
		return nil, err
	}
	return enc1, nil
}

func decRoot3(raw any, at string) (pkg_onzggl3sn52xizlt.CreateConversation, error) {
	var dvZero pkg_onzggl3sn52xizlt.CreateConversation
	dec1, err := decCreateConversation(raw, at)
	if err != nil {
		return dvZero, err
	}
	return dec1, nil
}

// EncodeRoot3 converts v into the devalue value model.
func EncodeRoot3(v pkg_onzggl3sn52xizlt.CreateConversation) (any, error) { return encRoot3(v, "") }

// DecodeRoot3 converts a devalue value model tree into a pkg_onzggl3sn52xizlt.CreateConversation, rejecting any
// shape the type grammar does not admit.
func DecodeRoot3(raw any) (pkg_onzggl3sn52xizlt.CreateConversation, error) { return decRoot3(raw, "") }

// StringifyRoot3 encodes v and serializes it with devalue.
func StringifyRoot3(v pkg_onzggl3sn52xizlt.CreateConversation) (string, error) {
	encoded, err := encRoot3(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRoot3 parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.CreateConversation.
func ParseRoot3(s string) (pkg_onzggl3sn52xizlt.CreateConversation, error) {
	var zero pkg_onzggl3sn52xizlt.CreateConversation
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRoot3(parsed, "")
}

func encRoot4(v pkg_conversation.Conversation, at string) (any, error) {
	enc1, err := encConversation(v, at)
	if err != nil {
		return nil, err
	}
	return enc1, nil
}

func decRoot4(raw any, at string) (pkg_conversation.Conversation, error) {
	var dvZero pkg_conversation.Conversation
	dec1, err := decConversation(raw, at)
	if err != nil {
		return dvZero, err
	}
	return dec1, nil
}

// EncodeRoot4 converts v into the devalue value model.
func EncodeRoot4(v pkg_conversation.Conversation) (any, error) { return encRoot4(v, "") }

// DecodeRoot4 converts a devalue value model tree into a pkg_conversation.Conversation, rejecting any
// shape the type grammar does not admit.
func DecodeRoot4(raw any) (pkg_conversation.Conversation, error) { return decRoot4(raw, "") }

// StringifyRoot4 encodes v and serializes it with devalue.
func StringifyRoot4(v pkg_conversation.Conversation) (string, error) {
	encoded, err := encRoot4(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRoot4 parses a devalue document and decodes it into a pkg_conversation.Conversation.
func ParseRoot4(s string) (pkg_conversation.Conversation, error) {
	var zero pkg_conversation.Conversation
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRoot4(parsed, "")
}

func encRoot5(v pkg_onzggl3sn52xizlt.SendConversationMessage, at string) (any, error) {
	enc1, err := encSendConversationMessage(v, at)
	if err != nil {
		return nil, err
	}
	return enc1, nil
}

func decRoot5(raw any, at string) (pkg_onzggl3sn52xizlt.SendConversationMessage, error) {
	var dvZero pkg_onzggl3sn52xizlt.SendConversationMessage
	dec1, err := decSendConversationMessage(raw, at)
	if err != nil {
		return dvZero, err
	}
	return dec1, nil
}

// EncodeRoot5 converts v into the devalue value model.
func EncodeRoot5(v pkg_onzggl3sn52xizlt.SendConversationMessage) (any, error) { return encRoot5(v, "") }

// DecodeRoot5 converts a devalue value model tree into a pkg_onzggl3sn52xizlt.SendConversationMessage, rejecting any
// shape the type grammar does not admit.
func DecodeRoot5(raw any) (pkg_onzggl3sn52xizlt.SendConversationMessage, error) {
	return decRoot5(raw, "")
}

// StringifyRoot5 encodes v and serializes it with devalue.
func StringifyRoot5(v pkg_onzggl3sn52xizlt.SendConversationMessage) (string, error) {
	encoded, err := encRoot5(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRoot5 parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.SendConversationMessage.
func ParseRoot5(s string) (pkg_onzggl3sn52xizlt.SendConversationMessage, error) {
	var zero pkg_onzggl3sn52xizlt.SendConversationMessage
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRoot5(parsed, "")
}

func encRoot6(v pkg_onzggl3sn52xizlt.InterviewAnswered, at string) (any, error) {
	enc1, err := encInterviewAnswered(v, at)
	if err != nil {
		return nil, err
	}
	return enc1, nil
}

func decRoot6(raw any, at string) (pkg_onzggl3sn52xizlt.InterviewAnswered, error) {
	var dvZero pkg_onzggl3sn52xizlt.InterviewAnswered
	dec1, err := decInterviewAnswered(raw, at)
	if err != nil {
		return dvZero, err
	}
	return dec1, nil
}

// EncodeRoot6 converts v into the devalue value model.
func EncodeRoot6(v pkg_onzggl3sn52xizlt.InterviewAnswered) (any, error) { return encRoot6(v, "") }

// DecodeRoot6 converts a devalue value model tree into a pkg_onzggl3sn52xizlt.InterviewAnswered, rejecting any
// shape the type grammar does not admit.
func DecodeRoot6(raw any) (pkg_onzggl3sn52xizlt.InterviewAnswered, error) { return decRoot6(raw, "") }

// StringifyRoot6 encodes v and serializes it with devalue.
func StringifyRoot6(v pkg_onzggl3sn52xizlt.InterviewAnswered) (string, error) {
	encoded, err := encRoot6(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRoot6 parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.InterviewAnswered.
func ParseRoot6(s string) (pkg_onzggl3sn52xizlt.InterviewAnswered, error) {
	var zero pkg_onzggl3sn52xizlt.InterviewAnswered
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRoot6(parsed, "")
}

func encRoot7(v pkg_onzggl3sn52xizlt.RunsData, at string) (any, error) {
	enc1, err := encRunsData(v, at)
	if err != nil {
		return nil, err
	}
	return enc1, nil
}

func decRoot7(raw any, at string) (pkg_onzggl3sn52xizlt.RunsData, error) {
	var dvZero pkg_onzggl3sn52xizlt.RunsData
	dec1, err := decRunsData(raw, at)
	if err != nil {
		return dvZero, err
	}
	return dec1, nil
}

// EncodeRoot7 converts v into the devalue value model.
func EncodeRoot7(v pkg_onzggl3sn52xizlt.RunsData) (any, error) { return encRoot7(v, "") }

// DecodeRoot7 converts a devalue value model tree into a pkg_onzggl3sn52xizlt.RunsData, rejecting any
// shape the type grammar does not admit.
func DecodeRoot7(raw any) (pkg_onzggl3sn52xizlt.RunsData, error) { return decRoot7(raw, "") }

// StringifyRoot7 encodes v and serializes it with devalue.
func StringifyRoot7(v pkg_onzggl3sn52xizlt.RunsData) (string, error) {
	encoded, err := encRoot7(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRoot7 parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.RunsData.
func ParseRoot7(s string) (pkg_onzggl3sn52xizlt.RunsData, error) {
	var zero pkg_onzggl3sn52xizlt.RunsData
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRoot7(parsed, "")
}

func encRoot8(v pkg_onzggl3sn52xizlt.Sent, at string) (any, error) {
	enc1, err := encSent(v, at)
	if err != nil {
		return nil, err
	}
	return enc1, nil
}

func decRoot8(raw any, at string) (pkg_onzggl3sn52xizlt.Sent, error) {
	var dvZero pkg_onzggl3sn52xizlt.Sent
	dec1, err := decSent(raw, at)
	if err != nil {
		return dvZero, err
	}
	return dec1, nil
}

// EncodeRoot8 converts v into the devalue value model.
func EncodeRoot8(v pkg_onzggl3sn52xizlt.Sent) (any, error) { return encRoot8(v, "") }

// DecodeRoot8 converts a devalue value model tree into a pkg_onzggl3sn52xizlt.Sent, rejecting any
// shape the type grammar does not admit.
func DecodeRoot8(raw any) (pkg_onzggl3sn52xizlt.Sent, error) { return decRoot8(raw, "") }

// StringifyRoot8 encodes v and serializes it with devalue.
func StringifyRoot8(v pkg_onzggl3sn52xizlt.Sent) (string, error) {
	encoded, err := encRoot8(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRoot8 parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.Sent.
func ParseRoot8(s string) (pkg_onzggl3sn52xizlt.Sent, error) {
	var zero pkg_onzggl3sn52xizlt.Sent
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRoot8(parsed, "")
}

func encRoot9(v pkg_onzggl3sn52xizlt.Waiting, at string) (any, error) {
	enc1, err := encWaiting(v, at)
	if err != nil {
		return nil, err
	}
	return enc1, nil
}

func decRoot9(raw any, at string) (pkg_onzggl3sn52xizlt.Waiting, error) {
	var dvZero pkg_onzggl3sn52xizlt.Waiting
	dec1, err := decWaiting(raw, at)
	if err != nil {
		return dvZero, err
	}
	return dec1, nil
}

// EncodeRoot9 converts v into the devalue value model.
func EncodeRoot9(v pkg_onzggl3sn52xizlt.Waiting) (any, error) { return encRoot9(v, "") }

// DecodeRoot9 converts a devalue value model tree into a pkg_onzggl3sn52xizlt.Waiting, rejecting any
// shape the type grammar does not admit.
func DecodeRoot9(raw any) (pkg_onzggl3sn52xizlt.Waiting, error) { return decRoot9(raw, "") }

// StringifyRoot9 encodes v and serializes it with devalue.
func StringifyRoot9(v pkg_onzggl3sn52xizlt.Waiting) (string, error) {
	encoded, err := encRoot9(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRoot9 parses a devalue document and decodes it into a pkg_onzggl3sn52xizlt.Waiting.
func ParseRoot9(s string) (pkg_onzggl3sn52xizlt.Waiting, error) {
	var zero pkg_onzggl3sn52xizlt.Waiting
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRoot9(parsed, "")
}

func encRoot10(v pkg_src.RunSnapshot, at string) (any, error) {
	enc1, err := encRunSnapshot(v, at)
	if err != nil {
		return nil, err
	}
	return enc1, nil
}

func decRoot10(raw any, at string) (pkg_src.RunSnapshot, error) {
	var dvZero pkg_src.RunSnapshot
	dec1, err := decRunSnapshot(raw, at)
	if err != nil {
		return dvZero, err
	}
	return dec1, nil
}

// EncodeRoot10 converts v into the devalue value model.
func EncodeRoot10(v pkg_src.RunSnapshot) (any, error) { return encRoot10(v, "") }

// DecodeRoot10 converts a devalue value model tree into a pkg_src.RunSnapshot, rejecting any
// shape the type grammar does not admit.
func DecodeRoot10(raw any) (pkg_src.RunSnapshot, error) { return decRoot10(raw, "") }

// StringifyRoot10 encodes v and serializes it with devalue.
func StringifyRoot10(v pkg_src.RunSnapshot) (string, error) {
	encoded, err := encRoot10(v, "")
	if err != nil {
		return "", err
	}
	return devalue.Stringify(encoded)
}

// ParseRoot10 parses a devalue document and decodes it into a pkg_src.RunSnapshot.
func ParseRoot10(s string) (pkg_src.RunSnapshot, error) {
	var zero pkg_src.RunSnapshot
	parsed, err := devalue.Parse(s, nil)
	if err != nil {
		return zero, err
	}
	return decRoot10(parsed, "")
}
