// Code generated by skgo. DO NOT EDIT.

package skgo

import (
	"context"
	"reflect"

	"github.com/tylergannon/skgo"

	skgo0 "github.com/tylergannon/gimble/internal/skgo/links/onzggl3sn52xizlt"
	skgo1 "github.com/tylergannon/gimble/internal/skgo/links/onzggl3sn52xizltf5yhe33kmvrxi4zplnyhe33kmvrxixi"
	skgo2 "github.com/tylergannon/gimble/internal/skgo/links/onzggl3sn52xizltf5yhe33kmvrxi4zplnyhe33kmvrxixjpmnxw45tfojzwc5djn5xhg"
	skgo3 "github.com/tylergannon/gimble/internal/skgo/links/onzggl3sn52xizltf5yhe33kmvrxi4zplnyhe33kmvrxixjpmnxw45tfojzwc5djn5xhgl23mnxw45tfojzwc5djn5xesrc5"
	skgo5 "github.com/tylergannon/gimble/internal/skgo/links/onzggl3sn52xizltf5yhe33kmvrxi4zplnyhe33kmvrxixjpoj2w44zplnzhk3sjiroq"
	skgotp0 "github.com/tylergannon/gimble/web/src"
)

// remote_cancelRun answers src/routes/control.remote.ts#cancelRun, a command.
//
// The argument is decoded by DecodeRoot0, generated by polytype for cancelRun's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot1, generated for its result type.
func remote_cancelRun(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot0(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo0.Skgo_cancelRun(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot1(out)
}

// requestedArg_cancelRun decodes one instance's argument for skgo.Requested, with the same
// decoder remote_cancelRun uses.
func requestedArg_cancelRun(arg any) (any, error) {
	in, err := DecodeRoot0(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_stopTurn answers src/routes/control.remote.ts#stopTurn, a command.
//
// The argument is decoded by DecodeRoot2, generated by polytype for stopTurn's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot1, generated for its result type.
func remote_stopTurn(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot2(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo0.Skgo_stopTurn(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot1(out)
}

// requestedArg_stopTurn decodes one instance's argument for skgo.Requested, with the same
// decoder remote_stopTurn uses.
func requestedArg_stopTurn(arg any) (any, error) {
	in, err := DecodeRoot2(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_createConversation answers src/routes/conversation.remote.ts#createConversation, a command.
//
// The argument is decoded by DecodeRoot3, generated by polytype for createConversation's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot4, generated for its result type.
func remote_createConversation(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot3(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo0.Skgo_createConversation(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot4(out)
}

// requestedArg_createConversation decodes one instance's argument for skgo.Requested, with the same
// decoder remote_createConversation uses.
func requestedArg_createConversation(arg any) (any, error) {
	in, err := DecodeRoot3(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_sendConversationMessage answers src/routes/conversation.remote.ts#sendConversationMessage, a command.
//
// The argument is decoded by DecodeRoot5, generated by polytype for sendConversationMessage's
// own parameter type: a shape it does not admit is a 400 naming the path,
// never a zero value.
// The result is encoded by EncodeRoot4, generated for its result type.
func remote_sendConversationMessage(ctx context.Context, call skgo.Call) (any, error) {
	if err := skgo.RequireArgument(call); err != nil {
		return nil, err
	}
	in, err := DecodeRoot5(call.Arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	out, err := skgo0.Skgo_sendConversationMessage(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot4(out)
}

// requestedArg_sendConversationMessage decodes one instance's argument for skgo.Requested, with the same
// decoder remote_sendConversationMessage uses.
func requestedArg_sendConversationMessage(arg any) (any, error) {
	in, err := DecodeRoot5(arg)
	if err != nil {
		return nil, skgo.BadRequest(err)
	}
	return in, nil
}

// remote_startImplement answers src/routes/implement_start.remote.ts#startImplement, a form.
//
// A form's submission is assigned onto the handler's own argument type:
// kit posts a form as binary form data, which can carry an uploaded File,
// and a File is not a value polytype describes.
// The result is encoded by EncodeRoot6, generated for its result type.
func remote_startImplement(ctx context.Context, call skgo.Call) (any, error) {
	var in skgo0.SkgoArg_startImplement
	if err := skgo.DecodeForm(call.Arg, &in); err != nil {
		return nil, err
	}
	out, err := skgo0.Skgo_startImplement(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot6(out)
}

// remote_answerInterview answers src/routes/interview.remote.ts#answerInterview, a form.
//
// A form's submission is assigned onto the handler's own argument type:
// kit posts a form as binary form data, which can carry an uploaded File,
// and a File is not a value polytype describes.
// The result is encoded by EncodeRoot7, generated for its result type.
func remote_answerInterview(ctx context.Context, call skgo.Call) (any, error) {
	var in skgo0.SkgoArg_answerInterview
	if err := skgo.DecodeForm(call.Arg, &in); err != nil {
		return nil, err
	}
	out, err := skgo0.Skgo_answerInterview(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot7(out)
}

// remote_startPyramidSummary answers src/routes/pyramidsummary_start.remote.ts#startPyramidSummary, a form.
//
// A form's submission is assigned onto the handler's own argument type:
// kit posts a form as binary form data, which can carry an uploaded File,
// and a File is not a value polytype describes.
// The result is encoded by EncodeRoot6, generated for its result type.
func remote_startPyramidSummary(ctx context.Context, call skgo.Call) (any, error) {
	var in skgo0.SkgoArg_startPyramidSummary
	if err := skgo.DecodeForm(call.Arg, &in); err != nil {
		return nil, err
	}
	out, err := skgo0.Skgo_startPyramidSummary(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot6(out)
}

// remote_startResearchDocument answers src/routes/researchdocument_start.remote.ts#startResearchDocument, a form.
//
// A form's submission is assigned onto the handler's own argument type:
// kit posts a form as binary form data, which can carry an uploaded File,
// and a File is not a value polytype describes.
// The result is encoded by EncodeRoot6, generated for its result type.
func remote_startResearchDocument(ctx context.Context, call skgo.Call) (any, error) {
	var in skgo0.SkgoArg_startResearchDocument
	if err := skgo.DecodeForm(call.Arg, &in); err != nil {
		return nil, err
	}
	out, err := skgo0.Skgo_startResearchDocument(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot6(out)
}

// remote_startReview answers src/routes/review_start.remote.ts#startReview, a form.
//
// A form's submission is assigned onto the handler's own argument type:
// kit posts a form as binary form data, which can carry an uploaded File,
// and a File is not a value polytype describes.
// The result is encoded by EncodeRoot6, generated for its result type.
func remote_startReview(ctx context.Context, call skgo.Call) (any, error) {
	var in skgo0.SkgoArg_startReview
	if err := skgo.DecodeForm(call.Arg, &in); err != nil {
		return nil, err
	}
	out, err := skgo0.Skgo_startReview(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot6(out)
}

// remote_steer answers src/routes/steer.remote.ts#steer, a form.
//
// A form's submission is assigned onto the handler's own argument type:
// kit posts a form as binary form data, which can carry an uploaded File,
// and a File is not a value polytype describes.
// The result is encoded by EncodeRoot8, generated for its result type.
func remote_steer(ctx context.Context, call skgo.Call) (any, error) {
	var in skgo0.SkgoArg_steer
	if err := skgo.DecodeForm(call.Arg, &in); err != nil {
		return nil, err
	}
	out, err := skgo0.Skgo_steer(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot8(out)
}

// remote_steerLoop answers src/routes/steer.remote.ts#steerLoop, a form.
//
// A form's submission is assigned onto the handler's own argument type:
// kit posts a form as binary form data, which can carry an uploaded File,
// and a File is not a value polytype describes.
// The result is encoded by EncodeRoot9, generated for its result type.
func remote_steerLoop(ctx context.Context, call skgo.Call) (any, error) {
	var in skgo0.SkgoArg_steerLoop
	if err := skgo.DecodeForm(call.Arg, &in); err != nil {
		return nil, err
	}
	out, err := skgo0.Skgo_steerLoop(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot9(out)
}

// remote_startValidateProduct answers src/routes/validateproduct_start.remote.ts#startValidateProduct, a form.
//
// A form's submission is assigned onto the handler's own argument type:
// kit posts a form as binary form data, which can carry an uploaded File,
// and a File is not a value polytype describes.
// The result is encoded by EncodeRoot6, generated for its result type.
func remote_startValidateProduct(ctx context.Context, call skgo.Call) (any, error) {
	var in skgo0.SkgoArg_startValidateProduct
	if err := skgo.DecodeForm(call.Arg, &in); err != nil {
		return nil, err
	}
	out, err := skgo0.Skgo_startValidateProduct(ctx, in)
	if err != nil {
		return nil, err
	}
	return EncodeRoot6(out)
}

// Remotes returns every remote function declared in the app, ready to hand
// to skgo.NewRemotes.
func Remotes() []*skgo.Remote {
	return []*skgo.Remote{
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindCommand,
			Module:    "src/routes/control.remote.ts",
			Name:      "cancelRun",
			Fn:        skgo0.Skgo_cancelRun,
			Call:      remote_cancelRun,
			DecodeArg: requestedArg_cancelRun,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindCommand,
			Module:    "src/routes/control.remote.ts",
			Name:      "stopTurn",
			Fn:        skgo0.Skgo_stopTurn,
			Call:      remote_stopTurn,
			DecodeArg: requestedArg_stopTurn,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindCommand,
			Module:    "src/routes/conversation.remote.ts",
			Name:      "createConversation",
			Fn:        skgo0.Skgo_createConversation,
			Call:      remote_createConversation,
			DecodeArg: requestedArg_createConversation,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:      skgo.KindCommand,
			Module:    "src/routes/conversation.remote.ts",
			Name:      "sendConversationMessage",
			Fn:        skgo0.Skgo_sendConversationMessage,
			Call:      remote_sendConversationMessage,
			DecodeArg: requestedArg_sendConversationMessage,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindForm,
			Module: "src/routes/implement_start.remote.ts",
			Name:   "startImplement",
			Fn:     skgo0.Skgo_startImplement,
			Call:   remote_startImplement,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindForm,
			Module: "src/routes/interview.remote.ts",
			Name:   "answerInterview",
			Fn:     skgo0.Skgo_answerInterview,
			Call:   remote_answerInterview,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindForm,
			Module: "src/routes/pyramidsummary_start.remote.ts",
			Name:   "startPyramidSummary",
			Fn:     skgo0.Skgo_startPyramidSummary,
			Call:   remote_startPyramidSummary,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindForm,
			Module: "src/routes/researchdocument_start.remote.ts",
			Name:   "startResearchDocument",
			Fn:     skgo0.Skgo_startResearchDocument,
			Call:   remote_startResearchDocument,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindForm,
			Module: "src/routes/review_start.remote.ts",
			Name:   "startReview",
			Fn:     skgo0.Skgo_startReview,
			Call:   remote_startReview,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindForm,
			Module: "src/routes/steer.remote.ts",
			Name:   "steer",
			Fn:     skgo0.Skgo_steer,
			Call:   remote_steer,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindForm,
			Module: "src/routes/steer.remote.ts",
			Name:   "steerLoop",
			Fn:     skgo0.Skgo_steerLoop,
			Call:   remote_steerLoop,
		}),
		skgo.NewRemote(skgo.RemoteSpec{
			Kind:   skgo.KindForm,
			Module: "src/routes/validateproduct_start.remote.ts",
			Name:   "startValidateProduct",
			Fn:     skgo0.Skgo_startValidateProduct,
			Call:   remote_startValidateProduct,
		}),
	}
}

// load_page answers src/routes/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_page(ctx context.Context) (any, error) {
	return skgo0.Skgo_load(ctx)
}

// load_projects_project_page answers src/routes/projects/[project]/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_projects_project_page(ctx context.Context) (any, error) {
	return skgo1.Skgo_load(ctx)
}

// load_projects_project_conversations_page answers src/routes/projects/[project]/conversations/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_projects_project_conversations_page(ctx context.Context) (any, error) {
	return skgo2.Skgo_Load(ctx)
}

// load_projects_project_conversations_conversationID_page answers src/routes/projects/[project]/conversations/[conversationID]/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_projects_project_conversations_conversationID_page(ctx context.Context) (any, error) {
	return skgo3.Skgo_Load(ctx)
}

// load_projects_project_runs_runID_page answers src/routes/projects/[project]/runs/[runID]/+page.server.ts.
//
// A load's result is the one value no generated encoder produces: it may
// hold a skgo.Deferred, and `Promise<T>` is not a projection of any Go
// type, so the value is encoded where a promise can still be recognised.
func load_projects_project_runs_runID_page(ctx context.Context) (any, error) {
	return skgo5.Skgo_load(ctx)
}

// Loads returns every server load declared in the app, ready to hand to
// skgo.NewLoads.
func Loads() []*skgo.ServerLoad {
	return []*skgo.ServerLoad{
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/+page.server.ts", Run: load_page}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/projects/[project]/+page.server.ts", Run: load_projects_project_page}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/projects/[project]/conversations/+page.server.ts", Run: load_projects_project_conversations_page}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/projects/[project]/conversations/[conversationID]/+page.server.ts", Run: load_projects_project_conversations_conversationID_page}),
		skgo.NewServerLoad(skgo.LoadSpec{Module: "src/routes/projects/[project]/runs/[runID]/+page.server.ts", Run: load_projects_project_runs_runID_page}),
	}
}

// Endpoints returns every server route declared in the app, ready to hand
// to skgo.NewEndpoints.
func Endpoints() []*skgo.Endpoint {
	return []*skgo.Endpoint{}
}

// Transport is the app's `transport` hook: the Go half of the encode/decode
// pairs src/hooks.ts declares. Hand it to skgo.RemoteConfig.Transport and
// skgo.LoadConfig.Transport.
//
// Each key must be spelled the same here and in src/hooks.ts: it is what the
// value travels under, and a client with no decoder for it cannot read the
// response at all.
func Transport() skgo.Transport {
	return skgo.Transport{
		"RunSnapshot": {
			Type:   reflect.TypeFor[skgotp0.RunSnapshot](),
			Encode: func(v any) (any, error) { return EncodeRunSnapshot(v.(skgotp0.RunSnapshot)) },
			Decode: func(raw any) (any, error) { return DecodeRunSnapshot(raw) },
		},
	}
}
