// Code generated by skgo. DO NOT EDIT.
import type { RequestEvent } from "@sveltejs/kit";
import type { InterviewRow } from "../../../lib/skgo/observation/types";
import type { RunItem } from "./types";

export const load = async (
  event: RequestEvent,
): Promise<{ items: Array<RunItem>; attention: Array<InterviewRow>; now: number }> => {
  throw new Error("skgo: implemented in Go");
};
