// Code generated by polytype. DO NOT EDIT.

/**
 * EventArg is what the page's live query subscribes with: which run, which stream generation, and the position it already holds. Kit holds this fixed for the life of one stream instance; the page opens a new instance (a new argument) whenever it needs to resume from a different position.
 */
export type EventArg = {
  run: string;
  stream: string;
  position: number;
};
