//go:build !jsonschema

// Code generated by internal/generate. DO NOT EDIT.

package main

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/spf13/cobra"
	"github.com/tylergannon/gimble"
	"github.com/tylergannon/gimble/internal/skgo/client"
	routes "github.com/tylergannon/gimble/internal/skgo/links/onzggl3sn52xizlt"
	"github.com/tylergannon/gimble/web"
	"github.com/tylergannon/polytype"
)

// implementationCommand is gimble run implement and submits the matching Form remote.
func implementationCommand(defaults map[gimble.WorkflowRole]string) *cobra.Command {
	var valueOutcomesFile string
	var valueMaxTasksPerOutcome int
	var sprintPlanningModel string
	var architecturalCritiqueModel string
	var codingModel string
	var qaOrchestrationModel string
	var workDir, project, instanceDir, conversation string
	var follow bool
	cmd := &cobra.Command{Use: "implement", Short: "Implement works through supplied outcomes until each is demonstrated.", Long: "Package implementation works through an ordered list of outcomes. Each\noutcome has its own bounded PromiseLoop and independent validation; there is\nno planner deciding which outcome comes next.\n\nThe caller supplies a local JSON file containing an array of outcome\nstrings. The workflow takes them in file order. Within an outcome, a planner\nmay choose another task only when validation finds a substantial gap. A\npassing judgment at 90–95% with only small gaps advances immediately to the\nnext outcome. An incomplete outcome stops the run; later outcomes do not\nstart.\n\nScope supervisors watch the planner, coder, and validator for unnecessary\ncomplexity, gold-plating, and work outside the selected outcome. They steer\nbut never gate completion. The workflow changes the working tree but does\nnot commit, push, merge, deploy, or edit the outcomes file. Checks gather\nevidence; the independent validator judges whether the behavior was seen.\n\nExample outcomes.json:\n\n\t[\"The CLI starts work in the selected instance\", \"The page observes that work live\"]\n\nExample invocation:\n\n\tgimble run implement --outcomes-file ./outcomes.json --max-tasks-per-outcome 3" + "\n\nThe selected persistent instance owns this run. --project selects its admitted repository; --work-dir selects the execution directory independently. --instance-dir selects the instance state directory (or GIMBLE_INSTANCE_DIR, default .gimble). --follow waits for terminal success or failure; otherwise the run continues after this client exits. Each role flag chooses a model and optional effort. Executable lookup, PATH, and provider configuration come from the instance startup environment.", Args: cobra.NoArgs}
	cmd.Flags().StringVar(&valueOutcomesFile, "outcomes-file", "", "OutcomesFile is a local JSON array of outcome strings, in execution order. (required)")
	cmd.Flags().IntVar(&valueMaxTasksPerOutcome, "max-tasks-per-outcome", 0, "MaxTasksPerOutcome bounds planner assignments for each outcome. (required)")
	_ = cmd.MarkFlagRequired("outcomes-file")
	_ = cmd.MarkFlagRequired("max-tasks-per-outcome")
	cmd.Flags().StringVar(&workDir, "work-dir", "", "execution directory (default: owning project)")
	cmd.Flags().StringVar(&project, "project", ".", "repository owning this run and its observation; admitted on first start")
	instanceDefault := os.Getenv("GIMBLE_INSTANCE_DIR")
	if instanceDefault == "" {
		instanceDefault = ".gimble"
	}
	cmd.Flags().StringVar(&instanceDir, "instance-dir", instanceDefault, "selected running instance state directory (default: GIMBLE_INSTANCE_DIR or .gimble)")
	cmd.Flags().StringVar(&conversation, "conversation", "", "associate this run with a conversation in the owning project")
	cmd.Flags().BoolVar(&follow, "follow", false, "wait for the hosted run's terminal result; without this flag the run survives client exit")
	sprintPlanningModelDefault := defaults[gimble.WorkflowRole("sprint-planning")]
	if sprintPlanningModelDefault == "" {
		cmd.Flags().StringVar(&sprintPlanningModel, "sprint-planning", "", "the model for role sprint-planning, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model")
		_ = cmd.MarkFlagRequired("sprint-planning")
	} else {
		cmd.Flags().StringVar(&sprintPlanningModel, "sprint-planning", sprintPlanningModelDefault, "advanced override for role sprint-planning, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model; omit this flag to use the displayed workflow default")
	}
	architecturalCritiqueModelDefault := defaults[gimble.WorkflowRole("architectural-critique")]
	if architecturalCritiqueModelDefault == "" {
		cmd.Flags().StringVar(&architecturalCritiqueModel, "architectural-critique", "", "the model for role architectural-critique, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model")
		_ = cmd.MarkFlagRequired("architectural-critique")
	} else {
		cmd.Flags().StringVar(&architecturalCritiqueModel, "architectural-critique", architecturalCritiqueModelDefault, "advanced override for role architectural-critique, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model; omit this flag to use the displayed workflow default")
	}
	codingModelDefault := defaults[gimble.WorkflowRole("coding")]
	if codingModelDefault == "" {
		cmd.Flags().StringVar(&codingModel, "coding", "", "the model for role coding, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model")
		_ = cmd.MarkFlagRequired("coding")
	} else {
		cmd.Flags().StringVar(&codingModel, "coding", codingModelDefault, "advanced override for role coding, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model; omit this flag to use the displayed workflow default")
	}
	qaOrchestrationModelDefault := defaults[gimble.WorkflowRole("qa-orchestration")]
	if qaOrchestrationModelDefault == "" {
		cmd.Flags().StringVar(&qaOrchestrationModel, "qa-orchestration", "", "the model for role qa-orchestration, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model")
		_ = cmd.MarkFlagRequired("qa-orchestration")
	} else {
		cmd.Flags().StringVar(&qaOrchestrationModel, "qa-orchestration", qaOrchestrationModelDefault, "advanced override for role qa-orchestration, as model or model:effort; OpenCode uses opencode/model or opencode/provider/model; omit this flag to use the displayed workflow default")
	}
	cmd.RunE = func(cmd *cobra.Command, _ []string) error {
		project, err := filepath.Abs(project)
		if err != nil {
			return err
		}
		if workDir == "" {
			workDir = project
		}
		workDir, err = filepath.Abs(workDir)
		if err != nil {
			return err
		}
		formInput := routes.StartImplementInput{ProjectDir: project, WorkDir: workDir, Conversation: conversation,
			OutcomesFile:              valueOutcomesFile,
			MaxTasksPerOutcome:        valueMaxTasksPerOutcome,
			RoleSprintPlanning:        polytype.Optional[string]{Present: cmd.Flags().Changed("sprint-planning"), Value: sprintPlanningModel},
			RoleArchitecturalCritique: polytype.Optional[string]{Present: cmd.Flags().Changed("architectural-critique"), Value: architecturalCritiqueModel},
			RoleCoding:                polytype.Optional[string]{Present: cmd.Flags().Changed("coding"), Value: codingModel},
			RoleQaOrchestration:       polytype.Optional[string]{Present: cmd.Flags().Changed("qa-orchestration"), Value: qaOrchestrationModel},
		}
		formClient, err := web.SelectedFormClient(cmd.Context(), instanceDir, project)
		if err != nil {
			return err
		}
		accepted, err := (client.Client{FormClient: formClient}).StartImplement(cmd.Context(), formInput)
		if err != nil {
			return fmt.Errorf("start implement: %w", err)
		}
		fmt.Fprintln(cmd.OutOrStdout(), accepted.RunID)
		if !follow {
			return nil
		}
		result, err := web.Follow(cmd.Context(), instanceDir, project, accepted.RunID)
		if err != nil {
			return err
		}
		if result.Status != "completed" {
			return fmt.Errorf("run %s %s: %s", accepted.RunID, result.Status, result.Error)
		}
		return nil
	}
	return cmd
}
