// Run with `just attest` or `go run ./ephemeral/attest/just-attest`. One
// live workflow touches every gimble primitive once, on the cheap tier
// (Codex gpt-5.6-luna, Claude claude-haiku-4-5-20251001), and prints what it
// saw: a scope with data, a schema turn and a text turn, a steer that lands
// and one that drops, an interrupt (a ctx cancel of one turn, followed by a
// further turn on the same session), a fork, a group of two, a supervised
// turn with an objection, and a loop of two laps. The runtime serves the
// live page for the run's duration and a little after.
package main

import (
	"context"
	"encoding/json"
	"errors"
	"flag"
	"fmt"
	"log"
	"os"
	"os/signal"
	"path/filepath"
	"strings"
	"syscall"
	"time"

	"github.com/tylergannon/gimble"
	"github.com/tylergannon/gimble/claude"
	"github.com/tylergannon/gimble/codex"
	"github.com/tylergannon/gimble/web"
)

const (
	codexModel  = "gpt-5.6-luna"
	claudeModel = "claude-haiku-4-5-20251001"
)

// impression is the attest's schema-turn output, written by hand against the
// public Output contract (Schema + ValidateJSON) rather than generated by
// polytype: a one-off ephemeral program has no lasting type to generate for.
type impression struct {
	Note string `json:"note"`
}

func (impression) Schema() json.RawMessage {
	return json.RawMessage(`{"type":"object","properties":{"note":{"type":"string"}},"required":["note"],"additionalProperties":false}`)
}

func (impression) ValidateJSON(data []byte) error {
	var v struct {
		Note *string `json:"note"`
	}
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	if v.Note == nil || strings.TrimSpace(*v.Note) == "" {
		return errors.New("note is required")
	}
	return nil
}

func main() {
	port := flag.Int("port", 8098, "loopback TCP port for the web application")
	hold := flag.Duration("hold", 3*time.Second, "how long to hold the server open after the run")
	flag.Parse()

	base, err := filepath.Abs("ephemeral/attest/just-attest")
	if err != nil {
		log.Fatal(err)
	}
	logs := filepath.Join(base, "logs")
	if err := os.RemoveAll(logs); err != nil {
		log.Fatal(err)
	}
	workspace := filepath.Join(base, "workspace")
	if err := os.RemoveAll(workspace); err != nil {
		log.Fatal(err)
	}
	if err := os.MkdirAll(workspace, 0o755); err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Models: codex=%s claude=%s\n", codexModel, claudeModel)

	ctx, stop := signal.NotifyContext(context.Background(), os.Interrupt, syscall.SIGTERM)
	defer stop()
	runtime, err := web.NewRuntime(ctx, logs, web.WithPort(*port))
	if err != nil {
		log.Fatal(err)
	}
	go announce(ctx, logs, *port)

	var laps int
	var interruptErr, postInterruptErr error
	var supervisedErr error

	runErr := runtime.Run(ctx, "just-attest", func(ctx context.Context) error {
		return gimble.Scope(ctx, "demo", func(ctx context.Context) error {
			// A scope with data.
			if err := gimble.Set(ctx, "goal", "touch every gimble primitive once, live, on the cheap tier"); err != nil {
				return err
			}
			fmt.Println("--- scope data ---")
			fmt.Println(gimble.ScopeText(ctx))

			worker := gimble.NewSession(ctx, "worker", codex.New(), codexModel, workspace)

			// A schema turn.
			imp, err := worker.Generate[impression](ctx,
				"Reply with JSON matching the schema: a two-to-four word made-up impression of this attest run in the \"note\" field. No tools.")
			if err != nil {
				return fmt.Errorf("schema turn: %w", err)
			}
			fmt.Printf("--- schema turn ---\nnote=%q\n", imp.Note)

			// A text turn.
			text, err := worker.Generate[gimble.Text](ctx,
				"Now restate that impression as one plain sentence. No tools.")
			if err != nil {
				return fmt.Errorf("text turn: %w", err)
			}
			fmt.Printf("--- text turn ---\n%s\n", text)

			// A steer that lands: sent while this session's turn is running.
			steerLandedErr := make(chan error, 1)
			go func() {
				time.Sleep(2 * time.Second)
				steerLandedErr <- worker.Steer(ctx, "Also use the word lighthouse somewhere in your final reply.")
			}()
			steered, err := worker.Generate[gimble.Text](ctx,
				"Run the shell command `sleep 6`. Then reply with one short sentence about the weather. No other tools.")
			landErr := <-steerLandedErr
			if err != nil {
				return fmt.Errorf("steered turn: %w", err)
			}
			fmt.Printf("--- steer (landed) ---\nsteer error=%v mentions lighthouse=%t reply=%q\n",
				landErr, strings.Contains(strings.ToLower(string(steered)), "lighthouse"), steered)

			// A steer that drops: sent with no turn running on this session.
			dropErr := worker.Steer(ctx, "too late: the turn already ended")
			fmt.Printf("--- steer (dropped) ---\nsteer error=%v\n", dropErr)

			// An interrupt: a ctx cancel of one turn, not Session.Interrupt
			// (issue 106's amendment; Session.Interrupt is deleted by #165).
			// The library's own contract is that cancelling ctx interrupts
			// the native turn and returns ctx.Err(); the proof here is that
			// the same session still takes a further turn afterward.
			turnCtx, cancelTurn := context.WithCancel(ctx)
			go func() {
				time.Sleep(3 * time.Second)
				cancelTurn()
			}()
			_, interruptErr = worker.Generate[gimble.Text](turnCtx,
				"Run the shell command `sleep 30`, then reply with the word done. No other tools.")
			fmt.Printf("--- interrupt ---\ncancelled turn error=%v (context.Canceled=%t)\n",
				interruptErr, errors.Is(interruptErr, context.Canceled))

			after, err := worker.Generate[gimble.Text](ctx, "Reply with exactly: still here. No tools.")
			postInterruptErr = err
			if err != nil {
				return fmt.Errorf("post-interrupt turn: %w", err)
			}
			fmt.Printf("post-interrupt turn: %q\n", after)

			// A fork.
			forked, err := worker.Fork(ctx, "worker-fork")
			if err != nil {
				return fmt.Errorf("fork: %w", err)
			}
			forkReply, err := forked.Generate[gimble.Text](ctx,
				"In one short sentence, confirm you already have the conversation so far. No tools.")
			if err != nil {
				return fmt.Errorf("fork turn: %w", err)
			}
			fmt.Printf("--- fork ---\n%s\n", forkReply)

			// A loop of two laps. Ordered before the primitives that need
			// Claude so that a Claude-side outage (see the group and the
			// supervised turn below) never prevents this Codex-only
			// primitive from completing and printing its own evidence.
			planner := gimble.NewSession(ctx, "planner", codex.New(), codexModel, workspace)
			loop := gimble.Loop(ctx, "laps", "The working directory contains lap1.txt and lap2.txt, each holding only its own file name. One file per task; end dispatch once both files exist.", planner)
			fmt.Println("--- loop ---")
			for taskCtx, task := range loop.Tasks {
				laps++
				fmt.Printf("lap %d task: %s\n", laps, task.Name)
				lapWorker := gimble.NewSession(taskCtx, "lap-worker", codex.New(), codexModel, workspace)
				reply, err := lapWorker.Generate[gimble.Text](taskCtx,
					"Complete this assignment.\n\n"+gimble.ScopeText(taskCtx))
				if err != nil {
					return fmt.Errorf("loop lap %d: %w", laps, err)
				}
				fmt.Printf("lap %d reply: %q\n", laps, reply)
				if err := gimble.Set(taskCtx, "result", string(reply)); err != nil {
					return err
				}
				if laps >= 4 {
					break // safety valve: never trust a live planner unboundedly
				}
			}
			if err := loop.Err(); err != nil {
				return fmt.Errorf("loop: %w", err)
			}
			fmt.Printf("loop laps observed: %d (2 expected)\n", laps)

			// A group of two.
			group := gimble.Group(ctx, "pair")
			group.Go("lane", func(ctx context.Context) error {
				lane := gimble.NewSession(ctx, "lane", codex.New(), codexModel, workspace)
				reply, err := lane.Generate[gimble.Text](ctx, "Reply with exactly: lane a done. No tools.")
				fmt.Printf("--- group lane a (codex) ---\n%q err=%v\n", reply, err)
				return err
			})
			group.Go("lane", func(ctx context.Context) error {
				lane := gimble.NewSession(ctx, "lane", claude.New(), claudeModel, workspace)
				reply, err := lane.Generate[gimble.Text](ctx, "Reply with exactly: lane b done. No tools.")
				fmt.Printf("--- group lane b (claude) ---\n%q err=%v\n", reply, err)
				return err
			})
			if err := group.Wait(); err != nil {
				return fmt.Errorf("group: %w", err)
			}

			// A supervised turn with an objection.
			reviewer := gimble.NewSession(ctx, "reviewer", claude.New(), claudeModel, workspace)
			objectionWorker := gimble.NewSession(ctx, "objection-worker", codex.New(), codexModel, workspace)
			objReply, err := objectionWorker.Generate[gimble.Text](ctx,
				"Run the shell command `sleep 10`. Then create a file named notes.secret in the working directory containing the text draft. Then explain in one sentence what you did.",
				gimble.WithSupervisor(reviewer,
					"If the agent creates any file whose name ends in .secret, object with exactly: delete notes.secret; secrets do not belong in this workspace. Otherwise return no objections.",
					gimble.WithInterval(2*time.Second)))
			supervisedErr = err
			if err != nil {
				return fmt.Errorf("supervised turn: %w", err)
			}
			fmt.Printf("--- supervised turn ---\n%s\n", objReply)
			return nil
		})
	})
	fmt.Printf("Run finished: err=%v\n", runErr)

	steerLanded, steerDropped, objectionLanded := scanSteerEvents(logs)
	fmt.Printf("=== summary ===\n"+
		"run error: %v\n"+
		"steer events observed: landed=%d dropped=%d objection_landed=%d\n"+
		"interrupt: cancelled turn returned context.Canceled=%t, further turn on same session error=%v\n"+
		"loop laps observed: %d\n",
		runErr, steerLanded, steerDropped, objectionLanded,
		errors.Is(interruptErr, context.Canceled), postInterruptErr, laps)

	fail := runErr != nil ||
		!errors.Is(interruptErr, context.Canceled) ||
		postInterruptErr != nil ||
		supervisedErr != nil ||
		steerLanded < 1 || steerDropped < 1
	if fail {
		fmt.Println("RESULT: FAIL")
	} else {
		fmt.Println("RESULT: PASS")
	}

	time.Sleep(*hold)
	if fail {
		os.Exit(1)
	}
}

// scanSteerEvents reads the run's own durable record and counts steer
// events by outcome, and objections (a steer landed from the reviewer
// session), so the summary is read from the run's evidence rather than
// only from in-process bookkeeping.
func scanSteerEvents(logs string) (landed, dropped, objectionLanded int) {
	matches, _ := filepath.Glob(filepath.Join(logs, "runs", "*", "run.jsonl"))
	if len(matches) == 0 {
		return
	}
	raw, err := os.ReadFile(matches[len(matches)-1])
	if err != nil {
		return
	}
	for _, line := range strings.Split(string(raw), "\n") {
		if strings.TrimSpace(line) == "" {
			continue
		}
		var rec struct {
			Event struct {
				Kind   string `json:"kind"`
				Source string `json:"source"`
				Landed bool   `json:"landed"`
			} `json:"event"`
		}
		if json.Unmarshal([]byte(line), &rec) != nil || rec.Event.Kind != "steer" {
			continue
		}
		if rec.Event.Landed {
			landed++
			if strings.Contains(rec.Event.Source, "reviewer") {
				objectionLanded++
			}
		} else {
			dropped++
		}
	}
	return
}

// announce prints the run id and its page URL as soon as the run directory
// appears, so the page can be opened while the run is still going.
func announce(ctx context.Context, logs string, port int) {
	for ctx.Err() == nil {
		entries, err := os.ReadDir(filepath.Join(logs, "runs"))
		if err == nil {
			for _, entry := range entries {
				if entry.IsDir() {
					fmt.Printf("Run: %s\nPage: http://127.0.0.1:%d/runs/%s\n", entry.Name(), port, entry.Name())
					return
				}
			}
		}
		time.Sleep(50 * time.Millisecond)
	}
}
